import { translate } from "../campaign/i18n-core";
import { useMemo, useState } from "react";
import { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import { effectiveMaximumModels, memberCount, treasury as draftTreasury } from "@domain/campaign/kernel/document";
import { useCampaignApp, useCloseOnCampaignError } from "../campaign/useCampaignApp";
import { knowledgeName, localizedLabel, warriorAbilities, warriorAbilityRef, warriorName, resourceAmount } from "../campaign/displayText";
import { presentationOutput } from "../campaign/presentation-output";
import { textJoin, textNumber, textSymbol, warbandPersonalName, warriorCharacteristic, warriorPersonalName } from "../campaign/presentation-values";
import type { CampaignDocument } from "../campaign/types";
import { HirelingsPanel } from "../hirelings/HirelingsPanel";
import { EquipmentPanel } from "../equipment/EquipmentPanel";
import { ManualCorrectionsPanel } from "../economy/ManualCorrectionsPanel";
import { KnowledgeHint } from "../campaign/KnowledgeHint";
import { NumberStepper } from "../common/NumberStepper";

const HERO_ADVANCES = new Set([2, 4, 6, 8, 11, 14, 17, 20, 24, 28, 32, 36, 41, 46, 51, 57, 63, 69, 76, 83, 90]);
const HENCHMAN_ADVANCES = new Set([2, 5, 9, 14]);

export function ExperienceTrack({ experience, kind, locale }: { experience: number; kind: string; locale: "es" | "en" }) {
  const henchman = kind === "henchman" || kind === "hireling"; const capacity = henchman ? 14 : 90;
  const advances = henchman ? HENCHMAN_ADVANCES : HERO_ADVANCES;
  const progress = Math.min(100, Math.max(0, experience / capacity * 100));
  return <div className="draft-experience"><span><small>{presentationOutput(translate({ key: "ui.af6e18f48665" }, locale))}</small><b>{presentationOutput(textNumber(experience, locale))}</b></span><div className={`experience-track ${henchman ? "track-henchman" : "track-hero"}`} aria-label={presentationOutput(textJoin([textNumber(experience, locale), translate({ key: "unit.experience" }, locale)]))}><span className="experience-progress" style={{ width: `${progress}%` }} />{Array.from({ length: capacity }, (_, index) => index + 1).map((value) => <i key={value} className={`${value <= experience ? "earned" : ""} ${advances.has(value) ? "advance" : ""}`} />)}</div></div>;
}

export function DraftWorkspace({ document, knowledge, locale }: { document: CampaignDocument; knowledge: ArtefactKnowledgeReader; locale: "es" | "en" }) {
  const app = useCampaignApp();
  const [tab, setTab] = useState<"hero" | "henchman" | "hireling" | "inventory">("hero"); const [profileId, setProfileId] = useState(""); const [quantity, setQuantity] = useState(1); const [name, setName] = useState(""); const [showAdd, setShowAdd] = useState(false); const [renameId, setRenameId] = useState<string | null>(null); const [renameValue, setRenameValue] = useState(""); const [skillsId, setSkillsId] = useState<string | null>(null); const [skillId, setSkillId] = useState(""); const [skillReason, setSkillReason] = useState(""); const [skillSearch, setSkillSearch] = useState(""); const [inventoryDialog, setInventoryDialog] = useState<"trade" | "manual" | null>(null); const [stashChoice, setStashChoice] = useState(""); const [stashQuantity, setStashQuantity] = useState(1);
  useCloseOnCampaignError(() => { setShowAdd(false); setRenameId(null); setSkillsId(null); setInventoryDialog(null); });
  const profiles = useMemo(() => knowledge.list("profile").filter((row) => row.band_id === document.campaign.identity.band_id), [knowledge, document.campaign.identity.band_id]);
  const items = useMemo(() => new Map(knowledge.list("item").map((row) => [String(row.item_id), row])), [knowledge]);
  const stashOffers = useMemo(() => {
    const prices = new Map<string, number | null>();
    for (const profile of profiles) for (const raw of Array.isArray(profile.equipment_access) ? profile.equipment_access as Record<string, unknown>[] : []) {
      const itemId = String(raw.item_id ?? ""); const price = typeof raw.cost === "number" ? raw.cost : null;
      if (itemId && items.has(itemId) && (!prices.has(itemId) || (price !== null && (prices.get(itemId) === null || price < prices.get(itemId)!)))) prices.set(itemId, price);
    }
    return [...prices].map(([itemId, price]) => ({ itemId, price })).sort((left, right) => knowledge.recordText(items.get(left.itemId), "name", locale).localeCompare(knowledge.recordText(items.get(right.itemId), "name", locale)));
  }, [profiles, items, locale, knowledge]);
  const availableProfiles = profiles.filter((row) => (row.type === "hero" ? "hero" : "henchman") === tab).sort((a,b)=>knowledge.recordText(a, "name", locale).localeCompare(knowledge.recordText(b, "name", locale),locale));
  const selected = availableProfiles.find((row) => String(row.id) === profileId);
  const models = memberCount(document.campaign.warriors);
  const heroes = document.campaign.warriors.reduce((sum, warrior) => sum + (warrior.kind === "hero" ? warrior.quantity ?? 1 : 0), 0);
  const treasury = draftTreasury(document.campaign);
  const maximumModels = effectiveMaximumModels(document.campaign);
  const legal = models >= document.campaign.configuration.minimum_models && models <= maximumModels && heroes > 0 && heroes <= document.campaign.configuration.hero_limit && treasury >= 0;
  const t = ({ eyebrow: translate({ key: "ui.9a8120609a70" }, locale), draft: translate({ key: "ui.7c144476336f" }, locale), description: translate({ key: "ui.ca62accf5ce4" }, locale), models: translate({ key: "ui.e9882ce840bb" }, locale), heroes: translate({ key: "ui.516877a59173" }, locale), hero: translate({ key: "ui.3ee456a0fa58" }, locale), henchman: translate({ key: "ui.c9fc68d81cd2" }, locale), hireling: translate({ key: "ui.bdd0dc3c8e41" }, locale), inventory: translate({ key: "ui.07bf0f8e6179" }, locale), roster: translate({ key: "ui.3087408dfd27" }, locale), remove: translate({ key: "ui.d985a24dd184" }, locale), rename: translate({ key: "ui.af7d7211e1f2" }, locale), save: translate({ key: "ui.a4e236e5f40f" }, locale), add: translate({ key: "ui.b816c2ac76d3" }, locale), addMember: translate({ key: "ui.c5b382df9a77" }, locale), profile: translate({ key: "ui.c0f38b97c8b9" }, locale), name: translate({ key: "ui.9b9a13d3e4d1" }, locale), optional: translate({ key: "ui.63746864b6c5" }, locale), quantity: translate({ key: "ui.8f2846965a7a" }, locale), addRoster: translate({ key: "ui.d060bd3d491f" }, locale), equipment: translate({ key: "ui.6e167b0c85f2" }, locale), stash: translate({ key: "ui.c9ef5329ca7c" }, locale), chooseEquipment: translate({ key: "ui.72ed1a822e89" }, locale), buy: translate({ key: "ui.016b8cb68ffe" }, locale), buyStash: translate({ key: "ui.c4d270cc75b6" }, locale), purchased: translate({ key: "ui.4e36bff8a305" }, locale), variant: translate({ key: "ui.cfb9fed1fbd3" }, locale), none: translate({ key: "ui.3ca5db996aaf" }, locale), commit: translate({ key: "ui.7ff41d8a718b" }, locale), invalid: translate({ key: "ui.59c0c628cd74" }, locale) });
  const add = async () => { if (!selected) return false; const kind = selected.type === "hero" ? "hero" : "henchman"; const ok=await app.runAction("composeDraft", { band_id: document.campaign.identity.band_id, name, locale, rows: [{ profile_id: String(selected.id), kind, quantity, equipment: [] }] }); if(ok){setName("");setQuantity(1);} return ok; };
  const skills = knowledge.list("skill");
  const isLeader = (warrior: CampaignDocument["campaign"]["warriors"][number]) => warrior.kind === "hero" && warriorAbilities(knowledge, warrior).some((rule) => /(^|--|\.)leader$/i.test(rule));
  const resourceLabel = (rows: readonly (readonly [string, number])[]) => textJoin(rows.map(([key, value]) => resourceAmount(key === "gold" ? "gold_crowns" : key, value, locale)), " + ");
  return <section className="draft-workspace" aria-label={presentationOutput(translate({ key: "ui.46fd11152a80" }, locale))}><div className="page-title"><p>{presentationOutput(textJoin([t.eyebrow, t.draft], " · "))}</p><h2>{presentationOutput(warbandPersonalName(document.campaign, locale))}</h2><span>{presentationOutput(t.description)}</span><span>{presentationOutput(textJoin([textJoin([textNumber(models, locale), textSymbol("/"), textNumber(maximumModels, locale)], ""), t.models, textSymbol("·"), textJoin([textNumber(heroes, locale), textSymbol("/"), textNumber(document.campaign.configuration.hero_limit, locale)], ""), t.heroes, textSymbol("·"), textNumber(treasury, locale), translate({ key: "unit.gold" }, locale)]))}</span></div>
    <div className="draft-toolbar"><nav className="segmented-tabs prominent" aria-label={presentationOutput(t.roster)}>{(["hero","henchman","hireling","inventory"] as const).map((key)=><button key={key} className={tab===key ? "active" : ""} aria-pressed={tab===key} onClick={()=>{setTab(key);setProfileId("");setShowAdd(false);}}>{presentationOutput(t[key])}</button>)}</nav>{(tab === "hero" || tab === "henchman") && <button className="primary" type="button" onClick={() => setShowAdd(true)}>{presentationOutput(textSymbol("＋"))} {presentationOutput(tab === "hero" ? (translate({ key: "ui.05888bd6c491" }, locale)) : (translate({ key: "ui.78304e805012" }, locale)))}</button>}</div>
    {tab === "inventory" && <section className="draft-inventory"><div className="inventory-actionbar"><p>{presentationOutput(translate({ key: "ui.52cac94aec81" }, locale))}</p><div><button type="button" onClick={() => setInventoryDialog("manual")}>{presentationOutput(translate({ key: "ui.30ae8c333dd4" }, locale))}</button><button className="primary" type="button" onClick={() => setInventoryDialog("trade")}>{presentationOutput(translate({ key: "ui.f6d2a8faa9f6" }, locale))}</button></div></div><EquipmentPanel document={document} knowledge={knowledge} locale={locale} showTitle={false}/></section>}
    {(tab === "hero" || tab === "henchman" || tab === "hireling") && <div className="draft-columns"><article><h3>{presentationOutput(t[tab])}</h3>
      {document.campaign.warriors.filter((warrior) => warrior.kind === tab).sort((a,b)=>tab === "hero" ? Number(isLeader(b))-Number(isLeader(a)) : tab === "hireling" ? warriorName(knowledge,a,locale).localeCompare(warriorName(knowledge,b,locale),locale) : 0).map((warrior) => {
        const localizedProfile = knowledgeName(knowledge, warrior.kind === "hireling" ? "hireling" : "profile", warrior.profile_id, locale, undefined, warrior.kind === "hireling" ? undefined : document.campaign.identity.band_id);
        const displayName = warriorPersonalName(warrior, locale);
        const equipment = warrior.equipment.map((item) => ({ id: item.item_id, quantity: item.quantity }));
        const skillNames = [...new Map(warriorAbilities(knowledge, warrior).map((skill) => {
          const ref = warriorAbilityRef(knowledge, skill, warrior.profile_id, document.campaign.identity.band_id);
          const entry = { ...ref, kind: ref.kind === "skill" ? "skill" as const : "rule" as const, text: knowledgeName(knowledge, ref.kind, ref.id, locale, ref.profileId, ref.bandId) };
          return [entry.text, entry] as const;
        })).values()];
        return <article className={`draft-warrior-card${warrior.kind !== "hireling" ? " has-options" : ""}`} key={warrior.id}>
          <div className="draft-card-body">
            <section className="draft-card-identity">
              <header><div><strong>{presentationOutput(displayName)}</strong><span>{presentationOutput(localizedProfile)}</span></div><span className="draft-card-cost"><b>{warrior.kind === "hireling" && <>{presentationOutput(translate({ key: "ui.38a17e3eb9cc" }, locale))}{presentationOutput(textSymbol(":"))} </>}{presentationOutput(textNumber(warrior.quantity ?? 1, locale))}  {presentationOutput(textSymbol("×"))} {presentationOutput(textNumber(warrior.cost, locale))} {presentationOutput(translate({ key: "unit.gold" }, locale))}</b>{warrior.kind === "hireling" && <small>{presentationOutput(translate({ key: "ui.15e8bb635504" }, locale))} {presentationOutput(textSymbol(":"))} {warrior.upkeep_resources?.length ? presentationOutput(resourceLabel(warrior.upkeep_resources)) : presentationOutput(textSymbol("—"))}</small>}</span></header>
              <div className="stats">{(["M", "WS", "BS", "S", "T", "W", "I", "A", "Ld"] as const).filter((key) => Object.hasOwn(warrior.stats, key)).map((key) => <span key={key}><small>{presentationOutput(localizedLabel(key, locale))}</small>{presentationOutput(warriorCharacteristic(warrior, key, locale))}</span>)}</div>
            </section>
            <section className="draft-card-box"><h4>{presentationOutput(translate({ key: "ui.c0081f2540bc" }, locale))}</h4>{equipment.map((item) => <p key={item.id}><KnowledgeHint knowledge={knowledge} kind="item" id={item.id} locale={locale} quantity={item.quantity}/></p>)}{equipment.length === 0 && <p>{presentationOutput(textSymbol("—"))}</p>}</section>
            <section className="draft-card-box"><h4>{presentationOutput(translate({ key: "ui.bee89842c456" }, locale))}</h4>{skillNames.map((skill) => <p key={skill.id}><KnowledgeHint knowledge={knowledge} kind={skill.kind} id={skill.id} profileId={skill.profileId} bandId={skill.bandId} locale={locale}/></p>)}{skillNames.length === 0 && <p>{presentationOutput(textSymbol("—"))}</p>}</section>
          </div>
          <footer><div className="skill-access"><small>{presentationOutput(translate({ key: "ui.7644f4e6a00f" }, locale))}</small><span>{presentationOutput(warrior.skill_access?.length ? textJoin(warrior.skill_access.map((key) => localizedLabel(key, locale)), " · ") : textSymbol("—"))}</span></div><ExperienceTrack experience={warrior.experience} kind={warrior.kind} locale={locale}/></footer>
          {warrior.kind !== "hireling" && <details className="draft-card-options"><summary aria-label={presentationOutput(textJoin([translate({ key: "ui.486630e6322e" }, locale), displayName]))}>{presentationOutput(textSymbol("•••"))}</summary><div className="draft-card-menu">{warrior.kind === "henchman" && <button type="button" onClick={() => void app.runAction("adjustDraftGroup", { warrior_id: warrior.id, delta: 1 })}>{presentationOutput(t.addMember)}</button>}<button onClick={() => { setRenameId(warrior.id); setRenameValue(warrior.name); }}>{presentationOutput(translate({ key: "ui.af7d7211e1f2" }, locale))}</button><button onClick={() => { setSkillsId(warrior.id); setSkillId(""); setSkillReason(""); }}>{presentationOutput(translate({ key: "ui.3d578cbd5517" }, locale))}</button><button className="danger-text" onClick={() => void app.runAction("removeDraftRow", { warrior_id: warrior.id })}>{presentationOutput(translate({ key: "ui.d985a24dd184" }, locale))}</button></div></details>}
        </article>;
      })}
    </article></div>}
    {tab === "hireling" && <HirelingsPanel document={document} listings={knowledge} locale={locale} mode="hirelings" />}
    {renameId && <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="draft-rename-title"><button className="close" aria-label={presentationOutput(translate({ key: "ui.b61e7685256c" }, locale))} onClick={() => setRenameId(null)}> {presentationOutput(textSymbol("×"))} </button><h3 id="draft-rename-title">{presentationOutput(translate({ key: "ui.107636e8193d" }, locale))}</h3><label>{presentationOutput(translate({ key: "ui.073689804a50" }, locale))}<input autoFocus value={renameValue} onChange={(event) => setRenameValue(event.target.value)} /></label><div className="modal-actions"><button onClick={() => setRenameId(null)}>{presentationOutput(translate({ key: "ui.45ac97c49aed" }, locale))}</button><button className="primary" disabled={!renameValue.trim()} data-disabled-reason={(!renameValue.trim() ? (translate({ key: "disabled.c44a547ea0" }, locale)) : undefined) === undefined ? undefined : presentationOutput((!renameValue.trim() ? (translate({ key: "disabled.c44a547ea0" }, locale)) : undefined)!)} onClick={() => void app.runAction("renameWarrior", { warrior_id: renameId, name: renameValue.trim() }).then((ok) => { if (ok) setRenameId(null); })}>{presentationOutput(translate({ key: "ui.28a60b494c65" }, locale))}</button></div></section></div>}
    {skillsId && <div className="modal-backdrop" role="presentation"><section className="modal draft-skills-dialog" role="dialog" aria-modal="true" aria-labelledby="draft-skills-title"><button className="close" aria-label={presentationOutput(translate({ key: "ui.b61e7685256c" }, locale))} onClick={() => { setSkillsId(null); setSkillSearch(""); }}> {presentationOutput(textSymbol("×"))} </button><h3 id="draft-skills-title">{presentationOutput(translate({ key: "ui.6f16bc2c08e1" }, locale))}</h3><label>{presentationOutput(translate({ key: "ui.f090bb15551e" }, locale))}<input autoFocus value={skillSearch} onChange={(event) => setSkillSearch(event.target.value)} placeholder={presentationOutput(translate({ key: "ui.c510b1ecd70b" }, locale))} /></label><label>{presentationOutput(translate({ key: "ui.842e16b36c7d" }, locale))}<select value={skillId} onChange={(event) => setSkillId(event.target.value)}><option value="">{presentationOutput(translate({ key: "ui.88d46d36996d" }, locale))}</option>{skills.filter((skill) => knowledge.recordText(skill, "name", locale).toLocaleLowerCase().includes(skillSearch.toLocaleLowerCase())).sort((a,b)=>knowledge.recordText(a, "name", locale).localeCompare(knowledge.recordText(b, "name", locale),locale)).map((skill) => <option key={String(skill.id)} value={String(skill.id)}>{presentationOutput(knowledge.recordText(skill, "name", locale))}</option>)}</select></label><label>{presentationOutput(translate({ key: "ui.3fcafd5c5068" }, locale))}<input value={skillReason} onChange={(event) => setSkillReason(event.target.value)} /></label><div className="modal-actions"><button disabled={!skillId || !skillReason.trim()} data-disabled-reason={(!skillId ? (translate({ key: "disabled.55dfb81882" }, locale)) : !skillReason.trim() ? (translate({ key: "disabled.e5f5931dbb" }, locale)) : undefined) === undefined ? undefined : presentationOutput((!skillId ? (translate({ key: "disabled.55dfb81882" }, locale)) : !skillReason.trim() ? (translate({ key: "disabled.e5f5931dbb" }, locale)) : undefined)!)} onClick={() => void app.runAction("setManualSkill", { warrior_id: skillsId, skill_id: skillId, present: false, reason: skillReason })}>{presentationOutput(translate({ key: "ui.388b8804f87d" }, locale))}</button><button className="primary" disabled={!skillId || !skillReason.trim()} data-disabled-reason={(!skillId ? (translate({ key: "disabled.55dfb81882" }, locale)) : !skillReason.trim() ? (translate({ key: "disabled.e5f5931dbb" }, locale)) : undefined) === undefined ? undefined : presentationOutput((!skillId ? (translate({ key: "disabled.55dfb81882" }, locale)) : !skillReason.trim() ? (translate({ key: "disabled.e5f5931dbb" }, locale)) : undefined)!)} onClick={() => void app.runAction("setManualSkill", { warrior_id: skillsId, skill_id: skillId, present: true, reason: skillReason })}>{presentationOutput(translate({ key: "ui.450e8c76d0ed" }, locale))}</button></div></section></div>}
    {inventoryDialog === "trade" && <div className="modal-backdrop" role="presentation"><section className="modal inventory-trade-dialog" role="dialog" aria-modal="true" aria-labelledby="inventory-trade-title"><button className="close" aria-label={presentationOutput(translate({ key: "ui.b61e7685256c" }, locale))} onClick={() => setInventoryDialog(null)}> {presentationOutput(textSymbol("×"))} </button><h3 id="inventory-trade-title">{presentationOutput(translate({ key: "ui.f6d2a8faa9f6" }, locale))}</h3><p>{presentationOutput(textJoin([textNumber(treasury, locale), translate({ key: "unit.gold" }, locale)]))}</p><label>{presentationOutput(t.equipment)}<select autoFocus value={stashChoice} onChange={(event) => setStashChoice(event.target.value)}><option value="">{presentationOutput(t.chooseEquipment)}</option>{stashOffers.map((offer) => <option key={offer.itemId} value={offer.itemId}>{presentationOutput(textJoin([knowledge.recordText(items.get(offer.itemId), "name", locale), textSymbol("·"), offer.price === null ? translate({ key: "knowledge.unavailable" }, locale) : textNumber(offer.price, locale), translate({ key: "unit.gold" }, locale)]))}</option>)}</select></label><div className="warrior-control-row"><span>{presentationOutput(t.quantity)}</span><NumberStepper locale={locale} label={translate({ key: "number.quantity" }, locale)} value={stashQuantity} min={1} onChange={setStashQuantity}/></div><button className="primary" type="button" disabled={!stashChoice} data-disabled-reason={(!stashChoice ? (translate({ key: "disabled.f0b0b508d0" }, locale)) : undefined) === undefined ? undefined : presentationOutput((!stashChoice ? (translate({ key: "disabled.f0b0b508d0" }, locale)) : undefined)!)} onClick={() => void app.runAction("buyDraftStashItem", { item_id: stashChoice, quantity: stashQuantity })}>{presentationOutput(t.buyStash)}</button><h4>{presentationOutput(t.stash)}</h4><ul className="trade-stash-list">{document.campaign.inventory.filter((item) => item.stash > 0).map((item) => <li key={item.id}><span><KnowledgeHint knowledge={knowledge} kind="item" id={item.id} locale={locale} quantity={item.stash}/></span><button type="button" onClick={() => void app.runAction("removeDraftStashItem", { item_id: item.id, quantity: 1 })}>{presentationOutput(translate({ key: "ui.2c999464170e" }, locale))}</button></li>)}</ul></section></div>}
    {inventoryDialog === "manual" && <div className="modal-backdrop" role="presentation"><section className="modal inventory-manual-dialog" role="dialog" aria-modal="true" aria-labelledby="inventory-manual-title"><button className="close" aria-label={presentationOutput(translate({ key: "ui.b61e7685256c" }, locale))} onClick={() => setInventoryDialog(null)}> {presentationOutput(textSymbol("×"))} </button><h3 id="inventory-manual-title">{presentationOutput(translate({ key: "ui.7fbc176b9749" }, locale))}</h3><ManualCorrectionsPanel document={document} knowledge={knowledge} locale={locale}/></section></div>}
    {showAdd && <div className="modal-backdrop" role="presentation"><section className="modal draft-add-dialog" role="dialog" aria-modal="true" aria-labelledby="draft-add-title"><button className="close" aria-label={presentationOutput(translate({ key: "ui.b61e7685256c" }, locale))} onClick={() => setShowAdd(false)}> {presentationOutput(textSymbol("×"))} </button><form onSubmit={(event) => { event.preventDefault(); void add().then((ok) => { if (ok) setShowAdd(false); }); }}><h3 id="draft-add-title">{presentationOutput(t.add)}</h3><fieldset className="draft-profile-options"><legend>{presentationOutput(t.profile)}</legend>{availableProfiles.map((row,index) => <label key={String(row.id)}><input autoFocus={index===0} type="radio" name="draft-profile" value={String(row.id)} checked={profileId===String(row.id)} onChange={(event) => setProfileId(event.target.value)}/><span>{presentationOutput(knowledge.recordText(row, "name", locale))} <b>{presentationOutput(textNumber(row.cost ?? 0, locale))} {presentationOutput(translate({ key: "unit.gold" }, locale))}</b></span></label>)}</fieldset><label>{presentationOutput(t.name)}<input value={name} onChange={(event) => setName(event.target.value)} placeholder={presentationOutput(t.optional)} /></label>{tab === "henchman" && <div className="warrior-control-row"><span>{presentationOutput(t.quantity)}</span><NumberStepper locale={locale} label={translate({ key: "number.quantity" }, locale)} value={quantity} min={1} max={15} onChange={setQuantity}/></div>}<div className="modal-actions"><button type="button" onClick={() => setShowAdd(false)}>{presentationOutput(translate({ key: "ui.45ac97c49aed" }, locale))}</button><button className="primary" disabled={!selected} data-disabled-reason={(!selected ? (translate({ key: "disabled.10be476f3c" }, locale)) : undefined) === undefined ? undefined : presentationOutput((!selected ? (translate({ key: "disabled.10be476f3c" }, locale)) : undefined)!)} type="submit">{presentationOutput(t.addRoster)}</button></div></form></section></div>}
    <button className="primary" disabled={!legal} data-disabled-reason={(!legal ? t.invalid : undefined) === undefined ? undefined : presentationOutput((!legal ? t.invalid : undefined)!)} onClick={() => void app.runAction("commitInitialWarband", {})}>{presentationOutput(t.commit)}</button>{!legal && <p role="status">{presentationOutput(t.invalid)}</p>}</section>;
}
