import { useMemo, useState } from "react";
import { ArtefactKnowledgeReader, resolveName } from "@adapters/knowledge-reader/index";
import { treasury as draftTreasury } from "@domain/campaign/kernel/document";
import { useCampaignApp } from "../campaign/useCampaignApp";
import { knowledgeName, localizedLabel, warriorAbilities, warriorName } from "../campaign/displayText";
import type { CampaignDocument } from "../campaign/types";
import { HirelingsPanel } from "../hirelings/HirelingsPanel";
import { EquipmentPanel } from "../equipment/EquipmentPanel";
import { ManualCorrectionsPanel } from "../economy/ManualCorrectionsPanel";
import { KnowledgeHint } from "../campaign/KnowledgeHint";
import { adaptCharacteristicValue } from "@app/rules/distance-display";
import { NumberStepper } from "../common/NumberStepper";

const HERO_ADVANCES = new Set([2, 4, 6, 8, 11, 14, 17, 20, 24, 28, 32, 36, 41, 46, 51, 57, 63, 69, 76, 83, 90]);
const HENCHMAN_ADVANCES = new Set([2, 5, 9, 14]);

function readableRuleId(value: string): string {
  const leaf = value.split("--").at(-1) ?? value.split(".").at(-1) ?? value;
  return leaf.replaceAll("-", " ").replace(/\b\p{L}/gu, (letter) => letter.toUpperCase());
}

export function ExperienceTrack({ experience, kind, locale }: { experience: number; kind: string; locale: "es" | "en" }) {
  const henchman = kind === "henchman" || kind === "hireling"; const capacity = henchman ? 14 : 90;
  const advances = henchman ? HENCHMAN_ADVANCES : HERO_ADVANCES;
  const progress = Math.min(100, Math.max(0, experience / capacity * 100));
  return <div className="draft-experience"><span><small>{locale === "es" ? "EXPERIENCIA" : "EXPERIENCE"}</small><b>{experience}</b></span><div className={`experience-track ${henchman ? "track-henchman" : "track-hero"}`} aria-label={`${experience} XP`}><span className="experience-progress" style={{ width: `${progress}%` }} />{Array.from({ length: capacity }, (_, index) => { const value=index+1; return <i key={value} className={`${value <= experience ? "earned" : ""} ${advances.has(value) ? "advance" : ""}`} />; })}</div></div>;
}

export function DraftWorkspace({ document, knowledge, locale }: { document: CampaignDocument; knowledge: ArtefactKnowledgeReader; locale: "es" | "en" }) {
  const app = useCampaignApp();
  const [tab, setTab] = useState<"hero" | "henchman" | "hireling" | "inventory">("hero"); const [profileId, setProfileId] = useState(""); const [quantity, setQuantity] = useState(1); const [name, setName] = useState(""); const [showAdd, setShowAdd] = useState(false); const [renameId, setRenameId] = useState<string | null>(null); const [renameValue, setRenameValue] = useState(""); const [skillsId, setSkillsId] = useState<string | null>(null); const [skillId, setSkillId] = useState(""); const [skillReason, setSkillReason] = useState(""); const [skillSearch, setSkillSearch] = useState(""); const [inventoryDialog, setInventoryDialog] = useState<"trade" | "manual" | null>(null); const [stashChoice, setStashChoice] = useState(""); const [stashQuantity, setStashQuantity] = useState(1);
  const profiles = useMemo(() => knowledge.list("profile").filter((row) => row.band_id === document.campaign.identity.band_id), [knowledge, document.campaign.identity.band_id]);
  const profileNames = useMemo(() => new Map(profiles.map((row) => [String(row.id), resolveName(row, locale)])), [profiles, locale]);
  const items = useMemo(() => new Map(knowledge.list("item").map((row) => [String(row.item_id), row])), [knowledge]);
  const stashOffers = useMemo(() => {
    const prices = new Map<string, number | null>();
    for (const profile of profiles) for (const raw of Array.isArray(profile.equipment_access) ? profile.equipment_access as Record<string, unknown>[] : []) {
      const itemId = String(raw.item_id ?? ""); const price = typeof raw.cost === "number" ? raw.cost : null;
      if (itemId && items.has(itemId) && (!prices.has(itemId) || (price !== null && (prices.get(itemId) === null || price < prices.get(itemId)!)))) prices.set(itemId, price);
    }
    return [...prices].map(([itemId, price]) => ({ itemId, price })).sort((left, right) => resolveName(items.get(left.itemId)!, locale).localeCompare(resolveName(items.get(right.itemId)!, locale)));
  }, [profiles, items, locale]);
  const availableProfiles = profiles.filter((row) => (row.type === "hero" ? "hero" : "henchman") === tab).sort((a,b)=>resolveName(a,locale).localeCompare(resolveName(b,locale),locale));
  const selected = availableProfiles.find((row) => String(row.id) === profileId);
  const models = document.campaign.warriors.reduce((sum, warrior) => sum + (warrior.quantity ?? 1), 0);
  const heroes = document.campaign.warriors.reduce((sum, warrior) => sum + (warrior.kind === "hero" ? warrior.quantity ?? 1 : 0), 0);
  const treasury = draftTreasury(document.campaign);
  const legal = models >= document.campaign.configuration.minimum_models && models <= document.campaign.configuration.maximum_models && heroes > 0 && heroes <= document.campaign.configuration.hero_limit && treasury >= 0;
  const t = locale === "es" ? { eyebrow:"BANDA INICIAL",draft:"BORRADOR",description:"Construye la banda que se convertirá en el estado inicial inmutable de la campaña.",models:"miniaturas",heroes:"héroes",hero:"HÉROES",henchman:"SECUACES",hireling:"ESPADAS DE ALQUILER",inventory:"INVENTARIO",roster:"Guerreros",remove:"Retirar",rename:"Renombrar",save:"Guardar",add:"Añadir guerreros",addMember:"Añadir miembro",profile:"Perfil",name:"Nombre",optional:"Opcional",quantity:"Cantidad",addRoster:"Añadir a la banda",equipment:"Equipo inicial",stash:"Reserva inicial",chooseEquipment:"Elige equipo…",buy:"Comprar para el grupo",buyStash:"Comprar para reserva",purchased:"Comprado",variant:"Variante de Mercenarios",none:"Sin variante",commit:"Confirmar banda inicial",invalid:"El borrador debe respetar los límites de miniaturas, héroes y tesorería antes de confirmarlo." } : { eyebrow:"INITIAL WARBAND",draft:"DRAFT",description:"Build the warband that will become the campaign's immutable starting state.",models:"models",heroes:"heroes",hero:"HEROES",henchman:"HENCHMEN",hireling:"HIRED SWORDS",inventory:"INVENTORY",roster:"Roster",remove:"Remove",rename:"Rename",save:"Save",add:"Add warriors",addMember:"Add member",profile:"Profile",name:"Name",optional:"Optional",quantity:"Quantity",addRoster:"Add to roster",equipment:"Starting equipment",stash:"Starting stash",chooseEquipment:"Choose equipment…",buy:"Buy for group",buyStash:"Buy for stash",purchased:"Purchased",variant:"Mercenary variant",none:"No variant",commit:"Commit initial warband",invalid:"Draft must meet model, hero and treasury limits before commit." };
  const add = async () => { if (!selected) return false; const kind = selected.type === "hero" ? "hero" : "henchman"; const ok=await app.runAction("composeDraft", { band_id: document.campaign.identity.band_id, name, rows: [{ profile_id: String(selected.id), kind, quantity, equipment: [] }] }); if(ok){setName("");setQuantity(1);} return ok; };
  const skills = knowledge.list("skill");
  const isLeader = (warrior: CampaignDocument["campaign"]["warriors"][number]) => warrior.kind === "hero" && warriorAbilities(knowledge, warrior).some((rule) => /(^|--|\.)leader$/i.test(rule));
  const resourceLabel = (rows: readonly (readonly [string, number])[]) => rows.map(([key, value]) => `${value} ${key === "gold" || key === "gold_crowns" ? "gc" : key === "wyrdstone_fragments" ? (locale === "es" ? "piedra bruja" : "wyrdstone") : key === "treasures" ? (locale === "es" ? "tesoros" : "treasures") : key === "campaign_points" ? (locale === "es" ? "puntos de campaña" : "campaign points") : key}`).join(" + ");
  return <section className="draft-workspace" aria-label={locale === "es" ? "Borrador de banda inicial" : "Initial warband draft"}><div className="page-title"><p>{t.eyebrow} · {t.draft}</p><h2>{document.campaign.identity.warband_name}</h2><span>{t.description}</span><span>{models}/{document.campaign.configuration.maximum_models} {t.models} · {heroes}/{document.campaign.configuration.hero_limit} {t.heroes} · {treasury} gc</span></div>
    <div className="draft-toolbar"><nav className="segmented-tabs prominent" aria-label={t.roster}>{(["hero","henchman","hireling","inventory"] as const).map((key)=><button key={key} className={tab===key ? "active" : ""} aria-pressed={tab===key} onClick={()=>{setTab(key);setProfileId("");setShowAdd(false);}}>{t[key]}</button>)}</nav>{(tab === "hero" || tab === "henchman") && <button className="primary" type="button" onClick={() => setShowAdd(true)}>＋ {tab === "hero" ? (locale === "es" ? "AÑADIR HÉROE" : "ADD HERO") : (locale === "es" ? "AÑADIR GRUPO" : "ADD GROUP")}</button>}</div>
    {tab === "inventory" && <section className="draft-inventory"><div className="inventory-actionbar"><p>{locale === "es" ? "Mueve el equipo entre los guerreros y la reserva." : "Move equipment between warriors and the stash."}</p><div><button type="button" onClick={() => setInventoryDialog("manual")}>{locale === "es" ? "AÑADIR OBJETO / RECURSOS" : "ADD ITEM / RESOURCES"}</button><button className="primary" type="button" onClick={() => setInventoryDialog("trade")}>{locale === "es" ? "COMPRAR Y VENDER" : "BUY AND SELL"}</button></div></div><EquipmentPanel document={document} knowledge={knowledge} locale={locale} showTitle={false}/></section>}
    {(tab === "hero" || tab === "henchman" || tab === "hireling") && <div className="draft-columns"><article><h3>{t[tab]}</h3>
      {document.campaign.warriors.filter((warrior) => warrior.kind === tab).sort((a,b)=>tab === "hero" ? Number(isLeader(b))-Number(isLeader(a)) : tab === "hireling" ? warriorName(knowledge,a,locale).localeCompare(warriorName(knowledge,b,locale),locale) : 0).map((warrior) => {
        const localizedProfile = profileNames.get(String(warrior.profile_id)) ?? warrior.profile_name;
        const displayName = warriorName(knowledge, warrior, locale);
        const equipment = warrior.equipment.map((item) => ({ id: item.item_id, text: item.quantity + "× " + knowledgeName(knowledge, "item", item.item_id, locale, item.name) }));
        const skillNames = [...new Map(warriorAbilities(knowledge, warrior).map((skill) => {
          const kind = skill.startsWith("skill.") ? "skill" : "rule";
          const entry = { id: skill, kind, text: knowledgeName(knowledge, kind, skill, locale, readableRuleId(skill), warrior.profile_id, document.campaign.identity.band_id) } as const;
          return [entry.text, entry] as const;
        })).values()];
        return <article className={`draft-warrior-card${warrior.kind !== "hireling" ? " has-options" : ""}`} key={warrior.id}>
          <div className="draft-card-body">
            <section className="draft-card-identity">
              <header><div><strong>{displayName}</strong><span>{localizedProfile}</span></div><span className="draft-card-cost"><b>{warrior.kind === "hireling" ? `${locale === "es" ? "Contratación" : "Hiring fee"}: ` : ""}{warrior.quantity ?? 1} × {warrior.cost} gc</b>{warrior.kind === "hireling" && <small>{locale === "es" ? "Mantenimiento" : "Upkeep"}: {warrior.upkeep_resources?.length ? resourceLabel(warrior.upkeep_resources) : "—"}</small>}</span></header>
              <div className="stats">{Object.entries(warrior.stats).map(([key,value])=><span key={key}><small>{localizedLabel(key, locale)}</small>{adaptCharacteristicValue(key, value, locale, warrior.stat_modifiers?.[key] ?? 0)}</span>)}</div>
            </section>
            <section className="draft-card-box"><h4>{locale === "es" ? "EQUIPAMIENTO" : "EQUIPMENT"}</h4>{equipment.map((item) => <p key={item.id}><KnowledgeHint knowledge={knowledge} kind="item" id={item.id} locale={locale}>{item.text}</KnowledgeHint></p>)}{equipment.length === 0 && <p>—</p>}</section>
            <section className="draft-card-box"><h4>{locale === "es" ? "HABILIDADES / REGLAS" : "SKILLS / RULES"}</h4>{skillNames.map((skill) => <p key={skill.id}><KnowledgeHint knowledge={knowledge} kind={skill.kind} id={skill.id} profileId={warrior.profile_id} bandId={document.campaign.identity.band_id} locale={locale}>{skill.text}</KnowledgeHint></p>)}{skillNames.length === 0 && <p>—</p>}</section>
          </div>
          <footer><div className="skill-access"><small>{locale === "es" ? "ACCESO A HABILIDADES" : "SKILL ACCESS"}</small><span>{(warrior.skill_access ?? []).map((key) => localizedLabel(key, locale)).join(" · ") || "—"}</span></div><ExperienceTrack experience={warrior.experience} kind={warrior.kind} locale={locale}/></footer>
          {warrior.kind !== "hireling" && <details className="draft-card-options"><summary aria-label={(locale === "es" ? "Opciones de " : "Options for ") + displayName}>•••</summary><div className="draft-card-menu">{warrior.kind === "henchman" && <button type="button" onClick={() => void app.runAction("adjustDraftGroup", { warrior_id: warrior.id, delta: 1 })}>{t.addMember}</button>}<button onClick={() => { setRenameId(warrior.id); setRenameValue(warrior.name); }}>{locale === "es" ? "Renombrar" : "Rename"}</button><button onClick={() => { setSkillsId(warrior.id); setSkillId(""); setSkillReason(""); }}>{locale === "es" ? "Editar habilidades" : "Edit Skills"}</button><button className="danger-text" onClick={() => void app.runAction("removeDraftRow", { warrior_id: warrior.id })}>{locale === "es" ? "Retirar" : "Remove"}</button></div></details>}
        </article>;
      })}
    </article></div>}
    {tab === "hireling" && <HirelingsPanel document={document} listings={knowledge} locale={locale} mode="hirelings" />}
    {renameId && <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="draft-rename-title"><button className="close" aria-label={locale === "es" ? "Cerrar" : "Close"} onClick={() => setRenameId(null)}>×</button><h3 id="draft-rename-title">{locale === "es" ? "RENOMBRAR" : "RENAME"}</h3><label>{locale === "es" ? "Nuevo nombre" : "New name"}<input autoFocus value={renameValue} onChange={(event) => setRenameValue(event.target.value)} /></label><div className="modal-actions"><button onClick={() => setRenameId(null)}>{locale === "es" ? "Cancelar" : "Cancel"}</button><button className="primary" disabled={!renameValue.trim()} data-disabled-reason={!renameValue.trim() ? (locale === "es" ? "Introduce un nombre para el guerrero." : "Enter a warrior name.") : undefined} onClick={() => void app.runAction("renameWarrior", { warrior_id: renameId, name: renameValue.trim() }).then((ok) => { if (ok) setRenameId(null); })}>{locale === "es" ? "GUARDAR" : "SAVE"}</button></div></section></div>}
    {skillsId && <div className="modal-backdrop" role="presentation"><section className="modal draft-skills-dialog" role="dialog" aria-modal="true" aria-labelledby="draft-skills-title"><button className="close" aria-label={locale === "es" ? "Cerrar" : "Close"} onClick={() => { setSkillsId(null); setSkillSearch(""); }}>×</button><h3 id="draft-skills-title">{locale === "es" ? "EDITAR HABILIDADES" : "EDIT SKILLS"}</h3><label>{locale === "es" ? "Buscar habilidad" : "Search skill"}<input autoFocus value={skillSearch} onChange={(event) => setSkillSearch(event.target.value)} placeholder={locale === "es" ? "Escribe para filtrar…" : "Type to filter…"} /></label><label>{locale === "es" ? "Habilidad" : "Skill"}<select value={skillId} onChange={(event) => setSkillId(event.target.value)}><option value="">{locale === "es" ? "Selecciona una habilidad…" : "Select a skill…"}</option>{skills.filter((skill) => resolveName(skill, locale).toLocaleLowerCase().includes(skillSearch.toLocaleLowerCase())).sort((a,b)=>resolveName(a,locale).localeCompare(resolveName(b,locale),locale)).map((skill) => <option key={String(skill.id)} value={String(skill.id)}>{resolveName(skill, locale)}</option>)}</select></label><label>{locale === "es" ? "Motivo de la corrección" : "Reason for correction"}<input value={skillReason} onChange={(event) => setSkillReason(event.target.value)} /></label><div className="modal-actions"><button disabled={!skillId || !skillReason.trim()} data-disabled-reason={!skillId ? (locale === "es" ? "Selecciona una habilidad." : "Select a skill.") : !skillReason.trim() ? (locale === "es" ? "Explica el motivo de la corrección." : "Explain the reason for the correction.") : undefined} onClick={() => void app.runAction("setManualSkill", { warrior_id: skillsId, skill_id: skillId, present: false, reason: skillReason })}>{locale === "es" ? "QUITAR" : "REMOVE"}</button><button className="primary" disabled={!skillId || !skillReason.trim()} data-disabled-reason={!skillId ? (locale === "es" ? "Selecciona una habilidad." : "Select a skill.") : !skillReason.trim() ? (locale === "es" ? "Explica el motivo de la corrección." : "Explain the reason for the correction.") : undefined} onClick={() => void app.runAction("setManualSkill", { warrior_id: skillsId, skill_id: skillId, present: true, reason: skillReason })}>{locale === "es" ? "AÑADIR" : "ADD"}</button></div></section></div>}
    {inventoryDialog === "trade" && <div className="modal-backdrop" role="presentation"><section className="modal inventory-trade-dialog" role="dialog" aria-modal="true" aria-labelledby="inventory-trade-title"><button className="close" aria-label={locale === "es" ? "Cerrar" : "Close"} onClick={() => setInventoryDialog(null)}>×</button><h3 id="inventory-trade-title">{locale === "es" ? "COMPRAR Y VENDER" : "BUY AND SELL"}</h3><p>{treasury} gc</p><label>{t.equipment}<select autoFocus value={stashChoice} onChange={(event) => setStashChoice(event.target.value)}><option value="">{t.chooseEquipment}</option>{stashOffers.map((offer) => <option key={offer.itemId} value={offer.itemId}>{resolveName(items.get(offer.itemId)!, locale)} · {offer.price ?? "?"} gc</option>)}</select></label><div className="warrior-control-row"><span>{t.quantity}</span><NumberStepper label={t.quantity} value={stashQuantity} min={1} onChange={setStashQuantity}/></div><button className="primary" type="button" disabled={!stashChoice} data-disabled-reason={!stashChoice ? (locale === "es" ? "Selecciona un objeto para comprar." : "Select an item to buy.") : undefined} onClick={() => void app.runAction("buyDraftStashItem", { item_id: stashChoice, quantity: stashQuantity })}>{t.buyStash}</button><h4>{t.stash}</h4><ul className="trade-stash-list">{document.campaign.inventory.filter((item) => item.stash > 0).map((item) => <li key={item.id}><span><KnowledgeHint knowledge={knowledge} kind="item" id={item.id} locale={locale}>{item.stash} × {knowledgeName(knowledge, "item", item.id, locale, item.name)}</KnowledgeHint></span><button type="button" onClick={() => void app.runAction("removeDraftStashItem", { item_id: item.id, quantity: 1 })}>{locale === "es" ? "Vender 1" : "Sell 1"}</button></li>)}</ul></section></div>}
    {inventoryDialog === "manual" && <div className="modal-backdrop" role="presentation"><section className="modal inventory-manual-dialog" role="dialog" aria-modal="true" aria-labelledby="inventory-manual-title"><button className="close" aria-label={locale === "es" ? "Cerrar" : "Close"} onClick={() => setInventoryDialog(null)}>×</button><h3 id="inventory-manual-title">{locale === "es" ? "AJUSTES MANUALES" : "MANUAL ADJUSTMENTS"}</h3><ManualCorrectionsPanel document={document} knowledge={knowledge} locale={locale}/></section></div>}
    {showAdd && <div className="modal-backdrop" role="presentation"><section className="modal draft-add-dialog" role="dialog" aria-modal="true" aria-labelledby="draft-add-title"><button className="close" aria-label={locale === "es" ? "Cerrar" : "Close"} onClick={() => setShowAdd(false)}>×</button><form onSubmit={(event) => { event.preventDefault(); void add().then((ok) => { if (ok) setShowAdd(false); }); }}><h3 id="draft-add-title">{t.add}</h3><fieldset className="draft-profile-options"><legend>{t.profile}</legend>{availableProfiles.map((row,index) => <label key={String(row.id)}><input autoFocus={index===0} type="radio" name="draft-profile" value={String(row.id)} checked={profileId===String(row.id)} onChange={(event) => setProfileId(event.target.value)}/><span>{resolveName(row, locale)} <b>{String(row.cost ?? 0)} gc</b></span></label>)}</fieldset><label>{t.name}<input value={name} onChange={(event) => setName(event.target.value)} placeholder={t.optional} /></label>{tab === "henchman" && <div className="warrior-control-row"><span>{t.quantity}</span><NumberStepper label={t.quantity} value={quantity} min={1} max={15} onChange={setQuantity}/></div>}<div className="modal-actions"><button type="button" onClick={() => setShowAdd(false)}>{locale === "es" ? "Cancelar" : "Cancel"}</button><button className="primary" disabled={!selected} data-disabled-reason={!selected ? (locale === "es" ? "Selecciona un perfil para añadirlo." : "Select a profile to add.") : undefined} type="submit">{t.addRoster}</button></div></form></section></div>}
    <button className="primary" disabled={!legal} data-disabled-reason={!legal ? t.invalid : undefined} onClick={() => void app.runAction("commitInitialWarband", {})}>{t.commit}</button>{!legal && <p role="status">{t.invalid}</p>}</section>;
}
