import { useMemo, useState } from "react";
import { ArtefactKnowledgeReader, resolveName } from "@adapters/knowledge-reader/index";
import { treasury as draftTreasury } from "@domain/campaign/kernel/document";
import { useCampaignApp } from "../campaign/useCampaignApp";
import type { CampaignDocument } from "../campaign/types";

function DraftStashRow({ item, warriors, locale }: { item: CampaignDocument["campaign"]["inventory"][number]; warriors: CampaignDocument["campaign"]["warriors"]; locale: "es" | "en" }) {
  const app = useCampaignApp(); const [target, setTarget] = useState("");
  const t = locale === "es" ? { remove: "Retirar", choose: "Elige guerrero…", assign: "Asignar" } : { remove: "Remove", choose: "Choose warrior…", assign: "Assign" };
  return <p>{item.stash}× {item.name} <button type="button" onClick={() => void app.runAction("removeDraftStashItem", { item_id: item.id, quantity: 1 })}>{t.remove}</button><select aria-label={`${t.assign} ${item.name}`} value={target} onChange={(event) => setTarget(event.target.value)}><option value="">{t.choose}</option>{warriors.map((warrior) => <option value={warrior.id} key={warrior.id}>{warrior.name}</option>)}</select><button type="button" disabled={!target} onClick={() => void app.runAction("assignEquipment", { warrior_id: target, item_id: item.id, quantity: 1, direction: "equip" })}>{t.assign}</button></p>;
}

export function DraftWorkspace({ document, knowledge, locale }: { document: CampaignDocument; knowledge: ArtefactKnowledgeReader; locale: "es" | "en" }) {
  const app = useCampaignApp();
  const [profileId, setProfileId] = useState(""); const [quantity, setQuantity] = useState(1); const [name, setName] = useState(""); const [equipmentChoices, setEquipmentChoices] = useState<Record<string, string>>({}); const [renameValues, setRenameValues] = useState<Record<string, string>>({}); const [stashChoice, setStashChoice] = useState(""); const [stashQuantity, setStashQuantity] = useState(1);
  const profiles = useMemo(() => knowledge.list("profile").filter((row) => row.band_id === document.campaign.identity.band_id), [knowledge, document.campaign.identity.band_id]);
  const profileNames = useMemo(() => new Map(profiles.map((row) => [String(row.id), resolveName(row, locale)])), [profiles, locale]);
  const items = useMemo(() => new Map(knowledge.list("item").map((row) => [String(row.item_id), row])), [knowledge]);
  const stashOffers = useMemo(() => {
    const prices = new Map<string, number | null>();
    for (const profile of profiles) for (const raw of Array.isArray(profile.equipment_access) ? profile.equipment_access as Record<string, unknown>[] : []) {
      const itemId = String(raw.item_id ?? ""); const price = typeof raw.cost === "number" ? raw.cost : null;
      if (itemId && items.has(itemId) && (!prices.has(itemId) || (price !== null && (prices.get(itemId) === null || price < prices.get(itemId)!)))) prices.set(itemId, price);
    }
    return [...prices].map(([itemId, price]) => ({ itemId, price })).sort((left, right) => resolveName(items.get(left.itemId)!, locale).localeCompare(resolveName(items.get(right.itemId)!, locale)));
  }, [profiles, items, locale]);
  const selected = profiles.find((row) => String(row.id) === profileId) ?? profiles[0];
  const models = document.campaign.warriors.reduce((sum, warrior) => sum + (warrior.quantity ?? 1), 0);
  const heroes = document.campaign.warriors.reduce((sum, warrior) => sum + (warrior.kind === "hero" ? warrior.quantity ?? 1 : 0), 0);
  const treasury = draftTreasury(document.campaign);
  const legal = models >= document.campaign.configuration.minimum_models && models <= document.campaign.configuration.maximum_models && heroes > 0 && heroes <= document.campaign.configuration.hero_limit && treasury >= 0;
  const t = locale === "es" ? { eyebrow:"BANDA INICIAL",models:"miniaturas",heroes:"héroes",roster:"Guerreros",remove:"Retirar",rename:"Renombrar",save:"Guardar",increase:"Añadir miembro",decrease:"Retirar miembro",add:"Añadir guerreros",profile:"Perfil",name:"Nombre",optional:"Opcional",quantity:"Cantidad",addRoster:"Añadir a la banda",equipment:"Equipo inicial",stash:"Reserva inicial",chooseEquipment:"Elige equipo…",buy:"Comprar para el grupo",buyStash:"Comprar para reserva",purchased:"Comprado",commit:"Confirmar banda inicial",invalid:"El borrador debe respetar los límites de miniaturas, héroes y tesorería antes de confirmarlo." } : { eyebrow:"INITIAL WARBAND",models:"models",heroes:"heroes",roster:"Roster",remove:"Remove",rename:"Rename",save:"Save",increase:"Add member",decrease:"Remove member",add:"Add warriors",profile:"Profile",name:"Name",optional:"Optional",quantity:"Quantity",addRoster:"Add to roster",equipment:"Starting equipment",stash:"Starting stash",chooseEquipment:"Choose equipment…",buy:"Buy for group",buyStash:"Buy for stash",purchased:"Purchased",commit:"Commit initial warband",invalid:"Draft must meet model, hero and treasury limits before commit." };
  const add = async () => { if (!selected) return; const kind = selected.type === "hero" ? "hero" : "henchman"; await app.runAction("composeDraft", { band_id: document.campaign.identity.band_id, name, rows: [{ profile_id: String(selected.id), kind, quantity, equipment: [] }] }); setName(""); setQuantity(1); };
  const offersFor = (warrior: CampaignDocument["campaign"]["warriors"][number]) => {
    const profile = profiles.find((row) => String(row.id) === String(warrior.profile_id));
    const access = Array.isArray(profile?.equipment_access) ? profile.equipment_access as Record<string, unknown>[] : [];
    return access.map((offer) => ({ itemId: String(offer.item_id ?? ""), price: typeof offer.cost === "number" ? offer.cost : null }))
      .filter((offer) => offer.itemId && items.has(offer.itemId));
  };
  return <section className="draft-workspace" aria-label="Initial warband draft"><div className="page-title"><p>{t.eyebrow}</p><h2>{document.campaign.identity.warband_name}</h2><span>{models}/{document.campaign.configuration.maximum_models} {t.models} · {heroes}/{document.campaign.configuration.hero_limit} {t.heroes} · {treasury} gc</span></div>
    <div className="draft-columns"><article><h3>{t.roster}</h3>{document.campaign.warriors.map((warrior) => { const localizedProfile = profileNames.get(String(warrior.profile_id)) ?? warrior.profile_name; const displayName = warrior.name === warrior.profile_name ? localizedProfile : warrior.name; const offers = offersFor(warrior); const choice = equipmentChoices[warrior.id] ?? ""; const renameValue = renameValues[warrior.id] ?? warrior.name; return <div className="roster-row" key={warrior.id}><div><strong>{displayName}</strong><span>{localizedProfile} · {warrior.quantity ?? 1} × {warrior.cost} gc</span><span><input aria-label={`${t.rename} ${displayName}`} value={renameValue} onChange={(event) => setRenameValues((current) => ({ ...current, [warrior.id]: event.target.value }))}/><button disabled={!renameValue.trim() || renameValue === warrior.name} onClick={() => void app.runAction("renameWarrior", { warrior_id: warrior.id, name: renameValue })}>{t.save}</button></span>{warrior.kind === "henchman" && <span><button aria-label={`${t.decrease} ${displayName}`} onClick={() => void app.runAction("adjustDraftGroup", { warrior_id: warrior.id, delta: -1 })}>−</button><button aria-label={`${t.increase} ${displayName}`} onClick={() => void app.runAction("adjustDraftGroup", { warrior_id: warrior.id, delta: 1 })}>+</button></span>}{warrior.equipment.filter((item) => item.acquisition === "purchase").map((item) => <span key={`${item.item_id}:${item.unit_cost}`}>{t.purchased}: {item.quantity}× {item.name} · {item.unit_cost ?? 0} gc <button onClick={() => void app.runAction("removeDraftEquipment", { warrior_id: warrior.id, item_id: item.item_id, unit_price: item.unit_cost })}>{t.remove}</button></span>)}{offers.length > 0 && <span><select aria-label={`${t.equipment} ${displayName}`} value={choice} onChange={(event) => setEquipmentChoices((current) => ({ ...current, [warrior.id]: event.target.value }))}><option value="">{t.chooseEquipment}</option>{offers.map((offer) => <option key={offer.itemId} value={offer.itemId}>{resolveName(items.get(offer.itemId)!, locale)} · {offer.price ?? "?"} gc</option>)}</select><button disabled={!choice} onClick={() => void app.runAction("buyDraftEquipment", { warrior_id: warrior.id, item_id: choice })}>{t.buy}</button></span>}</div><button onClick={() => void app.runAction("removeDraftRow", { warrior_id: warrior.id })}>{t.remove}</button></div>; })}</article>
      <form onSubmit={(event) => { event.preventDefault(); void add(); }}><h3>{t.add}</h3><label>{t.profile}<select value={String(selected?.id ?? "")} onChange={(event) => setProfileId(event.target.value)}>{profiles.map((row) => <option value={String(row.id)} key={String(row.id)}>{resolveName(row, locale)} · {String(row.cost ?? 0)} gc</option>)}</select></label><label>{t.name}<input value={name} onChange={(event) => setName(event.target.value)} placeholder={t.optional} /></label><label>{t.quantity}<input type="number" min="1" max="15" value={quantity} onChange={(event) => setQuantity(Math.max(1, Number(event.target.value)))} /></label><button className="primary" disabled={!selected} type="submit">{t.addRoster}</button><h3>{t.stash}</h3><label>{t.equipment}<select value={stashChoice} onChange={(event) => setStashChoice(event.target.value)}><option value="">{t.chooseEquipment}</option>{stashOffers.map((offer) => <option key={offer.itemId} value={offer.itemId}>{resolveName(items.get(offer.itemId)!, locale)} · {offer.price ?? "?"} gc</option>)}</select></label><label>{t.quantity}<input type="number" min="1" value={stashQuantity} onChange={(event) => setStashQuantity(Math.max(1, Number(event.target.value)))} /></label><button type="button" disabled={!stashChoice} onClick={() => void app.runAction("buyDraftStashItem", { item_id: stashChoice, quantity: stashQuantity })}>{t.buyStash}</button>{document.campaign.inventory.filter((item) => item.stash > 0).map((item) => <DraftStashRow key={item.id} item={item} warriors={document.campaign.warriors} locale={locale}/>)}</form></div>
    <button className="primary" disabled={!legal} onClick={() => void app.runAction("commitInitialWarband", {})}>{t.commit}</button>{!legal && <p role="status">{t.invalid}</p>}</section>;
}
