schema_version: 2
band_id: lost-the-mou
profiles:
- id: barons
  name: Barons
  type: hero
  cost: 55
  experience: 15
  characteristics:
    M: 4
    WS: 4
    BS: 3
    S: 3
    T: 3
    W: 1
    I: 4
    A: 1
    Ld: 6
  equipment_lists:
  - the-lost-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - shooting
  - strength
  - speed
  - special
  source:
    manual: broheim.net
    printed_page: 3
    section: Heroes / 1-3 Barons
    url: https://broheim.net/downloads/warbands/supplement/mousillon/The%20Lost.pdf
  source_path:
  - heroes
  - 1-3 Barons
  name_i18n:
    es: Barones
  rule_ids:
  - barons--mob-mentality
  combat_traits: {}
- id: elders
  name: Elders
  type: hero
  cost: 25
  experience: 8
  characteristics:
    M: 4
    WS: 2
    BS: 2
    S: 3
    T: 3
    W: 1
    I: 3
    A: 1
    Ld: 5
  equipment_lists:
  - the-lost-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - academic
  - special
  source:
    manual: broheim.net
    printed_page: 4
    section: Heroes / 0-2 Elders
    url: https://broheim.net/downloads/warbands/supplement/mousillon/The%20Lost.pdf
  source_path:
  - heroes
  - 0-2 Elders
  name_i18n:
    es: Ancianos
  rule_ids:
  - elders--advisor
  combat_traits: {}
- id: greenjacks
  name: Greenjacks
  type: hero
  cost: 15
  experience: 0
  characteristics:
    M: 4
    WS: 2
    BS: 2
    S: 3
    T: 3
    W: 1
    I: 4
    A: 1
    Ld: 4
  equipment_lists:
  - the-lost-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - shooting
  - strength
  - speed
  source:
    manual: broheim.net
    printed_page: 4
    section: Heroes / 0-2 Greenjacks
    url: https://broheim.net/downloads/warbands/supplement/mousillon/The%20Lost.pdf
  source_path:
  - heroes
  - 0-2 Greenjacks
  name_i18n:
    es: Verdets
  rule_ids: []
  combat_traits: {}
- id: scavengers
  name: Scavengers
  type: henchman
  cost: 20
  experience: 0
  characteristics:
    M: 4
    WS: 2
    BS: 2
    S: 3
    T: 3
    W: 1
    I: 3
    A: 1
    Ld: 4
  equipment_lists:
  - the-lost-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: broheim.net
    printed_page: 4
    section: Henchmen / Scavengers
    url: https://broheim.net/downloads/warbands/supplement/mousillon/The%20Lost.pdf
  source_path:
  - henchmen
  - Scavengers
  name_i18n:
    es: Carroñeros
  rule_ids: []
  combat_traits: {}
- id: greycoats
  name: Greycoats
  type: henchman
  cost: 35
  experience: 0
  characteristics:
    M: 4
    WS: 3
    BS: 4
    S: 3
    T: 3
    W: 1
    I: 3
    A: 1
    Ld: 5
  equipment_lists:
  - greycoats-equipment-list
  fixed_equipment: []
  equipment_restrictions:
  - May not wear armour.
  skill_access: []
  source:
    manual: broheim.net
    printed_page: 5
    section: Henchmen / 0-2 Greycoats
    url: https://broheim.net/downloads/warbands/supplement/mousillon/The%20Lost.pdf
  source_path:
  - henchmen
  - 0-2 Greycoats
  name_i18n:
    es: Grises
  rule_ids:
  - greycoats--trap-masters
  combat_traits: {}
- id: mummers
  name: Mummers
  type: henchman
  cost: 35
  experience: 0
  characteristics:
    M: 4
    WS: 4
    BS: 2
    S: 4
    T: 3
    W: 1
    I: 3
    A: 1
    Ld: 5
  equipment_lists:
  - the-lost-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: broheim.net
    printed_page: 5
    section: Henchmen / Mummers
    url: https://broheim.net/downloads/warbands/supplement/mousillon/The%20Lost.pdf
  source_path:
  - henchmen
  - Mummers
  name_i18n:
    es: Mimos
  rule_ids:
  - mummers--brutes
  combat_traits: {}
