"""verification: Maps KB effects to their executable engine consumers."""
from __future__ import annotations



MODULAR_TAG_CONSUMERS = {
    'defence.holy-relic': 'leadership.resolve_local_leadership: the first required Leadership test automatically passes and spends the personal relic resource.',
    'mechanic.dueling-pride': 'contexts._hit_reroll: source-qualified first-combat-turn melee hit reroll.',
    'mechanic.first-failed-leadership-reroll': 'leadership.resolve_local_leadership: one persistent reroll resource for the first failed Leadership test.',
    'mechanic.flesh-peddler': 'compiler and contexts: supplied marked living opponent receives the source-qualified hit modifier.',
    'mechanic.guiding-dream': 'state.initialize_fighter and contexts: one battle-start dream result modifies attacks against the nominated opposing Hero.',
    'mechanic.kindred-hatred': 'contexts._hit_reroll: first-round bloodline-qualified Vampire Hatred, suppressed by active Frenzy.',
    'mechanic.marine-hunter': 'attacks.resolve_reference_attack: source-qualified injury reroll against the explicitly Aquatic opponent.',
    'mechanic.morrs-servant': 'psychology.causes_fear and resolve_fear: source-qualified Fear interaction against explicit Undead.',
    'mechanic.myrmidia-eagle-friend': 'compiler and rounds: each supplied eagle contributes a separate repeatable Strike First Strength 3 attack.',
    'mechanic.pikewall': 'contexts: first-round source-qualified melee defence.',
    'mechanic.shallya-strictures': 'state.initialize_fighter: prohibit attack contributions while retaining the source-qualified defender.',
    'mechanic.shallya-tranquil-aura': 'contexts: source-qualified incoming melee modifier while the aura bearer is active.',
    'mechanic.sigmar-enlightened': 'leadership.resolve_local_leadership: automatically pass against explicitly qualified Chaos/Orc/Goblin opponents.',
    'mechanic.sigmar-symbol-of-unity': 'contexts: apply the source-qualified melee hit modifier against explicit target identities.',
    'mechanic.snorri-drunk': 'compiler and contexts: supplied pre-battle drinking result determines characteristic, Frenzy and contact-stench effects.',
    'mechanic.taal-tranquil-fauna': 'rounds: inhibit attacks by explicitly qualified animals, using the supplied handler Leadership where required.',
    'mechanic.ulric-intense-rivals': 'contexts._hit_reroll: source-qualified Hatred against the explicitly supplied Ulric rival.',
    'skill.righteous-fury': 'contexts._hit_reroll: first-round Hatred against explicit source-qualified hostile species and nature.',

    "mechanic.norse-bulwark": "Source-bound Norse shield parry and axe/shield melee armour bonus.",
    "mechanic.norse-shieldmaster": "Source-bound Norse shield parry and axe/shield melee armour bonus.",
    "mechanic.unholy-stink": "Bog Hunter enemies suffer -1 melee hit regardless of their nature.",
    "mechanic.wheelo-skill-modifications": "Source-specific Wheelo fittings modify collision hits; Mighty Blow improves crew wound rolls only.",
    "mechanic.ghost-pirate-ethereal": "Ghost Pirate 4+ unmodifiable save; magical attacks and printed special metals bypass it.",
    "mechanic.righteous-charge": "rounds.resolve_round: the source-qualified active snapshot grants first-round charging mounted melee/Fear/Psychology benefits",
    "mechanic.wizened-halfling": "leadership.resolve_local_leadership: eligible same-band supplied leader gives a Leadership reroll within six inches",
    "mechanic.undivided-leader": "leadership.resolve_local_leadership: eligible same-band supplied leader gives a Leadership reroll within six inches",
    "mechanic.fear-human": "psychology.causes_fear: Nasty Reputation against explicitly Human opponents only",
    "mechanic.goblin-squabble": "rounds.resolve_round: own-turn D6=1 suppresses attacks until end of that turn",
    "mechanic.beauty-of-the-sea": "psychology and rounds: sex-qualified Fear and charge/combat Leadership until one successful test",
    "mechanic.wheelo-impact": "rounds.resolve_round: first-round charging D3 automatic S4 hits before weapon blows; psychology.resolve_fear: rolling charge remains engaged",
    "mechanic.noble-disdain": "contexts._hit_reroll: first-round Hatred against an explicitly ranged-armed opponent",
    "mechanic.hatred-orcs-goblins": "First-combat-turn reroll against explicit Orc/Goblin species",
    "mechanic.hatred-dwarfs": "First-combat-turn reroll against explicit opponent species",
    "mechanic.hatred-dwarfs-skaven": "First-combat-turn reroll against explicit opponent species",
    "mechanic.hatred-skaven-orcs-goblins": "First-combat-turn reroll against explicit opponent species",
    "mechanic.hatred-skaven": "First-combat-turn reroll against explicit opponent species",
    "mechanic.hatred-chaotic-warband": "First-combat-turn reroll against the declared opponent faction or nature",
    "mechanic.hatred-human-warband": "First-combat-turn reroll against the declared opponent faction or nature",
    "mechanic.fears-fire": "Individual Fear test against the duel opponent bearing active flames, including the printed immunity exception",
    "mechanic.andanti-knowledge": "Melee hit bonus against explicit Vampire only",
    "mechanic.hatred-undead": "First-combat-turn hit reroll against explicit Undead only",
    "mechanic.ethereal-hit-save": "Unmodifiable mundane hit save before wound resolution",
    "mechanic.centigor-drunken": "Own-turn temporary Stupidity or Frenzy and other Psychology immunity",
    "mechanic.foul-odour": "Source-qualified melee replacement, failed-wound knockdown or living-target odour/fire vulnerability",
    "mechanic.titanic-strength": "Source-qualified melee replacement, failed-wound knockdown or living-target odour/fire vulnerability",
    "mechanic.wraith-touch": "Source-qualified melee replacement, failed-wound knockdown or living-target odour/fire vulnerability",
    "mechanic.hypnotist": "Optional living target hypnosis, broken by the first attack attempt",
    "mechanic.mark-of-shornaal": "Three dice discard lowest, once passed, otherwise combat inhibition and automatic incoming hits",
    "mechanic.mesmerising-dance": "Individual charm test or immunity at combat-phase start",
    "mechanic.torturer": "source-qualified-opponent-effects",
    "mechanic.blessing-of-morr": "source-qualified-opponent-effects",
    "mechanic.animal-friendship": "source-qualified-opponent-effects",
    "mechanic.honorable": "opponent-condition-attack-denial",
    "dance.whirling-death": "learned-per-round-shadow-dance",
    "dance.storm-of-blades": "learned-per-round-shadow-dance",
    "dance.the-shadows-coil": "learned-per-round-shadow-dance",
    "dance.woven-mist": "learned-per-round-shadow-dance",

    "mechanic.bat-injury-chart": "source-specific-injury-threshold",
    "mechanic.fen-hard-to-kill": "fire-qualified-injury-chart",
    "mechanic.magical-void": "magic-qualified-special-save",
    "mechanic.hard-to-rattle": "fire-qualified-stun-reaction",
    "mechanic.questing-vow": "fear-opponent-qualified-leadership-reroll",
    "mechanic.rousing-sermon": "own-turn-once-only-attack-bonus",
    "mechanic.frantic": "priority",
    "mechanic.great-thirster": "out-of-action-frenzy",
    "mechanic.curse-of-the-revenant": "own-turn-wound-recovery",
    "rule.squishy": "injury-no-pain-exception",
    "mechanic.psychology-immunity": "individual-psychology-tests-and-benefits",
    "mechanic.fear-immunity": "individual-leadership-tests",
    "mechanic.fear-reroll": "individual-leadership-tests",
    "mechanic.leadership-reroll": "individual-leadership-tests",
    "mechanic.mandatory-leadership-reroll": "individual-leadership-tests",

    "mechanic.hatred-dark-elves": "hit",
    "mechanic.hatred-high-elves": "hit",
    "mechanic.handler-leadership": "individual-leadership-tests",
    "mechanic.brood-mentality": "individual-stupidity-tests",
    "mechanic.stupidity": "individual-stupidity-tests",
    "mechanic.craven": "fear-tests",
    "mechanic.cold-blooded-leadership": "local-leadership",
    "mechanic.cold-blooded-psychology": "local-leadership",
    "mechanic.causes-fear": "charge-leadership-hit",
    "mechanic.leader-six": "local-leadership",
    "mechanic.automatic-leadership": "local-leadership",
    "mechanic.seaguard-spear-master": "hit-resource-wound-armour",
    "mechanic.sabretusk-charge": "attacks",
    "skill.crude-belch-halfling": "leadership-attack-pool",
    "mechanic.ravening-onslaught": "attack-pool",
    "mechanic.wolf-rat-bite": "wound-armour",
    "mechanic.gypsy-ward": "special-save",
    **{tag: "construction" for tag in (
        "weapon.natural-attacks", "armour.no-armour", "armour.light-armour",
        "armour.heavy-armour", "armour.gromril-armour", "armour.ithilmar-armour",
        "armour.toughened-leathers", "armour.plate-armour", "armour.wizard-s-robe",
        "armour.ninja-robes", "armour.eshin-assassin-robes", "armour.spider-chitin-armour",
        "armour.cathayan-quilted-silk", "defence.helmet", "defence.sea-dragon-cloak",
        "defence.cooking-pot-helmet", "material.normal",
    )},
    "defence.lucky-charm": "hit-defence",
    "poison.black-lotus": "wound",
    "poison.wolfsbane": "critical",
    "poison.nightshade": "wound-reaction",
    "poison.spider-spittle": "wound-reaction",
    "skill.unarmed-fighting": "attacks-wound-armour",
    "skill.axe-expert": "hit",
    "skill.axe-master": "parry",
    "skill.bellowing-battle-roar": "hit",
    "skill.berserker": "hit",
    "skill.expert-swordsman": "hit",
    "skill.ferocious-charge": "attacks-hit",
    "skill.hardy-constitution": "critical",
    "skill.head-crusher": "injury",
    "skill.ignore-pain": "injury",
    "skill.infallible": "hit",
    "skill.inspiring-sermon": "attacks",
    "skill.jump-up": "injury",
    "skill.knife-fighting": "hit-injury",
    "skill.lightning-reflexes": "priority",
    "skill.luck": "hit-wound-armour-resource",
    "skill.mighty-biceps": "wound",
    "skill.miniath": "parry",
    "skill.monster-slayer": "wound",
    "skill.monster-slayer-effective-strength-armour": "armour",
    "skill.monstrous": "duel-start",
    "skill.shield-mastery": "parry",
    "skill.shield-strike": "attacks",
    "skill.shifty": "attacks-priority",
    "skill.sigmar-s-sign": "attacks",
    "skill.sweep": "attacks-hit",
    "skill.sword-master": "parry",
    "skill.tireless": "wound",
    "skill.unbeatable-warrior": "parry-resource",
    "skill.virtue-of-valour": "hit",
    "skill.wound-valour": "wound",
    "skill.cutthroat": "armour",
    "skill.weapons-of-the-north": "hit",
    "skill.web-of-steel": "injury",
    "skill.art-of-silent-death": "attacks-critical",
    "skill.unarmed-critical-strikes": "critical",
    "skill.crack-shot": "hit",
    "skill.duellist": "hit",
    "skill.hatred": "hit",
    "skill.swordmaster": "parry",
    "mechanic.body-slam": "attacks-hit-wound",
    "mechanic.bull-charge": "attacks-hit-reaction",
    "mechanic.force-of-will": "injury-aftermath-resource",
    "mechanic.unpredictable-attack": "attack-allocation",
    "mechanic.strike-first-vs-skinks-first-round": "priority",
    "mechanic.strike-first-vs-skinks-always": "priority",
    "mechanic.anvil-head": "hit-multiplication",
    "mechanic.disability": "duel-start",
    "mechanic.energy-focus": "attacks-wound",
    "mechanic.mark-of-the-old-ones": "hit-wound-armour-resource",
    "mechanic.netter": "duel-start-hit-reaction",
    "mechanic.spawn-special-attacks": "attacks",
    "mechanic.amazon-isolationists": "hit",
    "mechanic.spider-infested": "hit-parry-reaction",
    "mechanic.killing-blow": "hit-parry-wound",
    "mechanic.retain-flail-morning-star-strength-bonus": "wound",
}


MODULAR_FIELD_CONSUMERS = {
    "strength_bonus": "wound", "first_round_strength_bonus": "wound",
    "charge_strength_bonus": "wound", "toughness_bonus": "duel-start",
    "initiative_bonus": "priority", "fixed_strength": "wound",
    "armour_penetration": "armour", "target_armour_bonus": "armour",
    "hit_modifier": "hit", "wound_modifier": "wound", "injury_modifier": "injury",
    "attacks_bonus": "attacks", "charge_attacks_bonus": "attacks", "first_round_charge_attacks_bonus": "attacks",
    "charge_ws_bonus": "hit", "first_round_attacks_bonus": "attacks",
    "incoming_strength_modifier": "wound", "armour_strength_modifier": "armour",
    "weapon_skill_bonus": "hit", "critical_injury_bonus": "injury",
    "damage_die_sides": "wound",
    "energy_focus_attacks": "attacks-wound", "incoming_attacks_modifier": "attacks",
    "incoming_hit_modifier": "hit", "armour_save_bonus": "construction-armour",
    "ward_save": "special-save", "priority": "priority", "parry": "parry",
    "concussion": "injury", "two_handed": "attacks-priority", "paired": "attacks",
    "reroll_hits": "hit", "reroll_wounds": "wound", "strongman": "priority",
    "charge_reroll_hits": "hit", "step_aside": "special-save",
    "thick_skull": "injury", "ignore_armour": "armour",
    "automatic_hit": "hit", "cannot_be_parried": "parry", "bear_hug": "hit-wound",
    "poison_immunity": "wound", "frenzy": "attacks-injury", "damage": "injury",
    "regeneration_save": "special-save", "out_of_action_threshold": "injury",
    "maximum_wound_target": "wound", "armour_save_floor": "armour",
    "armour_cannot_be_ignored": "armour", "ward_save_mundane_only": "special-save",
    "natural_armour_negated_by_magic": "armour",
    "regeneration_blocked_by_fire": "special-save",
    "regeneration_blocked_by_blessed": "special-save",
    "ignition_threshold": "aftermath", "caught_fire_threshold": "aftermath",
}


MODULAR_COMPLEX_SCENARIOS = frozenset({
    "reference-bear-hug-replaces-two-hits-before-wound-resolution",
    "reference-force-of-will-rescues-once-and-sustains-per-round",
    "reference-luck-and-mark-are-persistent-consumable-resources",
    "reference-spines-acid-blood-and-contagious-are-real-reactions",
    "reference-black-hunger-resolves-d3-self-hits",
    "reference-netter-covers-miss-escape-and-capture",
    "reference-disability-is-applied-during-scalar-initialization",
    "reference-parry-and-critical-capacity-are-consumed-in-state",
    "reference-fire-persists-until-recovery-succeeds",
})
