schema_version: 2
band_id: dwarf-slayer-cult-web
profiles:
- id: giant-slayer
  name: Giant Slayer
  type: hero
  cost: 85
  experience: 20
  characteristics:
    M: 3
    WS: 5
    BS: 4
    S: 3
    T: 4
    W: 1
    I: 3
    A: 1
    Ld: 9
  equipment_lists:
  - slayer-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - shooting
  - academic
  - strength
  - special
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 1 Giant Slayer
    url: https://mordheimer.net/docs/warbands/grade-2a-warbands/dwarf-slayer-cult
  source_path:
  - heroes
  - 1 Giant Slayer
  name_i18n:
    es: Gran Matatrolles
  rule_ids:
  - giant-slayer--leader
  combat_traits: {}
- id: doomseeker
  name: Doomseeker
  type: hero
  cost: 55
  experience: 8
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - doomseeker-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - strength
  - special
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0-2 Doomseeker
    url: https://mordheimer.net/docs/warbands/grade-2a-warbands/dwarf-slayer-cult
  source_path:
  - heroes
  - 0-2 Doomseeker
  name_i18n:
    es: Buscador de la Perdición
  rule_ids: []
  combat_traits: {}
- id: rememberer
  name: Rememberer
  type: hero
  cost: 40
  experience: 0
  characteristics:
    M: 3
    WS: 3
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 8
  equipment_lists:
  - rememberer-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - shooting
  - academic
  - special
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0-1 Rememberer
    url: https://mordheimer.net/docs/warbands/grade-2a-warbands/dwarf-slayer-cult
  source_path:
  - heroes
  - 0-1 Rememberer
  name_i18n:
    es: Memoralista
  rule_ids:
  - rememberer--record-of-valor
  - rememberer--rememberer
  - rememberer--pick-up-the-slack
  - rememberer--not-a-slayer
  combat_traits: {}
- id: troll-slayers
  name: Troll Slayers
  type: henchman
  cost: 40
  experience: 0
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - slayer-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: mordheimer.net
    printed_page: 0
    section: Troll Slayers
    url: https://mordheimer.net/docs/warbands/grade-2a-warbands/dwarf-slayer-cult
  source_path:
  - henchmen
  - Troll Slayers
  name_i18n:
    es: Matatrolles
  rule_ids: []
  combat_traits: {}
- id: stubbles
  name: Stubbles
  type: henchman
  cost: 25
  experience: 0
  characteristics:
    M: 3
    WS: 3
    BS: 2
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 8
  equipment_lists:
  - slayer-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: mordheimer.net
    printed_page: 0
    section: Stubbles
    url: https://mordheimer.net/docs/warbands/grade-2a-warbands/dwarf-slayer-cult
  source_path:
  - henchmen
  - Stubbles
  name_i18n:
    es: Barbas Nacientes
  rule_ids:
  - stubbles--skittish
  combat_traits: {}
- id: axe-hurlers
  name: Axe Hurlers
  type: henchman
  cost: 40
  experience: 0
  characteristics:
    M: 3
    WS: 3
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - slayer-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0-5 Axe Hurlers
    url: https://mordheimer.net/docs/warbands/grade-2a-warbands/dwarf-slayer-cult
  source_path:
  - henchmen
  - 0-5 Axe Hurlers
  name_i18n:
    es: Lanzahachas
  rule_ids:
  - axe-hurlers--strong-arm
  - axe-hurlers--born-marksmen
  - axe-hurlers--skittish
  combat_traits: {}
