import { useState } from "react";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import { scenarioSpellOptions } from "@app/campaign/features/exploration/scenario-followups-workflow";
import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";

export function ScenarioFollowupsPanel({document,knowledge,locale="en"}:{readonly document:CampaignDocument;readonly knowledge:ArtefactKnowledgeReader;readonly locale?:"es"|"en"}) {
  const app=useCampaignApp(); const [heroes,setHeroes]=useState<Record<string,string>>({}); const [spells,setSpells]=useState<Record<string,readonly string[]>>({}); const post=document.campaign.post_battles.find((row)=>!row.complete); const followUps=(post?.pending_follow_ups??[]).filter((row)=>row["type"]==="scenario_spell_reward"||row["type"]==="scenario_encampment");
  if(!post||followUps.length===0)return null; const t=locale==="es"?{title:"Recompensas de escenario",tome:"Tomo de magia",hero:"Héroe",first:"Primer hechizo",second:"Segundo hechizo",choose:"Seleccionar…",learn:"Aprender hechizos",camp:"Campamento capturado",occupy:"Ocupar campamento",destroy:"Destruir campamento",hint:"El contenido reclamado se registra manualmente durante Equipo."}:{title:"Scenario rewards",tome:"Tome of Magic",hero:"Hero",first:"First spell",second:"Second spell",choose:"Select…",learn:"Learn spells",camp:"Captured camp",occupy:"Occupy camp",destroy:"Destroy camp",hint:"Record claimed contents manually during Equipment."};
  const availableHeroes=document.campaign.warriors.filter((row)=>row.kind==="hero");
  return <section aria-label="Scenario rewards"><h3>{t.title}</h3>{followUps.map((followUp)=>{const id=String(followUp["id"]); if(followUp["type"]==="scenario_encampment")return <article key={id}><h4>{t.camp}</h4><p>{t.hint}</p><button className="primary" onClick={()=>void app.runAction("resolveScenarioEncampment",{follow_up_id:id,choice:"occupy"})}>{t.occupy}</button><button onClick={()=>void app.runAction("resolveScenarioEncampment",{follow_up_id:id,choice:"destroy"})}>{t.destroy}</button></article>; const heroId=heroes[id]??availableHeroes[0]?.id??""; const options=scenarioSpellOptions(document,knowledge,heroId); const selected=spells[id]??["",""]; const change=(index:number,value:string)=>setSpells((current)=>({...current,[id]:selected.map((item,itemIndex)=>itemIndex===index?value:item)})); return <article key={id}><h4>{t.tome}</h4><label>{t.hero}<select value={heroId} onChange={(event)=>setHeroes((current)=>({...current,[id]:event.target.value}))}>{availableHeroes.map((hero)=><option key={hero.id} value={hero.id}>{hero.name}</option>)}</select></label><label>{t.first}<select value={selected[0]} onChange={(event)=>change(0,event.target.value)}><option value="">{t.choose}</option>{options.map((spell)=><option key={spell.id} value={spell.id}>{spell.name}</option>)}</select></label><label>{t.second}<select value={selected[1]} onChange={(event)=>change(1,event.target.value)}><option value="">{t.choose}</option>{options.map((spell)=><option key={spell.id} value={spell.id}>{spell.name}</option>)}</select></label><button className="primary" disabled={!heroId||selected.length!==2||!selected[0]||!selected[1]||selected[0]===selected[1]} onClick={()=>void app.runAction("resolveScenarioSpellReward",{follow_up_id:id,hero_id:heroId,spell_ids:selected})}>{t.learn}</button></article>;})}</section>;
}
