import { warriorPersonalName } from "../campaign/presentation-values";
import { presentationOutput } from "../campaign/presentation-output";
import { translate } from "../campaign/i18n-core";
import { useLocale } from "../campaign/i18n-context";
import { knowledgeName } from "../campaign/displayText";
import { useState } from "react";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import { scenarioSpellOptions } from "@app/campaign/features/exploration/scenario-followups-workflow";
import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";

export function ScenarioFollowupsPanel({document,knowledge,locale: requestedLocale}:{readonly document:CampaignDocument;readonly knowledge:ArtefactKnowledgeReader;readonly locale?:"es"|"en"}) {
  const locale = useLocale(requestedLocale);
  const app=useCampaignApp(); const [heroes,setHeroes]=useState<Record<string,string>>({}); const [spells,setSpells]=useState<Record<string,readonly string[]>>({}); const post=document.campaign.post_battles.find((row)=>!row.complete); const followUps=(post?.pending_follow_ups??[]).filter((row)=>row["type"]==="scenario_spell_reward"||row["type"]==="scenario_encampment");
  if(!post||followUps.length===0)return null; const t=({ title: translate({ key: "ui.bc1578a0df3e" }, locale), tome: translate({ key: "ui.4f03a6b2cbb5" }, locale), hero: translate({ key: "ui.34dc1a21c0f8" }, locale), first: translate({ key: "ui.1ed231462b7f" }, locale), second: translate({ key: "ui.ca98db2376ff" }, locale), choose: translate({ key: "ui.74dd6859713a" }, locale), learn: translate({ key: "ui.6c6dea4bf6a4" }, locale), camp: translate({ key: "ui.98c10c35716e" }, locale), occupy: translate({ key: "ui.62d4024bbfef" }, locale), destroy: translate({ key: "ui.ab63f2c6d4a5" }, locale), hint: translate({ key: "ui.1c027578eab6" }, locale) });
  const availableHeroes=document.campaign.warriors.filter((row)=>row.kind==="hero");
  return <section aria-label={presentationOutput(t.title)}><h3>{presentationOutput(t.title)}</h3>{followUps.map((followUp)=>{const id=String(followUp["id"]); if(followUp["type"]==="scenario_encampment")return <article key={id}><h4>{presentationOutput(t.camp)}</h4><p>{presentationOutput(t.hint)}</p><button className="primary" onClick={()=>void app.runAction("resolveScenarioEncampment",{follow_up_id:id,choice:"occupy"})}>{presentationOutput(t.occupy)}</button><button onClick={()=>void app.runAction("resolveScenarioEncampment",{follow_up_id:id,choice:"destroy"})}>{presentationOutput(t.destroy)}</button></article>; const heroId=heroes[id]??""; const options=[...scenarioSpellOptions(document,knowledge,heroId)].sort((a,b)=>a.name.localeCompare(b.name,locale)); const selected=spells[id]??["",""]; const change=(index:number,value:string)=>setSpells((current)=>({...current,[id]:selected.map((item,itemIndex)=>itemIndex===index?value:item)})); return <article key={id}><h4>{presentationOutput(t.tome)}</h4><label>{presentationOutput(t.hero)}<select value={heroId} onChange={(event)=>setHeroes((current)=>({...current,[id]:event.target.value}))}><option value="">{presentationOutput(t.choose)}</option>{[...availableHeroes].sort((a,b)=>a.name.localeCompare(b.name,locale)).map((hero)=><option key={hero.id} value={hero.id}>{presentationOutput(warriorPersonalName(hero, locale))}</option>)}</select></label><label>{presentationOutput(t.first)}<select value={selected[0]} onChange={(event)=>change(0,event.target.value)}><option value="">{presentationOutput(t.choose)}</option>{options.map((spell)=><option key={spell.id} value={spell.id}>{presentationOutput(knowledgeName(knowledge,"skill",spell.id,locale))}</option>)}</select></label><label>{presentationOutput(t.second)}<select value={selected[1]} onChange={(event)=>change(1,event.target.value)}><option value="">{presentationOutput(t.choose)}</option>{options.map((spell)=><option key={spell.id} value={spell.id}>{presentationOutput(knowledgeName(knowledge,"skill",spell.id,locale))}</option>)}</select></label><button className="primary" disabled={!heroId||selected.length!==2||!selected[0]||!selected[1]||selected[0]===selected[1]} data-disabled-reason={(!heroId ? (translate({ key: "disabled.84e46cf702" }, locale)) : !selected[0]||!selected[1] ? (translate({ key: "disabled.9dc5e9937e" }, locale)) : selected[0]===selected[1] ? (translate({ key: "disabled.e3b56ab8f2" }, locale)) : undefined) === undefined ? undefined : presentationOutput((!heroId ? (translate({ key: "disabled.84e46cf702" }, locale)) : !selected[0]||!selected[1] ? (translate({ key: "disabled.9dc5e9937e" }, locale)) : selected[0]===selected[1] ? (translate({ key: "disabled.e3b56ab8f2" }, locale)) : undefined)!)} onClick={()=>void app.runAction("resolveScenarioSpellReward",{follow_up_id:id,hero_id:heroId,spell_ids:selected})}>{presentationOutput(t.learn)}</button></article>;})}</section>;
}
