schema_version: 2
band_id: channel-rats-mim
profiles:
- id: domnu
  name: Domnu (Caravan Master)
  type: hero
  cost: 65
  experience: 20
  characteristics:
    M: 4
    WS: 4
    BS: 3
    S: 4
    T: 3
    W: 1
    I: 3
    A: 2
    Ld: 8
  equipment_lists:
  - strigany-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - shooting
  - strength
  - speed
  - special
  source:
    manual: broheim.net
    printed_page: 179
    section: Heroes / Domnu
    url: https://broheim.net/downloads/warbands/supplement/mutinyinmarienburg/Channel Rats.pdf
  source_path:
  - heroes
  - Domnu
  name_i18n:
    es: Domnu (Maestro de Caravana)
  rule_ids:
  - domnu--leader
  - domnu--prize-fighter
  - domnu--bear-hug
  combat_traits: {}
- id: petru
  name: Petru (Mystic)
  type: hero
  cost: 40
  experience: 8
  characteristics:
    M: 4
    WS: 2
    BS: 2
    S: 2
    T: 3
    W: 1
    I: 4
    A: 1
    Ld: 7
  equipment_lists:
  - petru-equipment-list
  fixed_equipment: []
  equipment_restrictions:
  - The Petru always carries a secret pouch of spell ingredients.
  skill_access:
  - academic
  - speed
  - special
  source:
    manual: broheim.net
    printed_page: 179
    section: Heroes / Petru
    url: https://broheim.net/downloads/warbands/supplement/mutinyinmarienburg/Channel Rats.pdf
  source_path:
  - heroes
  - Petru
  name_i18n:
    es: Petru (Místico)
  rule_ids:
  - petru--wizard
  - petru--necromancy
  - petru--potions
  combat_traits: {}
- id: tinker
  name: Tinker
  type: hero
  cost: 45
  experience: 12
  characteristics:
    M: 4
    WS: 2
    BS: 2
    S: 3
    T: 3
    W: 1
    I: 3
    A: 1
    Ld: 7
  equipment_lists:
  - strigany-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - shooting
  - academic
  - speed
  - special
  source:
    manual: broheim.net
    printed_page: 179
    section: Heroes / Tinker
    url: https://broheim.net/downloads/warbands/supplement/mutinyinmarienburg/Channel Rats.pdf
  source_path:
  - heroes
  - Tinker
  name_i18n:
    es: Calderero
  rule_ids:
  - tinker--grifter
  - tinker--rigger
  combat_traits: {}
- id: truants
  name: Truants
  type: hero
  cost: 25
  experience: 0
  characteristics:
    M: 4
    WS: 2
    BS: 2
    S: 3
    T: 3
    W: 1
    I: 3
    A: 1
    Ld: 6
  equipment_lists:
  - strigany-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - strength
  - speed
  - special
  source:
    manual: broheim.net
    printed_page: 180
    section: Heroes / Truants
    url: https://broheim.net/downloads/warbands/supplement/mutinyinmarienburg/Channel Rats.pdf
  source_path:
  - heroes
  - Truants
  name_i18n:
    es: Cimarrones
  rule_ids:
  - truants--spry
  - truants--taunt
  combat_traits: {}
- id: gypsies
  name: Gypsies
  type: henchman
  cost: 25
  experience: 0
  characteristics:
    M: 4
    WS: 3
    BS: 3
    S: 3
    T: 3
    W: 1
    I: 3
    A: 1
    Ld: 7
  equipment_lists:
  - strigany-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: broheim.net
    printed_page: 181
    section: Henchmen / Gypsies
    url: https://broheim.net/downloads/warbands/supplement/mutinyinmarienburg/Channel Rats.pdf
  source_path:
  - henchmen
  - Gypsies
  name_i18n:
    es: Gitanos
  rule_ids: []
  combat_traits: {}
- id: dead-eyes
  name: Dead-Eyes
  type: henchman
  cost: 50
  experience: 0
  characteristics:
    M: 4
    WS: 3
    BS: 4
    S: 3
    T: 3
    W: 1
    I: 3
    A: 1
    Ld: 7
  equipment_lists:
  - strigany-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: broheim.net
    printed_page: 181
    section: Henchmen / Dead-eyes
    url: https://broheim.net/downloads/warbands/supplement/mutinyinmarienburg/Channel Rats.pdf
  source_path:
  - henchmen
  - Dead-eyes
  name_i18n:
    es: Ojos Muertos
  rule_ids:
  - dead-eyes--dead-eye-shot
  - dead-eyes--target-practice
  - dead-eyes--weapons-expert
  combat_traits: {}
- id: fugitives
  name: Fugitives
  type: henchman
  cost: 40
  experience: 0
  characteristics:
    M: 4
    WS: 4
    BS: 3
    S: 3
    T: 3
    W: 1
    I: 4
    A: 1
    Ld: 7
  equipment_lists:
  - strigany-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: broheim.net
    printed_page: 181
    section: Henchmen / Fugitives
    url: https://broheim.net/downloads/warbands/supplement/mutinyinmarienburg/Channel Rats.pdf
  source_path:
  - henchmen
  - Fugitives
  name_i18n:
    es: Fugitivos
  rule_ids:
  - fugitives--charismatic
  combat_traits: {}
- id: vagabonds
  name: Vagabonds
  type: henchman
  cost: 15
  experience: 0
  characteristics:
    M: 4
    WS: 2
    BS: 2
    S: 3
    T: 3
    W: 1
    I: 3
    A: 1
    Ld: 6
  equipment_lists:
  - strigany-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: broheim.net
    printed_page: 181
    section: Henchmen / Vagabonds
    url: https://broheim.net/downloads/warbands/supplement/mutinyinmarienburg/Channel Rats.pdf
  source_path:
  - henchmen
  - Vagabonds
  name_i18n:
    es: Vagabundos
  rule_ids: []
  combat_traits: {}
