/**
 * P3.2: the v5 contract schema (contracts/campaign-file-v5/
 * campaign-file-v5.schema.json), embedded verbatim so the TypeScript
 * adapter validates against the same source of truth as the Python
 * reader without a runtime dependency or a build step.
 *
 * Generated by tools/embed_v4_schema.py-style embedding; regenerate with
 * `python tools/embed_v4_schema.py` if the contract changes. Do not edit
 * by hand.
 */

export const SCHEMA_JSON: unknown = {
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "$id": "https://mordheim-utils.invalid/contracts/campaign-file-v5/campaign-file-v5.schema.json",
 "title": "Mordheim campaign file (format v5)",
 "description": "Neutral representation of a Warband Manager / Campaign Manager campaign. Self-contained JSON: marker, version, UTC timestamp. The campaign section holds external campaign state; the view section holds reconstructible UI selection state. The Knowledge Base is never serialised: every catalogue reference travels as a stable KB id (band_id, profile_id, item_id) that the loading application resolves against its own KB.",
 "type": "object",
 "required": [
  "marker",
  "format_version",
  "saved_at",
  "campaign"
 ],
 "additionalProperties": false,
 "properties": {
  "marker": {
   "const": "MORDHEIM_CAMPAIGN_MANAGER",
   "description": "Document type marker. Files without it are rejected before version checks."
  },
  "format_version": {
   "const": 5,
   "description": "Exactly 5. Versions 1-4 are explicitly retired and rejected without automatic migration."
  },
  "saved_at": {
   "$ref": "#/$defs/timestamp",
   "description": "UTC ISO-8601 save timestamp. Volatile by design: two saves of an unchanged campaign differ only in this field."
  },
  "campaign": {
   "$ref": "#/$defs/campaign"
  },
  "view": {
   "$ref": "#/$defs/view"
  }
 },
 "$defs": {
  "timestamp": {
   "type": "string",
   "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})$"
  },
  "nonnegative_int": {
   "type": "integer",
   "minimum": 0
  },
  "id_string": {
   "description": "Non-empty identifier string (stable KB ids and document-local ids).",
   "type": "string",
   "minLength": 1
  },
  "display_text": {
   "description": "Human-readable text captured from a specific locale. Volatile presentation data, not a KB reference.",
   "type": "string"
  },
  "open_object": {
   "description": "Unconstrained payload (preserve-in-place policy for KB-derived or application-defined data).",
   "type": "object"
  },
  "int_map": {
   "description": "Map of key to signed integer (stat modifiers, per-warrior awards, ...).",
   "type": "object",
   "additionalProperties": {
    "type": "integer"
   }
  },
  "campaign": {
   "type": "object",
   "description": "The campaign state. Array order is document order and is meaningful (states and battles are ordered by number).",
   "required": [
    "identity",
    "configuration",
    "resources",
    "warriors",
    "battles",
    "states",
    "post_battles",
    "inventory",
    "special_rules",
    "manual_log"
   ],
   "additionalProperties": false,
   "properties": {
    "identity": {
     "$ref": "#/$defs/identity"
    },
    "configuration": {
     "$ref": "#/$defs/draft_configuration"
    },
    "resources": {
     "$ref": "#/$defs/resources"
    },
    "current_state_number": {
     "description": "Newest committed timeline state number; 0 for a draft or a campaign without committed states.",
     "$ref": "#/$defs/nonnegative_int"
    },
    "warriors": {
     "type": "array",
     "items": {
      "$ref": "#/$defs/warrior"
     }
    },
    "battles": {
     "type": "array",
     "items": {
      "$ref": "#/$defs/battle"
     }
    },
    "states": {
     "type": "array",
     "items": {
      "$ref": "#/$defs/state"
     }
    },
    "post_battles": {
     "type": "array",
     "items": {
      "$ref": "#/$defs/post_battle"
     }
    },
    "inventory": {
     "type": "array",
     "items": {
      "$ref": "#/$defs/inventory_item"
     }
    },
    "special_rules": {
     "type": "array",
     "description": "Campaign-level special rules in effect (exploration grants, encounters). Free-form payloads with source/text/expiry conventions.",
     "items": {
      "$ref": "#/$defs/open_object"
     }
    },
    "unique_reward_ids": {
     "type": "array",
     "description": "Unique rewards already generated in this campaign; independent from current ownership.",
     "items": {
      "$ref": "#/$defs/id_string"
     }
    },
    "manual_log": {
     "type": "array",
     "description": "User-authored corrections made outside normal campaign resolution.",
     "items": {
      "$ref": "#/$defs/open_object"
     }
    }
   }
  },
  "identity": {
   "type": "object",
   "description": "Who the campaign is. Names are volatile display text; collection/band_id/ruleset are the stable KB identity.",
   "required": [
    "campaign_name",
    "warband_name",
    "warband_type",
    "band_id"
   ],
   "additionalProperties": false,
   "properties": {
    "campaign_name": {
     "$ref": "#/$defs/id_string"
    },
    "warband_name": {
     "type": "string"
    },
    "warband_type": {
     "type": "string"
    },
    "started": {
     "type": "string"
    },
    "collection": {
     "type": "string"
    },
    "band_id": {
     "$ref": "#/$defs/id_string"
    },
    "ruleset": {
     "type": "string"
    },
    "mercenary_variant": {
     "description": "Legacy field name used for the selected warband-family variant; null for bands without variants or for legacy drafts awaiting selection.",
     "type": [
      "string",
      "null"
     ]
    }
   }
  },
  "draft_configuration": {
   "type": "object",
   "description": "Campaign configuration, including draft-phase construction limits. Writers emit the draft limits when is_draft is true; readers must not rely on them otherwise.",
   "required": [
    "is_draft"
   ],
   "additionalProperties": false,
   "properties": {
    "is_draft": {
     "type": "boolean"
    },
    "starting_gold": {
     "$ref": "#/$defs/nonnegative_int",
     "default": 500
    },
    "minimum_models": {
     "$ref": "#/$defs/nonnegative_int",
     "default": 3
    },
    "maximum_models": {
     "$ref": "#/$defs/nonnegative_int",
     "default": 15
    },
    "hero_limit": {
     "$ref": "#/$defs/nonnegative_int",
     "default": 5
    },
    "required_profiles": {
     "description": "Draft-time minimum member counts per required KB profile id.",
     "type": "object",
     "additionalProperties": {
      "$ref": "#/$defs/nonnegative_int"
     }
    }
   }
  },
  "resources": {
   "type": "object",
   "description": "Warband-level numeric resources. Wyrdstone shards live on the timeline states; these pools are campaign-level counters.",
   "required": [
    "stash_value",
    "rare_finds",
    "treasures",
    "campaign_points"
   ],
   "additionalProperties": false,
   "properties": {
    "stash_value": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "rare_finds": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "treasures": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "campaign_points": {
     "$ref": "#/$defs/nonnegative_int"
    }
   }
  },
  "warrior": {
   "type": "object",
   "description": "One roster row (a hero, or a henchman group with quantity > 1).",
   "required": [
    "id",
    "name",
    "profile_name",
    "kind",
    "stats",
    "equipment",
    "skills",
    "experience"
   ],
   "additionalProperties": false,
   "properties": {
    "id": {
     "$ref": "#/$defs/id_string"
    },
    "name": {
     "$ref": "#/$defs/display_text"
    },
    "profile_name": {
     "$ref": "#/$defs/display_text"
    },
    "kind": {
     "type": "string",
     "enum": [
      "hero",
      "henchman",
      "hireling"
     ]
    },
    "stats": {
     "description": "Current characteristics by display key (M, WS, BS, S, T, W, I, A, Ld).",
     "$ref": "#/$defs/int_map"
    },
    "equipment": {
     "type": "array",
     "items": {
      "$ref": "#/$defs/equipment_entry"
     }
    },
    "skills": {
     "description": "Inherent rules plus skills gained in play.",
     "type": "array",
     "items": {
      "type": "string"
     }
    },
    "experience": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "previous_experience": {
     "type": [
      "integer",
      "null"
     ]
    },
    "advance_experience": {
     "description": "Experience baseline for the pending advance row; null when absent (legacy files).",
     "type": [
      "integer",
      "null"
     ]
    },
    "quantity": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "condition": {
     "type": [
      "string",
      "null"
     ]
    },
    "condition_detail": {
     "type": [
      "string",
      "null"
     ]
    },
    "cost": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "stat_modifiers": {
     "description": "Lasting characteristic injuries.",
     "$ref": "#/$defs/int_map"
    },
    "skill_access": {
     "type": "array",
     "items": {
      "type": "string"
     }
    },
    "stat_advances": {
     "description": "Characteristic points gained from advance rolls (distinct from injury stat_modifiers).",
     "$ref": "#/$defs/int_map"
    },
    "profile_id": {
     "type": "string"
    },
    "spell_difficulty_modifiers": {
     "$ref": "#/$defs/int_map"
    },
    "equipment_limits": {
     "description": "Remaining equip capacity by KB category key (post-battle equipment step).",
     "$ref": "#/$defs/int_map"
    },
    "hireling_rating": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "maximum_models_modifier": {
     "type": "integer"
    },
    "upkeep_resources": {
     "description": "Per-resource upkeep fees of this row: array of [resource_id, amount] pairs (JSON has no tuples).",
     "type": "array",
     "items": {
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "prefixItems": [
       {
        "type": "string"
       },
       {
        "type": "integer"
       }
      ],
      "items": false
     }
    },
    "games_to_miss": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "absence_reason": {
     "type": "string"
    },
    "hatreds": {
     "type": "array",
     "items": {
      "type": "string"
     }
    },
    "battle_start_checks": {
     "type": "array",
     "items": {
      "$ref": "#/$defs/open_object"
     }
    },
    "injury_records": {
     "type": "array",
     "items": {
      "$ref": "#/$defs/open_object"
     }
    },
    "lost_eyes": {
     "type": "array",
     "items": {
      "type": "string"
     }
    },
    "special_rules": {
     "type": "array",
     "items": {
      "type": "string"
     }
    }
   }
  },
  "equipment_entry": {
   "type": "object",
   "description": "One equipment line of a warrior row. item_id is the stable KB identity; name is captured display text.",
   "required": [
    "item_id",
    "name"
   ],
   "additionalProperties": false,
   "properties": {
    "item_id": {
     "$ref": "#/$defs/id_string"
    },
    "name": {
     "$ref": "#/$defs/display_text"
    },
    "quantity": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "acquisition": {
     "type": "string"
    },
    "unit_cost": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "per_model": {
     "type": "boolean"
    },
    "transferable": {
     "type": "boolean"
    },
    "special_rules": {
     "type": "array",
     "items": {
      "type": "string"
     }
    },
    "base_item_id": {
     "type": "string"
    },
    "acquisition_costs": {
     "description": "Per-copy acquisition costs (oldest first); empty when absent.",
     "type": "array",
     "items": {
      "$ref": "#/$defs/nonnegative_int"
     }
    }
   }
  },
  "battle": {
   "type": "object",
   "description": "One recorded battle. Facts are frozen at creation; post-battle resolution references the battle by number.",
   "required": [
    "number",
    "date",
    "scenario",
    "opponent",
    "result",
    "gold_delta",
    "wyrdstone",
    "xp_delta",
    "casualties",
    "advances",
    "rating_before",
    "rating_after",
    "models_before",
    "models_after"
   ],
   "additionalProperties": false,
   "properties": {
    "number": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "date": {
     "type": "string"
    },
    "scenario": {
     "type": "string"
    },
    "opponent": {
     "type": "string"
    },
    "opponent_band_id": {
     "type": "string"
    },
    "result": {
     "type": "string"
    },
    "gold_delta": {
     "type": "integer"
    },
    "wyrdstone": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "xp_delta": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "casualties": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "advances": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "rating_before": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "rating_after": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "models_before": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "models_after": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "notes": {
     "type": "string"
    },
    "opponent_rating": {
     "type": [
      "integer",
      "null"
     ]
    },
    "out_of_action_ids": {
     "description": "Warrior ids Out of Action at battle end; null = not recorded (legacy). Recovery resolves their injury rolls.",
     "type": [
      "array",
      "null"
     ],
     "items": {
      "$ref": "#/$defs/id_string"
     }
    },
    "participants": {
     "description": "Roster snapshot at battle time, so historical reviews do not depend on the live roster.",
     "type": "array",
     "items": {
      "$ref": "#/$defs/open_object"
     }
    },
    "per_group_casualties": {
     "$ref": "#/$defs/int_map"
    },
    "xp_awards": {
     "description": "Per-warrior XP award (warrior_id -> XP). Empty = uniform xp_delta for every survivor.",
     "$ref": "#/$defs/int_map"
    },
    "scenario_results": {
     "description": "Answers for the structured scenario result fields (award/question id -> value).",
     "type": "object"
    },
    "absentees": {
     "description": "Roster members unavailable for this battle, snapshotted before their absence counter was decremented.",
     "type": "array",
     "items": {
      "$ref": "#/$defs/open_object"
     }
    }
   }
  },
  "state": {
   "type": "object",
   "description": "One immutable timeline state with its aggregate counters and full roster/inventory snapshot.",
   "required": [
    "number",
    "date",
    "gold",
    "wyrdstone",
    "rating",
    "models",
    "max_models",
    "heroes",
    "henchmen",
    "experience"
   ],
   "additionalProperties": false,
   "properties": {
    "number": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "date": {
     "type": "string"
    },
    "gold": {
     "type": "integer"
    },
    "wyrdstone": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "rating": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "models": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "max_models": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "heroes": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "henchmen": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "experience": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "label": {
     "type": "string"
    },
    "roster": {
     "type": "array",
     "items": {
      "$ref": "#/$defs/warrior"
     }
    },
    "inventory": {
     "type": "array",
     "items": {
      "$ref": "#/$defs/inventory_item"
     }
    }
   }
  },
  "post_battle": {
   "type": "object",
   "description": "Post-battle sequence of one battle: complete history or resumable pending work. Numeric deltas are owned here; roster/inventory mutations are already applied to the campaign.",
   "required": [
    "battle_number",
    "complete",
    "active_step",
    "completed_steps",
    "review_open"
   ],
   "additionalProperties": false,
   "properties": {
    "battle_number": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "complete": {
     "type": "boolean"
    },
    "active_step": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "completed_steps": {
     "type": "array",
     "description": "Sorted step indices (JSON has no sets).",
     "items": {
      "$ref": "#/$defs/nonnegative_int"
     }
    },
    "review_open": {
     "type": "boolean"
    },
    "gold_delta": {
     "type": "integer"
    },
    "wyrdstone_delta": {
     "type": "integer"
    },
    "wyrdstone_sold": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "sale_resolved": {
     "type": "boolean"
    },
    "veteran_pool": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "experience_applied": {
     "type": "boolean"
    },
    "pending_advances": {
     "description": "Advance rolls of this sequence, one row per warrior that crossed a threshold (roll_total/subroll, committed, table).",
     "type": "array",
     "items": {
      "$ref": "#/$defs/open_object"
     }
    },
    "step_state": {
     "description": "Step-local working data keyed by step index (unresolved dice, sale quantity, sub-roll choices).",
     "type": "object"
    },
    "searches": {
     "description": "Search assignments and results keyed by hero id.",
     "type": "object"
    },
    "acknowledgements": {
     "description": "Explicit acknowledgement that an effect was resolved outside the application, keyed by step.",
     "type": "object"
    },
    "event_log": {
     "description": "Structured log of every applied mutation ({step, action, ids, message}).",
     "type": "array",
     "items": {
      "$ref": "#/$defs/open_object"
     }
    },
    "equipment_obligations": {
     "description": "Per-group equipment obligations created by recruitment [{warrior_id, item_id, quantity}].",
     "type": "array",
     "items": {
      "$ref": "#/$defs/open_object"
     }
    },
    "pending_follow_ups": {
     "description": "Follow-up actions awaiting resolution or acknowledgement ({id, step, type, description, ...}).",
     "type": "array",
     "items": {
      "$ref": "#/$defs/open_object"
     }
    }
   }
  },
  "inventory_item": {
   "type": "object",
   "description": "One warband inventory line: owned split into equipped and stash. id is the stable KB item id.",
   "required": [
    "id",
    "name",
    "category",
    "owned",
    "equipped",
    "stash"
   ],
   "additionalProperties": false,
   "properties": {
    "id": {
     "$ref": "#/$defs/id_string"
    },
    "name": {
     "$ref": "#/$defs/display_text"
    },
    "category": {
     "type": "string"
    },
    "owned": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "equipped": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "stash": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "value": {
     "$ref": "#/$defs/nonnegative_int"
    },
    "rarity": {
     "type": [
      "string",
      "null"
     ]
    },
    "special_rules": {
     "type": "array",
     "items": {
      "type": "string"
     }
    },
    "base_item_id": {
     "type": "string"
    },
    "acquisition_costs": {
     "description": "Per-copy acquisition costs (oldest first); empty when absent.",
     "type": "array",
     "items": {
      "$ref": "#/$defs/nonnegative_int"
     }
    }
   }
  },
  "view": {
   "type": "object",
   "description": "Reconstructible UI selection state. A reader may ignore or reset any part of it; a document without a view section is valid.",
   "additionalProperties": false,
   "properties": {
    "active_view": {
     "type": "string"
    },
    "campaign_mode": {
     "type": "string"
    },
    "selected_moment": {
     "description": "Timeline node selection: draft:0 | state:N | battle:N | post:N.",
     "type": "string"
    },
    "state_section": {
     "type": "string"
    },
    "battle_section": {
     "type": "string"
    },
    "inventory_mode": {
     "type": "string"
    },
    "draft_warrior_tab": {
     "type": "string"
    },
    "pending_battle_draft": {
     "description": "Partially entered record-battle draft; cleared when the battle is recorded or cancelled.",
     "type": "object"
    }
   }
  }
 }
};
