"""verification.consumers: responsabilidad extraída sin alterar las reglas."""
from __future__ import annotations



MODULAR_TAG_CONSUMERS = {
    **{tag: "construction" for tag in (
        "weapon.natural-attacks", "armour.no-armour", "armour.light-armour",
        "armour.heavy-armour", "armour.gromril-armour", "armour.ithilmar-armour",
        "armour.toughened-leathers", "armour.plate-armour", "armour.wizard-s-robe",
        "armour.ninja-robes", "armour.eshin-assassin-robes", "armour.spider-chitin-armour",
        "armour.cathayan-quilted-silk", "defence.helmet", "defence.sea-dragon-cloak",
        "defence.cooking-pot-helmet", "material.normal",
    )},
    "defence.lucky-charm": "hit-defence",
    "poison.black-lotus": "wound",
    "poison.wolfsbane": "critical",
    "poison.nightshade": "wound-reaction",
    "poison.spider-spittle": "wound-reaction",
    "skill.unarmed-fighting": "attacks-wound-armour",
    "skill.axe-expert": "hit",
    "skill.axe-master": "parry",
    "skill.bellowing-battle-roar": "hit",
    "skill.berserker": "hit",
    "skill.expert-swordsman": "hit",
    "skill.ferocious-charge": "attacks-hit",
    "skill.hardy-constitution": "critical",
    "skill.head-crusher": "injury",
    "skill.ignore-pain": "injury",
    "skill.infallible": "hit",
    "skill.inspiring-sermon": "attacks",
    "skill.jump-up": "injury",
    "skill.knife-fighting": "hit-injury",
    "skill.lightning-reflexes": "priority",
    "skill.luck": "hit-resource",
    "skill.mighty-biceps": "wound",
    "skill.miniath": "parry",
    "skill.monster-slayer": "wound",
    "skill.monster-slayer-effective-strength-armour": "armour",
    "skill.monstrous": "duel-start",
    "skill.shield-mastery": "parry",
    "skill.shield-strike": "attacks",
    "skill.sigmar-s-sign": "attacks",
    "skill.sweep": "attacks-hit",
    "skill.sword-master": "parry",
    "skill.tireless": "wound",
    "skill.unbeatable-warrior": "parry-resource",
    "skill.virtue-of-valour": "hit",
    "skill.weapons-of-the-north": "hit",
    "skill.web-of-steel": "injury",
    "skill.art-of-silent-death": "attacks-critical",
    "skill.unarmed-critical-strikes": "critical",
    "skill.crack-shot": "hit",
    "skill.duellist": "hit",
    "skill.hatred": "hit",
    "skill.swordmaster": "parry",
    "mechanic.body-slam": "attacks-hit-wound",
    "mechanic.bull-charge": "attacks-hit-reaction",
    "mechanic.force-of-will": "injury-aftermath-resource",
    "mechanic.unpredictable-attack": "attack-allocation",
    "mechanic.strike-first-vs-skinks-first-round": "priority",
    "mechanic.strike-first-vs-skinks-always": "priority",
    "mechanic.anvil-head": "hit-multiplication",
    "mechanic.disability": "duel-start",
    "mechanic.energy-focus": "attacks-wound",
    "mechanic.mark-of-the-old-ones": "hit-wound-resource",
    "mechanic.netter": "duel-start-hit-reaction",
    "mechanic.spawn-special-attacks": "attacks",
    "mechanic.amazon-isolationists": "hit",
    "mechanic.spider-infested": "hit-parry-reaction",
    "mechanic.retain-flail-morning-star-strength-bonus": "wound",
}


MODULAR_FIELD_CONSUMERS = {
    "strength_bonus": "wound", "first_round_strength_bonus": "wound",
    "charge_strength_bonus": "wound", "toughness_bonus": "duel-start",
    "initiative_bonus": "priority", "fixed_strength": "wound",
    "armour_penetration": "armour", "target_armour_bonus": "armour",
    "hit_modifier": "hit", "wound_modifier": "wound", "injury_modifier": "injury",
    "attacks_bonus": "attacks", "charge_attacks_bonus": "attacks", "first_round_charge_attacks_bonus": "attacks",
    "charge_ws_bonus": "hit", "first_round_attacks_bonus": "attacks",
    "incoming_strength_modifier": "wound", "armour_strength_modifier": "armour",
    "weapon_skill_bonus": "hit", "critical_injury_bonus": "injury",
    "energy_focus_attacks": "attacks-wound", "incoming_attacks_modifier": "attacks",
    "incoming_hit_modifier": "hit", "armour_save_bonus": "construction-armour",
    "ward_save": "special-save", "priority": "priority", "parry": "parry",
    "concussion": "injury", "two_handed": "attacks-priority", "paired": "attacks",
    "reroll_hits": "hit", "reroll_wounds": "wound", "strongman": "priority",
    "charge_reroll_hits": "hit", "step_aside": "special-save",
    "thick_skull": "injury", "ignore_armour": "armour",
    "automatic_hit": "hit", "cannot_be_parried": "parry", "bear_hug": "hit-wound",
    "poison_immunity": "wound", "frenzy": "attacks-injury", "damage": "injury",
    "regeneration_save": "special-save", "out_of_action_threshold": "injury",
    "maximum_wound_target": "wound", "armour_save_floor": "armour",
    "armour_cannot_be_ignored": "armour", "ward_save_mundane_only": "special-save",
    "natural_armour_negated_by_magic": "armour",
    "regeneration_blocked_by_fire": "special-save",
    "regeneration_blocked_by_blessed": "special-save",
    "ignition_threshold": "aftermath", "caught_fire_threshold": "aftermath",
}


MODULAR_COMPLEX_SCENARIOS = frozenset({
    "reference-bear-hug-replaces-two-hits-before-wound-resolution",
    "reference-force-of-will-rescues-once-and-sustains-per-round",
    "reference-luck-and-mark-are-persistent-consumable-resources",
    "reference-spines-acid-blood-and-contagious-are-real-reactions",
    "reference-black-hunger-resolves-d3-self-hits",
    "reference-netter-covers-miss-escape-and-capture",
    "reference-disability-is-applied-during-scalar-initialization",
    "reference-parry-and-critical-capacity-are-consumed-in-state",
    "reference-fire-persists-until-recovery-succeeds",
})
