// Generated by tools/web/build-eligibility.mjs. Do not edit.
// Source SHA256: 0821e8bf76e2f4f9776e724d7babadc201e52d1f742374b46b59f7106e90a4cb
"use strict";
var MordheimEligibility = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // packages/typescript/domain/eligibility/bridge.ts
  var bridge_exports = {};
  __export(bridge_exports, {
    BLACKPOWDER_WEAPONS: () => BLACKPOWDER_WEAPONS,
    DRUG_PREPARATIONS: () => DRUG_PREPARATIONS,
    EQUIPMENT_MECHANIC_PREFIXES: () => EQUIPMENT_MECHANIC_PREFIXES,
    EQUIPMENT_TAG_VOCABULARY: () => EQUIPMENT_TAG_VOCABULARY,
    INFORMATIONAL_ISSUE_CODES: () => INFORMATIONAL_ISSUE_CODES,
    MISSILE_WEAPONS: () => MISSILE_WEAPONS,
    NATURAL_ATTACK_ID: () => NATURAL_ATTACK_ID,
    NEUTRAL_ITEM_IDS: () => NEUTRAL_ITEM_IDS,
    additionalEquipmentRestriction: () => additionalEquipmentRestriction,
    applicableProfileRules: () => applicableProfileRules,
    applicableRules: () => applicableRules,
    bandEquipmentForbids: () => bandEquipmentForbids,
    bandEquipmentLimits: () => bandEquipmentLimits,
    bandFacts: () => bandFacts,
    bannedSkillCategories: () => bannedSkillCategories,
    buildAccess: () => buildAccess,
    buildRestriction: () => buildRestriction,
    carriedItemFacts: () => carriedItemFacts,
    catalogueEquipment: () => catalogueEquipment,
    catalogueItemFacts: () => catalogueItemFacts,
    catalogueSkillChoices: () => catalogueSkillChoices,
    configuredProfile: () => configuredProfile,
    constructionCall: () => constructionCall,
    desktopCall: () => desktopCall,
    entryReachesProfile: () => entryReachesProfile,
    equipmentIssue: () => equipmentIssue,
    equipmentSetIssues: () => equipmentSetIssues,
    installCatalogue: () => installCatalogue,
    isEquipmentMechanic: () => isEquipmentMechanic,
    issueIsInformational: () => issueIsInformational,
    loadoutRestriction: () => loadoutRestriction,
    poisonApplicationIssue: () => poisonApplicationIssue,
    profileBindings: () => profileBindings2,
    profileEquipment: () => profileEquipment,
    profileFacts: () => profileFacts,
    profileFactsProjection: () => profileFactsProjection,
    profileSkillLists: () => profileSkillLists2,
    resolveHirelingKit: () => resolveHirelingKit,
    selectableRuleOptions: () => selectableRuleOptions,
    selectedRuleBindings: () => selectedRuleBindings2,
    selectedRuleCandidates: () => selectedRuleCandidates,
    selectionDecisions: () => selectionDecisions,
    skillCategoryAllowed: () => skillCategoryAllowed,
    skillIssue: () => skillIssue,
    specialRuleOptions: () => specialRuleOptions,
    specialRuleRestriction: () => specialRuleRestriction,
    tokenForbids: () => tokenForbids,
    tokenPermits: () => tokenPermits,
    validateConstruction: () => validateConstruction,
    warriorEquipmentRestriction: () => warriorEquipmentRestriction
  });

  // packages/typescript/domain/eligibility/index.ts
  var INFORMATIONAL_ISSUE_CODES = [
    "equipment_unknown_item",
    "skill_pending_special_list",
    "construction_clause_unstructured"
  ];
  function issueIsInformational(code) {
    return INFORMATIONAL_ISSUE_CODES.includes(code);
  }
  var EQUIPMENT_TAG_VOCABULARY = [
    "animal",
    "blackpowder",
    "bow",
    "crossbow",
    "poison",
    "thrown",
    "constant-save-cloak"
  ];
  var HEAVY_ARMOUR = ["armour.heavy-armour", "armour.gromril-armour", "armour.ithilmar-armour", "armour.plate-armour"];
  var WEAPON_KINDS = ["close-combat-weapon", "ranged-weapon"];
  var INTERPRETED_TOKENS = [
    "armour",
    "armour-suit",
    "heavy-armour",
    "ranged-weapons",
    "weapons",
    "two-handed-weapons",
    "equipment",
    "non-thrown-ranged",
    ...EQUIPMENT_TAG_VOCABULARY
  ];
  var NATURAL_ATTACK_ID = "weapon.natural-attacks";
  function tokenForbids(token, itemId, item) {
    if (token === itemId || token === item?.mechanic_id) return true;
    if (itemId === NATURAL_ATTACK_ID || item?.mechanic_id === NATURAL_ATTACK_ID) return false;
    if (token === "non-thrown-ranged") return item?.kind === "ranged-weapon" && !item.tags.includes("thrown");
    if (token === "equipment") return true;
    if (item === null) return false;
    if (EQUIPMENT_TAG_VOCABULARY.includes(token)) return item.tags.includes(token);
    if (token === "armour") return ["armour", "shield-or-defence"].includes(item.kind);
    if (token === "armour-suit") return item.kind === "armour" || item.mechanic_id === "defence.sea-dragon-cloak";
    if (token === "heavy-armour") return item.mechanic_id !== null && HEAVY_ARMOUR.includes(item.mechanic_id);
    if (token === "weapons") return WEAPON_KINDS.includes(item.kind) || item.mechanic_id !== null && item.mechanic_id.startsWith("weapon.");
    if (token === "two-handed-weapons") return (item.hands ?? 0) >= 2;
    return token === "ranged-weapons" && item.kind === "ranged-weapon";
  }
  function tokenPermits(token, itemId, item) {
    return token === itemId || token === item?.mechanic_id || token === item?.kind;
  }
  var NEUTRAL_ITEM_IDS = ["weapon.fist", "armour.no-armour", "material.normal"];
  var EQUIPMENT_MECHANIC_PREFIXES = [
    "weapon.",
    "armour.",
    "defence.",
    "material.",
    "preparation.",
    "poison."
  ];
  function isEquipmentMechanic(id) {
    return EQUIPMENT_MECHANIC_PREFIXES.some((prefix) => id.startsWith(prefix));
  }
  function equipmentIssue(args) {
    const { profile, item_id: itemId, item } = args;
    const subject = [profile.band_id, profile.profile_id, itemId];
    if (NEUTRAL_ITEM_IDS.includes(itemId)) return null;
    if (profile.fixed_equipment.includes(itemId)) return null;
    const offers = (profile.equipment_access ?? []).filter((offer) => offer.list_id === void 0 || !(args.gated_lists ?? []).includes(offer.list_id) || (args.active_lists ?? []).includes(offer.list_id));
    const offered = profile.equipment_access !== null && offers.some((offer) => offer.item_id === itemId);
    if (profile.equipment_access !== null && !offered) return {
      code: "equipment_not_permitted",
      subject_ids: subject,
      message: `"${itemId}" is not on any equipment list of ${profile.band_id}/${profile.profile_id}.`
    };
    const forbids = [...profile.equipment_forbids, ...args.band_forbids ?? []];
    for (const token of forbids) if (tokenForbids(token, itemId, item)) return {
      code: "equipment_forbidden",
      subject_ids: subject,
      message: `"${token}" is forbidden for ${profile.band_id}/${profile.profile_id}.`
    };
    const unknown = forbids.find((token) => !INTERPRETED_TOKENS.includes(token) && token !== itemId && !["armour.", "defence.", "weapon."].some((prefix) => token.startsWith(prefix)));
    if (unknown) return {
      code: "construction_clause_unstructured",
      subject_ids: subject,
      rule_id: unknown,
      owner_task: "KB",
      message: `The prohibition token "${unknown}" of ${profile.band_id}/${profile.profile_id} has no construction contract; the choice is reported, not silently allowed.`
    };
    if (item === null && offered) return {
      code: "equipment_unknown_item",
      subject_ids: subject,
      owner_task: "KB",
      message: `"${itemId}" is offered by ${profile.band_id}/${profile.profile_id} but has no item record in the KB artefact.`
    };
    return null;
  }
  function itemIsMissile(item) {
    if (!item) return false;
    if (item.kind === "ranged-weapon") return true;
    return ["bow", "crossbow", "blackpowder", "thrown"].some((tag) => item.tags.includes(tag));
  }
  function weaponSatisfiesKind(kind, itemId, item) {
    if (kind === "ranged-weapon") return itemIsMissile(item);
    if (kind === "close-combat-weapon") return !itemIsMissile(item) && tokenForbids("weapons", itemId, item);
    return item?.kind === kind;
  }
  function poisonApplicationIssue(args) {
    const { profile, poison_id: poisonId } = args;
    const poisonIds = [poisonId, args.poison?.mechanic_id ?? ""].filter((id) => id !== "");
    const governed = (profile.poison_application ?? []).filter((application) => application.poisons.some((id) => poisonIds.includes(id)));
    if (!governed.length) return null;
    if (governed.some((application) => application.weapon_kinds.some((kind) => weaponSatisfiesKind(kind, args.weapon_id, args.weapon)))) return null;
    const kinds = Array.from(new Set(governed.flatMap((application) => application.weapon_kinds)));
    return {
      code: "equipment_forbidden",
      rule_id: governed[0].rule_id,
      subject_ids: [profile.band_id, profile.profile_id, poisonId, args.weapon_id],
      message: `"${poisonId}" may only be applied to ${kinds.join("/")} by ${profile.band_id}/${profile.profile_id}.`
    };
  }
  function skillIssue(profile, skill, strictEmptyAccess = false) {
    const subject = [profile.band_id, profile.profile_id, skill.id];
    if (profile.skill_access.length === 0 && !strictEmptyAccess) return null;
    if (!skillCategoryAllowed(profile.skill_access, skill.category, strictEmptyAccess)) return {
      code: "skill_not_permitted",
      subject_ids: subject,
      message: `"${skill.id}" (${skill.category}) is outside the skill access of ${profile.band_id}/${profile.profile_id}.`
    };
    if (skill.category === "special") {
      const lists = profile.skill_lists.filter((list) => list.category === "special");
      if (lists.length === 0 || lists.every((list) => list.skills.length === 0)) return {
        code: "skill_pending_special_list",
        subject_ids: subject,
        owner_task: "KB",
        message: `"${skill.id}" belongs to a band special-skill list whose members are prose-only in the KB; the list rule is not enforced yet.`
      };
      if (!lists.some((list) => list.skills.includes(skill.id))) return {
        code: "skill_not_permitted",
        subject_ids: subject,
        ...lists[0] ? { rule_id: lists[0].rule_id } : {},
        message: `"${skill.id}" is not on the published special-skill list of ${profile.band_id}/${profile.profile_id} (${lists.map((list) => list.rule_id).join(", ")}).`
      };
    }
    return null;
  }
  function skillCategoryAllowed(access, category, strictEmptyAccess = false) {
    return !access.length && !strictEmptyAccess || access.includes(category);
  }
  function equipmentSetIssues(args) {
    const { profile, limits, items } = args;
    const subject = [profile.band_id, profile.profile_id];
    const issues = [];
    for (const bound of profile.missile_weapon_limit ?? []) {
      const exempt = (entry) => bound.exempt_item_ids.includes(entry.item_id) || entry.item?.mechanic_id != null && bound.exempt_item_ids.includes(entry.item.mechanic_id);
      const counted = items.filter((entry) => itemIsMissile(entry.item) && !exempt(entry));
      if (counted.length > bound.maximum) issues.push({
        code: "equipment_limit_exceeded",
        rule_id: bound.rule_id,
        subject_ids: [...subject, ...counted.map((entry) => entry.item_id)],
        message: `${profile.band_id}/${profile.profile_id} carries ${counted.length} missile weapons; the printed clause allows ${bound.maximum}` + (bound.exempt_item_ids.length ? ` besides ${bound.exempt_item_ids.join(", ")}.` : ".")
      });
    }
    if (limits) {
      const carried = items.filter((entry) => entry.item?.kind === "ranged-weapon");
      if (typeof limits.max_missile_weapons === "number" && carried.length > limits.max_missile_weapons) issues.push({
        code: "equipment_limit_exceeded",
        subject_ids: [...subject, ...carried.map((entry) => entry.item_id)],
        ...limits.rule_id ? { rule_id: limits.rule_id } : {},
        message: `${profile.band_id}/${profile.profile_id} carries ${carried.length} missile weapons; the band allows ${limits.max_missile_weapons}.`
      });
      if (!(limits.exempt_profile_ids ?? []).includes(profile.profile_id) && limits.required_tag?.trim() && !items.some((entry) => entry.item?.tags.includes(limits.required_tag))) issues.push({
        code: "equipment_required_missing",
        subject_ids: subject,
        ...limits.rule_id ? { rule_id: limits.rule_id } : {},
        message: `The equipment of ${profile.band_id}/${profile.profile_id} includes no "${limits.required_tag}": the band compiles the kit from that family only.`
      });
      const limit = limits.item_copy_limit;
      if (limit) {
        const copies = items.filter((entry) => entry.item_id === limit.item_id || entry.item?.mechanic_id === limit.item_id);
        const exempt = limit.exempt_profile_ids.includes(profile.profile_id);
        const maximum = exempt ? limit.exempt_maximum : limit.maximum;
        if (typeof maximum === "number" && copies.length > maximum) issues.push({
          code: "equipment_limit_exceeded",
          subject_ids: [...subject, limit.item_id],
          ...limits.rule_id ? { rule_id: limits.rule_id } : {},
          message: `${profile.band_id}/${profile.profile_id} carries ${copies.length} copies of "${limit.item_id}"; the printed clause allows ${maximum} for this bearer.`
        });
      }
    }
    for (const requirement of profile.required_equipment ?? []) {
      const satisfied = items.some((entry) => {
        const item = entry.item;
        if (NEUTRAL_ITEM_IDS.includes(entry.item_id)) return false;
        const named = requirement.kinds.includes(entry.item_id) || item?.mechanic_id != null && requirement.kinds.includes(item.mechanic_id);
        if (!named && (item === null || !requirement.kinds.includes(item.kind))) return false;
        return ![entry.item_id, item?.mechanic_id ?? ""].some((id) => requirement.excludes.includes(id));
      });
      if (!satisfied) issues.push({
        code: "equipment_required_missing",
        subject_ids: [...subject, ...requirement.kinds],
        rule_id: requirement.rule_id,
        message: `The equipment of ${profile.band_id}/${profile.profile_id} includes no ${requirement.kinds.join("/")}; the printed clause obliges acquiring one.`
      });
    }
    return issues;
  }
  function entryReachesProfile(entry, profile) {
    const recipients = entry.applies_to;
    if (!recipients) return true;
    if ((recipients.excluded_profile_ids ?? []).includes(profile.id)) return false;
    if (recipients.variants?.length && !recipients.variants.some((token) => (profile.variants ?? []).includes(token))) return false;
    if (!recipients.profile_types?.length && !recipients.profile_ids?.length) return true;
    if ((recipients.profile_types ?? []).includes(profile.type ?? "")) return true;
    return (recipients.profile_ids ?? []).includes(profile.id);
  }
  function resolveHirelingKit(equipment, build, catalogue, rules = []) {
    const unique = equipment.unique_equipment ?? [];
    for (const item of unique) {
      if (!item.id || !item.rules?.length || !item.rules.every((id) => {
        const matching = rules.filter((rule) => rule.id === id);
        return matching.length === 1 && matching[0].runtime?.scope === "NO" && matching[0].runtime?.implemented === "NO" && !matching[0].bindings?.length;
      })) throw new Error("hireling unique equipment needs a canonical combat mapping");
    }
    const expand = (entries) => entries.flatMap((entry) => {
      const count = entry.quantity.value;
      if (entry.quantity.kind !== "fixed" || !Number.isInteger(count) || count === void 0 || count < 1)
        throw new Error(`unsupported hireling kit quantity: ${entry.item_id}`);
      return Array.from({ length: count }, () => entry.item_id);
    });
    let kits = [[...expand(equipment.fixed_items ?? []), ...unique.map((item) => item.id)]];
    for (const group of equipment.choices ?? []) {
      if (group.choose !== 1 || !group.options.length) throw new Error("unsupported hireling equipment choice");
      kits = kits.flatMap((kit) => group.options.map((option) => [...kit, ...expand(option.items)]));
    }
    for (const entry of equipment.optional_items ?? []) {
      const addition = expand([entry]);
      kits = kits.flatMap((kit) => [kit, [...kit, ...addition]]);
    }
    const signature = (items) => [...items].sort().join("\0");
    const neutral = /* @__PURE__ */ new Set(["weapon.fist", "armour.no-armour"]);
    const active = [
      build.main_weapon_id,
      build.off_hand_id,
      build.extra_hand_id,
      build.armour_id,
      ...build.defence_ids,
      ...build.preparation_ids,
      build.main_poison_id,
      build.off_poison_id
    ].filter((id) => Boolean(id) && !neutral.has(id ?? ""));
    if (active.some((id) => unique.some((item) => item.id === id)))
      throw new Error("non-duel unique equipment cannot occupy an active combat position");
    const owned = build.owned_item_ids;
    const matched = kits.find((kit) => {
      if (owned != null && signature(kit) !== signature(owned)) return false;
      const entries = [
        ...equipment.fixed_items ?? [],
        ...equipment.optional_items ?? [],
        ...(equipment.choices ?? []).flatMap((group) => group.options.flatMap((option) => option.items))
      ];
      const mechanic = (id) => entries.find((entry) => entry.item_id === id)?.mechanic_id ?? catalogue.mappings[id] ?? id;
      for (const [id, material] of [[build.main_weapon_id, build.main_material_id], [build.off_hand_id, build.off_material_id]]) {
        if (!id || neutral.has(id)) {
          if (material !== "material.normal") return false;
          continue;
        }
        const printed = entries.find((entry) => kit.includes(entry.item_id) && mechanic(entry.item_id) === id)?.material_id ?? "material.normal";
        if (material !== "material.normal" && material !== printed) return false;
      }
      const remaining = kit.map(mechanic);
      for (const id of active) {
        const position = remaining.indexOf(catalogue.mappings[id] ?? id);
        if (position < 0) return false;
        remaining.splice(position, 1);
      }
      return true;
    });
    if (!matched) throw new Error("hireling active equipment and supplied ownership do not form a complete legal printed kit");
    return matched;
  }
  var BLACKPOWDER_WEAPONS = ["weapon.pistol", "weapon.duelling-pistol"];
  var MISSILE_WEAPONS = BLACKPOWDER_WEAPONS;
  var DRUG_PREPARATIONS = ["preparation.crimson-shade", "preparation.mandrake-root", "preparation.mad-cap-mushrooms", "preparation.head-splitter-mushrooms"];
  function strings(value) {
    return typeof value === "string" ? [value] : Array.isArray(value) ? value.map(String) : [];
  }
  function containsAny(values, wanted) {
    return Array.from(values).some((value) => value != null && wanted.includes(value));
  }
  function pythonList(values) {
    return `[${values.map((value) => `'${value.replaceAll("'", "\\'")}'`).join(", ")}]`;
  }
  function loadoutItems(value) {
    if (typeof value === "string") return [value];
    if (Array.isArray(value)) return value.flatMap(loadoutItems);
    if (value && typeof value === "object") return Object.values(value).flatMap(loadoutItems);
    return [];
  }
  var BOUND_STAGE_TOKENS = ["armour", "ranged-weapons", "heavy-armour", "weapon.lance", "defence.helmet"];
  function carriedItemFacts(catalogue, id) {
    if (!id) return null;
    const items = catalogue.items ?? {};
    const direct = items[id];
    if (direct) return direct;
    const aliases = Object.values(items).filter((item) => item.mechanic_id === id);
    if (!aliases.length) return null;
    const kinds = Array.from(new Set(aliases.map((item) => item.kind)));
    return {
      kind: kinds.length === 1 ? kinds[0] : "",
      mechanic_id: id,
      tags: Array.from(new Set(aliases.flatMap((item) => item.tags)))
    };
  }
  function catalogueItemFacts(catalogue) {
    const items = catalogue.items ?? {};
    const result = { ...items };
    for (const id of Object.keys(items)) {
      const facts = carriedItemFacts(catalogue, id);
      const hands = catalogue.mechanics[facts?.mechanic_id ?? ""]?.["hands"];
      if (facts) result[id] = { ...facts, ...typeof hands === "number" ? { hands } : {} };
    }
    for (const row of Object.values(items)) {
      if (!row.mechanic_id) continue;
      const merged = carriedItemFacts(catalogue, row.mechanic_id);
      const hands = catalogue.mechanics[row.mechanic_id]?.["hands"];
      if (merged) result[row.mechanic_id] = { ...merged, ...typeof hands === "number" ? { hands } : {} };
    }
    return result;
  }
  function applicableProfileRules(pack, profile) {
    return pack.special_rules.filter((rule) => recipientTypeMatches(rule, profile) && ((profile.rule_ids ?? []).includes(rule.id) || rule.runtime?.grant === "profile" && (rule.applies_to?.profile_ids ?? []).includes(profile.id)));
  }
  function recipientTypeMatches(rule, profile) {
    return !rule.applies_to?.profile_types?.length || rule.applies_to.profile_types.includes(profile.type ?? "");
  }
  function configuredProfile(profile, variants) {
    const configured = variants.length ? { ...profile, variants: [...variants] } : profile;
    if (!variants.includes("promotion.hero") || profile.type === "hero") return configured;
    if (profile.type !== "henchman") throw new Error("promotion.hero requires a canonical Henchman profile");
    return { ...configured, type: "hero" };
  }
  function applicableRules(pack, profile) {
    const rules = applicableProfileRules(pack, profile);
    return [...rules, ...pack.special_rules.filter((rule) => !rules.includes(rule) && rule.runtime?.grant === "band" && recipientTypeMatches(rule, profile) && rule.applies_to?.band === true && (!rule.applies_to?.profile_ids?.length || rule.applies_to.profile_ids.includes(profile.id)) && (!rule.eligibility?.length || rule.eligibility.includes(profile.id)))];
  }
  function profileEquipmentItems(pack, profile) {
    const itemIds = new Set(profile.fixed_equipment ?? []);
    for (const listId of profile.equipment_lists ?? []) {
      const list = pack.equipment_lists.find((entry) => entry.id === listId);
      if (!list) throw new Error(`profile references unknown equipment list: ${pack.band.id}/${profile.id}/${listId}`);
      for (const item of list.items ?? []) {
        if (!entryReachesProfile(item, profile)) continue;
        itemIds.add(item.item_id);
      }
      for (const loadout of list.loadouts ?? []) for (const id of loadoutItems(loadout.items)) itemIds.add(id);
    }
    if (profile.type !== "hero") {
      itemIds.delete("darksteel_blade");
    }
    if (itemIds.has("spirit_knife")) {
      const etherealHero = pack.band.id === "call-of-the-night-haint-mim" && profile.type === "hero" && (profile.rule_ids ?? []).some((id) => id.endsWith("--ethereal") || id === "revenants--spectral-ascension");
      if (!etherealHero) itemIds.delete("spirit_knife");
    }
    if (pack.band.id === "savage-orcs-kaz" && profile.id === "gobbo-boyz") itemIds.delete("skull_busta");
    return itemIds;
  }
  function profileEquipment(pack, profile, catalogue) {
    const itemIds = profileEquipmentItems(pack, profile);
    const allowed = new Set(Array.from(itemIds).flatMap((id) => catalogue.mappings[id] ? [catalogue.mappings[id]] : []));
    for (const rule of applicableProfileRules(pack, profile)) for (const binding of rule.bindings ?? []) {
      if (isEquipmentMechanic(binding.id) && binding.id in catalogue.mechanics) allowed.add(binding.id);
    }
    return Array.from(allowed).sort();
  }
  function specialRuleOptions(pack, profile, catalogue) {
    const result = pack.special_rules.filter((rule) => rule.kind === "warband_skill" && recipientTypeMatches(rule, profile) && (!rule.eligibility?.length || rule.eligibility.includes(profile.id)) && (!rule.applies_to?.profile_ids?.length || rule.applies_to.profile_ids.includes(profile.id)) && (Boolean(rule.eligibility?.length || rule.applies_to?.profile_ids?.length) || (profile.skill_access ?? []).includes("special"))).map((rule) => rule.id);
    if (applicableRules(pack, profile).some((rule) => rule.runtime?.implemented === "YES" && rule.bindings?.some((binding) => binding.id === "compiler.slayer-skill-options"))) {
      const dwarf = catalogue.packages["chaos-streets-dwarf-treasure-hunters"];
      for (const rule of dwarf?.special_rules ?? []) if (rule.kind === "warband_skill" && rule.runtime?.implemented === "YES") result.push(rule.id);
    }
    return result.sort();
  }
  function selectableRuleOptions(pack, profile) {
    return pack.special_rules.filter((rule) => rule.kind !== "warband_skill" && rule.runtime?.grant === "selectable" && recipientTypeMatches(rule, profile) && (!rule.eligibility?.length || rule.eligibility.includes(profile.id)) && (!rule.applies_to?.profile_ids?.length || rule.applies_to.profile_ids.includes(profile.id))).map((rule) => rule.id).sort();
  }
  function buildAccess(context) {
    const { build, profile, package: pack, catalogue, contracts, profile_bindings, compiler_bindings } = context;
    const equipment = new Set(profileEquipment(pack, profile, catalogue));
    const addLists = (lists) => {
      for (const list of lists) for (const item of list.items ?? []) {
        if (!entryReachesProfile(item, profile)) continue;
        const id = catalogue.mappings[item.item_id];
        if (id) equipment.add(id);
      }
    };
    if (contracts.includes("compiler.pirate-human-mercenary-equipment-access")) addLists(catalogue.foreign_packages["mercenaries"]?.equipment_lists ?? []);
    if (contracts.includes("compiler.foreign-or-native-background")) {
      const background = build.variant_ids.includes("background.native") || !build.variant_ids.length && ["spirits", "jackals"].includes(profile.id) ? "native" : "foreign";
      addLists(pack.equipment_lists.filter((list) => list.id === `${background}-${profile.id === "beloved" ? "beloved" : "undead"}-equipment-list`));
    }
    if (contracts.includes("compiler.knighthood") && build.variant_ids.includes("promotion.knight-errant")) {
      equipment.clear();
      addLists(pack.equipment_lists.filter((list) => list.id === "knights-equipment-list"));
    }
    if (contracts.includes("compiler.follow-the-darkest-tribe") && build.variant_ids.includes("tribe.kurgan")) {
      for (const candidate of Object.values(catalogue.foreign_packages)) addLists(candidate.equipment_lists.filter((list) => list.items?.some((item) => item.item_id === "wolfcloak")));
    }
    if (contracts.includes("compiler.proven-warrior")) {
      const blackOrc = pack.profiles.find((row) => row.id === "black-orcs");
      addLists(pack.equipment_lists.filter((list) => blackOrc?.equipment_lists?.includes(list.id)));
    }
    if (contracts.includes("compiler.weapon-knowledge")) {
      for (const id of Object.keys(catalogue.mechanics)) if (id.startsWith("weapon.")) equipment.add(id);
    }
    const skills = new Set(profile.skill_access ?? []);
    const promoted = profile.type === "hero" || build.variant_ids.includes("promotion.hero");
    for (const binding of profile_bindings) if (binding.id === "profile.skill-access") for (const value of strings(binding.parameters?.["category"])) skills.add(value);
    for (const binding of compiler_bindings) if (binding.id === "compiler.promoted-hero-skill-access" && promoted) for (const value of strings(binding.parameters?.["allowed_skill_lists"])) skills.add(value);
    if (contracts.includes("compiler.promoted-hero-no-strength-access")) {
      for (const id of build.variant_ids) if (id.startsWith("skill-list.")) skills.add(id.slice(11));
    }
    if (contracts.includes("compiler.slayer-skill-options")) for (const category of ["combat", "strength", "special"]) skills.add(category);
    if (contracts.includes("compiler.proven-warrior")) for (const category of ["combat", "shooting", "strength", "speed", "special"]) skills.add(category);
    if (contracts.includes("compiler.knighthood")) {
      const categories = build.variant_ids.includes("promotion.knight-errant") ? ["combat", "academic", "strength", "speed", "special"] : build.variant_ids.includes("promotion.squire") ? ["combat", "academic", "strength", "speed"] : [];
      for (const category of categories) skills.add(category);
    }
    return { equipment: Array.from(equipment).sort(), skills: Array.from(skills).sort() };
  }
  function buildRestriction(context, stage) {
    const { build: b, profile: p, package: pack, catalogue: c, contracts, profile_bindings, compiler_bindings } = context;
    const who = `${b.band_id}/${b.profile_id}`;
    const hands = [b.main_weapon_id, b.off_hand_id, b.extra_hand_id];
    const selected = [...hands, b.armour_id, ...b.defence_ids];
    const has = (id) => contracts.includes(id);
    const forbiddenSkills = (predicate) => b.skill_ids.filter(predicate).sort();
    const magic = (id) => id.includes("arcane") || id.includes("sorcery");
    if (stage === "implicitWeapon") {
      if (b.main_weapon_id !== "weapon.dagger") return null;
      const facts = profileFactsProjection({ pack, profile: p, catalogue: c });
      const issue = equipmentIssue({ profile: facts, item_id: "weapon.dagger", item: carriedItemFacts(c, "weapon.dagger") });
      return issue && !issueIsInformational(issue.code) ? issue.message : null;
    }
    if (stage === "boundEquipment") {
      if (p.hireling_equipment) {
        try {
          resolveHirelingKit(p.hireling_equipment, b, c, pack.special_rules);
        } catch (error) {
          return error instanceof Error ? error.message : String(error);
        }
      }
      const profileFacts2 = profileFactsProjection({ pack, profile: p, catalogue: c });
      if (profileFacts2.active_weapon_limit || profileFacts2.active_weapon_forbids?.length || profileFacts2.active_weapon_permits?.length) {
        const issues = activeWeaponIssues({
          profile: profileFacts2,
          items: catalogueItemFacts(c),
          skills: {},
          slots: { main_weapon_id: b.main_weapon_id, off_hand_id: b.off_hand_id ?? null, extra_hand_id: b.extra_hand_id ?? null }
        });
        if (issues.length) return issues[0].message;
      }
      const forbidden2 = profile_bindings.filter((binding) => binding.id === "profile.equipment-restrictions").flatMap((binding) => strings(binding.parameters?.["forbids"]));
      if (forbidden2.includes("armour") && (b.armour_id !== "armour.no-armour" || b.defence_ids.includes("defence.sea-dragon-cloak") || containsAny(selected, ["defence.shield", "defence.buckler", "defence.helmet", "defence.cooking-pot-helmet"]))) return `armour is forbidden for ${who}`;
      if (forbidden2.includes("ranged-weapons") && containsAny(selected, MISSILE_WEAPONS)) return `missile weapons are forbidden for ${who}`;
      if (forbidden2.includes("heavy-armour") && HEAVY_ARMOUR.includes(b.armour_id)) return `heavy armour is forbidden for ${who}`;
      if (forbidden2.includes("weapon.lance") && selected.includes("weapon.lance")) return `lance is forbidden for ${who}`;
      if (forbidden2.includes("defence.helmet") && containsAny(selected, ["defence.helmet", "defence.cooking-pot-helmet"])) return `helmet is forbidden for ${who}`;
      const sharedTokens = forbidden2.filter((token) => !BOUND_STAGE_TOKENS.includes(token) && (INTERPRETED_TOKENS.includes(token) || token.includes(".") || carriedItemFacts(c, token) !== null));
      if (sharedTokens.length) for (const id of selected) {
        if (!id) continue;
        const issue = equipmentIssue({
          profile: {
            band_id: b.band_id ?? "custom",
            profile_id: p.id,
            fixed_equipment: [],
            equipment_access: null,
            equipment_forbids: sharedTokens,
            skill_access: [],
            skill_lists: []
          },
          item_id: id,
          item: carriedItemFacts(c, id)
        });
        if (issue && !issueIsInformational(issue.code)) return issue.message;
      }
      return null;
    }
    if (stage === "categoryProhibitions") {
      if (has("compiler.no-missile-weapons") && containsAny(hands, MISSILE_WEAPONS)) return `missile weapons are forbidden for ${who}`;
      if (has("compiler.no-blackpowder-weapons") && containsAny(hands, BLACKPOWDER_WEAPONS)) return `blackpowder weapons are forbidden for ${who}`;
      if (has("compiler.strictures") && ["dragon-monks", "warrior-monks"].includes(p.id) && (b.armour_id !== "armour.no-armour" || b.defence_ids.includes("defence.sea-dragon-cloak"))) return "Dragon Monks and Warrior Monks may never wear armour";
      const categories = compiler_bindings.filter((binding) => binding.id === "compiler.forbid-item-categories").flatMap((binding) => strings(binding.parameters?.["categories"]));
      if (categories.includes("poison") && (b.main_poison_id || b.off_poison_id)) return `poisons are forbidden for ${who}`;
      if (categories.includes("drug") && containsAny(b.preparation_ids, DRUG_PREPARATIONS)) return `drugs are forbidden for ${who}`;
      return null;
    }
    if (stage === "requiredInitial") {
      if (has("compiler.sister-special-skills")) {
        const selected2 = b.special_rule_ids.filter((id) => id.startsWith("band--special-skills-"));
        if (selected2.length !== 2 || new Set(selected2).size !== 2)
          return "Blessing of Sigmar requires exactly two distinct Sisters special skills";
      }
      if (has("compiler.mutant-requires-mutation-at-recruitment") && !b.special_rule_ids.some((id) => id.startsWith("band--mutations-"))) return `at least one mutation is required for ${who}`;
      if (has("compiler.nurgle-s-blessings") && !b.special_rule_ids.some((id) => id.startsWith("band--blessings-of-nurgle-"))) return "Tainted Ones require at least one Blessing of Nurgle";
      return null;
    }
    if (stage === "mutationLimit") return has("compiler.possessed-optional-zero-to-two-mutations-at-recruitment") && b.special_rule_ids.filter((id) => id.startsWith("band--mutations-")).length > 2 ? `at most two mutations are allowed for ${who}` : null;
    if (stage === "initialChoices") {
      const count = b.special_rule_ids.filter((id) => id.startsWith("band--mutations-")).length;
      return has("compiler.mutation-purchase-at-recruitment") && count && !["mutants", "the-possessed"].includes(p.id) ? `mutations are available only to Mutants and the Possessed: ${who}` : null;
    }
    if (stage === "profileTail") return profileTail(context);
    if (stage !== "profileSelections") throw new Error(`unknown eligibility stage: ${stage}`);
    if (has("compiler.foreign-or-native-background")) {
      const native = b.variant_ids.includes("background.native") || !b.variant_ids.length && ["spirits", "jackals"].includes(p.id);
      if (["blood-slaves", "black-hounds"].includes(p.id) && native) return `${p.id} requires the Foreign background`;
      if (["spirits", "jackals"].includes(p.id) && !native) return `${p.id} requires the Native background`;
    }
    if (has("compiler.knighthood") && b.variant_ids.filter((id) => ["promotion.squire", "promotion.knight-errant"].includes(id)).length > 1) return "choose at most one Knighthood promotion";
    if (has("compiler.proven-warrior") && p.id !== "younguns") return "Proven Warrior may only be selected by a Young'un";
    const equipment = /* @__PURE__ */ new Set([b.main_weapon_id, b.armour_id, ...b.defence_ids]);
    if (b.off_hand_id) equipment.add(b.off_hand_id);
    if (b.main_material_id !== "material.normal") equipment.add(b.main_material_id);
    if (b.off_hand_id && b.off_material_id !== "material.normal") equipment.add(b.off_material_id);
    for (const id of ["armour.no-armour", "weapon.natural-attacks", "weapon.fist"]) equipment.delete(id);
    const knight = (p.rule_ids ?? []).some((id) => id.endsWith("--knight")) || b.variant_ids.includes("promotion.knight-errant");
    if (has("compiler.powder-s-expensive") && p.type !== "hero" && containsAny(hands, BLACKPOWDER_WEAPONS)) return `blackpowder weapons are forbidden for Bandit Henchmen: ${who}`;
    if (has("compiler.chivalry") && knight) {
      if (containsAny(hands, MISSILE_WEAPONS)) return `missile weapons are forbidden for Knights: ${who}`;
      if (b.main_poison_id || b.off_poison_id) return `poisons are forbidden for Knights: ${who}`;
      if (containsAny(b.preparation_ids, DRUG_PREPARATIONS)) return `drugs are forbidden for Knights: ${who}`;
    }
    if (has("compiler.haughty") && containsAny(equipment, ["material.gromril", "material.obsidian", "armour.gromril-armour"])) return `Dwarf-made equipment is forbidden for ${who}`;
    if (has("compiler.chaos-engineer") && Array.from(equipment).some((id) => id.includes("chaos"))) return `Chaos armour is forbidden for ${who}`;
    if (has("compiler.saurus-skill-prohibitions") && ["saurus-totem-warrior", "saurus-braves"].includes(p.id) && containsAny(hands, MISSILE_WEAPONS)) return "missile weapons are forbidden for Saurus";
    const access = buildAccess(context);
    const neutralProfile = {
      band_id: b.band_id ?? "custom",
      profile_id: p.id,
      fixed_equipment: [],
      equipment_forbids: [],
      equipment_access: access.equipment.map((item_id) => ({ item_id })),
      skill_access: access.skills,
      skill_lists: profileSkillLists(pack, p).length ? profileSkillLists(pack, p) : [{ rule_id: p.id, category: "special", skills: Object.values(c.skills).filter((skill) => (skill.source_refs ?? []).some((ref) => [b.band_id, pack.band.canonical_family].some((band) => band && (ref.url ?? "").includes(`/${band}`)))).map((skill) => skill.id) }]
    };
    const illegal = Array.from(equipment).filter((id) => equipmentIssue({
      profile: neutralProfile,
      item_id: id,
      item: { kind: "", mechanic_id: id, tags: [] }
    })?.code === "equipment_not_permitted").sort();
    if (illegal.length) return `equipment is not available to ${who}: ${pythonList(illegal)}`;
    const promoted = b.variant_ids.filter((id) => id.startsWith("skill-list.")).map((id) => id.slice(11));
    if (has("compiler.promoted-hero-no-strength-access")) {
      if (promoted.includes("strength")) return `Strength skill list is forbidden for ${who}`;
      if (promoted.length > 2) return "a promoted Hero may choose at most two skill lists";
    }
    if (has("compiler.saurus-skill-prohibitions") && ["saurus-totem-warrior", "saurus-braves"].includes(p.id)) {
      const ids = forbiddenSkills((id) => c.skills[id]?.category === "academic");
      if (ids.length) return `Academic skills are forbidden for Saurus: ${pythonList(ids)}`;
    }
    for (const [contract, text] of [
      ["compiler.disciple-of-sigmar", `sorcery and Arcane Lore are forbidden for ${who}`],
      ["compiler.swabbie-rabble-loadout", "magic is forbidden for Swabbies"],
      ["compiler.no-arcane-lore", `Arcane Lore is forbidden for ${who}`]
    ]) {
      const ids = forbiddenSkills(magic);
      if (has(contract) && ids.length) return `${text}: ${pythonList(ids)}`;
    }
    if (has("compiler.promoted-hero-no-strength-access")) {
      const ids = forbiddenSkills((id) => c.skills[id]?.category === "strength");
      if (ids.length) return `Strength skills are forbidden for ${who}: ${pythonList(ids)}`;
    }
    const banned = compiler_bindings.filter((binding) => binding.id === "compiler.forbid-skill-categories").flatMap((binding) => strings(binding.parameters?.["categories"]));
    const forbidden = forbiddenSkills((id) => banned.includes(c.skills[id]?.category ?? ""));
    if (forbidden.length) return `skills are forbidden for ${who}: ${pythonList(forbidden)}`;
    const illegalSkills = forbiddenSkills((id) => {
      const skill = c.skills[id];
      return !skill || skillIssue(neutralProfile, skill, true) !== null;
    });
    if (illegalSkills.length) return `skills are not available to ${who}: ${pythonList(illegalSkills)}`;
    if (has("compiler.knighthood") && new Set(b.skill_ids.map((id) => c.skills[id]?.category).filter((category) => category !== "special")).size > 2) return "a promoted Squire may use at most two ordinary skill lists";
    const restrictions = (p.equipment_restrictions ?? []).join(" ").toLowerCase();
    if (["never wear armour", "cannot wear armour", "armour is not allowed", "does not allow armour", "using any armour", "non-armour items", "do not wear armour", "any form of armour", "do not use weapons or wear armour", "never use weapons or armour", "cannot use normal equipment"].some((text) => restrictions.includes(text)) && (b.armour_id !== "armour.no-armour" || b.defence_ids.includes("defence.sea-dragon-cloak"))) return `armour is forbidden for ${who}`;
    if ((restrictions.includes("may not use an off-hand weapon") || restrictions.includes("must use one hand")) && b.off_hand_id) return `off-hand equipment is forbidden for ${who}`;
    if ((restrictions.includes("may not use double-handed weapons") || restrictions.includes("double-handed weapons are for")) && c.mechanics[b.main_weapon_id]?.["hands"] === 2 && !has("compiler.proven-warrior")) return `two-handed weapons are forbidden for ${who}`;
    return null;
  }
  function profileTail(context) {
    const { build: b, profile: p, contracts } = context;
    const has = (id) => contracts.includes(id);
    const forbiddenSkills = (predicate) => b.skill_ids.filter(predicate).sort();
    const magic = (id) => id.includes("arcane") || id.includes("sorcery");
    if (has("compiler.sacred-marks") && b.special_rule_ids.filter((id) => id.startsWith("band--sacred-mark-")).length > 1) return "a Lizardman Hero may have at most one Sacred Mark";
    if (has("compiler.tracker-gear") && !["rope_hook", "bolas"].every((id) => (p.fixed_equipment ?? []).includes(id))) return "Trackers must begin with Rope and Hook and Bolas";
    if (has("compiler.vampiric-powers")) {
      const bloodline = p.id.endsWith("-vampire") ? p.id.slice(0, -8) : p.id;
      const foreign = b.special_rule_ids.filter((id) => id.includes("-power-") && !id.includes(`band--${bloodline}-power-`));
      if (foreign.length) return `Vampiric Powers must belong to the Vampire's bloodline: ${pythonList(foreign)}`;
    }
    if (has("compiler.warrior-s-code")) {
      const magicalSkills = forbiddenSkills((id) => magic(id) || id.includes("magic"));
      if (magicalSkills.length) return `magic is forbidden by the Warrior's Code: ${pythonList(magicalSkills)}`;
      const magical = b.special_rule_ids.filter((id) => ["spell", "magic", "arcane"].some((word) => id.includes(word))).sort();
      if (magical.length) return `magic is forbidden by the Warrior's Code: ${pythonList(magical)}`;
    }
    if (has("compiler.follow-the-darkest-tribe") && b.variant_ids.filter((id) => ["tribe.norse", "tribe.kurgan", "tribe.hung"].includes(id)).length > 1) return "choose exactly one Marauder tribe";
    if (has("compiler.foreign-or-native-background") && b.variant_ids.filter((id) => ["background.foreign", "background.native"].includes(id)).length > 1) return "choose exactly one Foreign or Native background";
    return null;
  }
  function selectionFactsOf(context, id) {
    return (context.selections ?? []).find((entry) => entry.id === id) ?? null;
  }
  function handsOf(context, entry, id) {
    if (entry?.paired) return 2;
    if (typeof entry?.hands === "number") return entry.hands;
    const item = entry?.item ?? context.items[id];
    if (!item) return 1;
    const facts = item.hands;
    return typeof facts === "number" ? facts : 1;
  }
  function ignoresHandRestrictions(context) {
    return (context.operation?.ignores_hand_restrictions ?? []).length > 0;
  }
  function activeLoadout(context) {
    const slots = context.slots;
    if (!slots) return [];
    return [
      slots.main_weapon_id,
      slots.off_hand_id,
      slots.extra_hand_id,
      slots.armour_id,
      ...slots.defence_ids ?? []
    ].filter((id) => Boolean(id) && id !== "armour.no-armour");
  }
  function activeWeaponIssues(context) {
    for (const restriction of context.profile.active_weapon_forbids ?? []) {
      for (const id of [context.slots?.main_weapon_id, context.slots?.off_hand_id, context.slots?.extra_hand_id]) {
        if (!id || NEUTRAL_ITEM_IDS.includes(id)) continue;
        if (restriction.forbids.some((token) => tokenForbids(token, id, itemFactsFor(context, id))))
          return [{
            code: "equipment_forbidden",
            rule_id: restriction.rule_id,
            subject_ids: [context.profile.band_id, context.profile.profile_id, id],
            message: `${id} may not be used by ${context.profile.band_id}/${context.profile.profile_id}.`
          }];
      }
    }
    for (const restriction of context.profile.active_weapon_permits ?? []) {
      for (const id of [context.slots?.main_weapon_id, context.slots?.off_hand_id, context.slots?.extra_hand_id]) {
        if (!id || NEUTRAL_ITEM_IDS.includes(id)) continue;
        if (restriction.permits.some((token) => tokenPermits(token, id, itemFactsFor(context, id)))) continue;
        return [{
          code: "equipment_forbidden",
          rule_id: restriction.rule_id,
          subject_ids: [context.profile.band_id, context.profile.profile_id, id],
          message: `${id} may not be used by ${context.profile.band_id}/${context.profile.profile_id}; the printed clause admits only ${restriction.permits.join(", ")}.`
        }];
      }
    }
    if (context.slots) {
      const mechanic = (id) => id ? itemFactsFor(context, id)?.mechanic_id ?? id : null;
      const cloakIssue = cloakArmourRestriction({
        ...buildFactsOf(context),
        armour_id: mechanic(context.slots.armour_id) ?? "armour.no-armour",
        defence_ids: (context.slots.defence_ids ?? []).map((id) => mechanic(id) ?? id)
      });
      if (cloakIssue) return [{
        code: "equipment_combination_forbidden",
        subject_ids: [context.profile.band_id, context.profile.profile_id],
        message: cloakIssue
      }];
      const message = skullBustaRestriction({
        ...buildFactsOf(context),
        main_weapon_id: mechanic(context.slots.main_weapon_id) ?? "weapon.fist",
        off_hand_id: mechanic(context.slots.off_hand_id),
        extra_hand_id: mechanic(context.slots.extra_hand_id)
      });
      if (message) return [{
        code: "equipment_combination_forbidden",
        subject_ids: [context.profile.band_id, context.profile.profile_id, "weapon.skull-busta"],
        message
      }];
    }
    const hellblade = hellbladeRestriction(buildFactsOf(context));
    if (hellblade) return [{
      code: "equipment_combination_forbidden",
      subject_ids: ["weapon.hellblade"],
      message: hellblade
    }];
    for (const [weaponKey, poisonKey] of [
      ["main_weapon_id", "main_poison_id"],
      ["off_hand_id", "off_poison_id"]
    ]) {
      const poisonId = context.slots?.[poisonKey];
      const weaponId = context.slots?.[weaponKey];
      if (!poisonId || !weaponId || NEUTRAL_ITEM_IDS.includes(weaponId)) continue;
      const poisonIssue = poisonApplicationIssue({
        profile: context.profile,
        poison_id: poisonId,
        poison: itemFactsFor(context, poisonId),
        weapon_id: weaponId,
        weapon: itemFactsFor(context, weaponId)
      });
      if (poisonIssue) return [poisonIssue];
    }
    const limit = context.profile.active_weapon_limit;
    if (!limit || !context.slots) return [];
    const weapons = [context.slots.main_weapon_id, context.slots.off_hand_id, context.slots.extra_hand_id].filter((id) => Boolean(id) && id !== "weapon.fist").filter((id) => {
      const item = itemFactsFor(context, id);
      return (item?.mechanic_id?.startsWith("weapon.") || item?.kind === "close-combat-weapon" || item?.kind === "weapon") && handsOf(context, selectionFactsOf(context, id), id) === 1;
    });
    return weapons.length > limit.maximum ? [{
      code: "equipment_limit_exceeded",
      rule_id: limit.rule_id,
      subject_ids: [context.profile.band_id, context.profile.profile_id, ...weapons],
      message: `${context.profile.band_id}/${context.profile.profile_id} may use at most ${limit.maximum} one-handed weapon at a time.`
    }] : [];
  }
  function itemFactsFor(context, id, explicit) {
    if (explicit !== void 0) return explicit;
    return context.items[id] ?? null;
  }
  function skillFactsFor(context, id, explicit) {
    if (explicit !== void 0) return explicit;
    return context.skills[id] ?? selectionFactsOf(context, id)?.skill ?? null;
  }
  function equipmentProposalIssues(context, proposal) {
    const entry = selectionFactsOf(context, proposal.id);
    const issues = [];
    const issue = equipmentIssue({
      profile: context.profile,
      item_id: proposal.id,
      item: itemFactsFor(context, proposal.id, proposal.item),
      band_forbids: context.band_forbids ?? [],
      active_lists: context.active_lists ?? [],
      gated_lists: context.gated_lists ?? []
    });
    if (issue) issues.push(issue);
    const slots = context.slots;
    const mechanic = itemFactsFor(context, proposal.id, proposal.item)?.mechanic_id ?? proposal.id;
    if (slots && (mechanic === "defence.sea-dragon-cloak" || mechanic.startsWith("armour."))) {
      const resolve = (id) => itemFactsFor(context, id)?.mechanic_id ?? id;
      const message = cloakArmourRestriction({
        ...buildFactsOf(context),
        armour_id: mechanic.startsWith("armour.") ? mechanic : resolve(slots.armour_id ?? "armour.no-armour"),
        defence_ids: [
          ...(slots.defence_ids ?? []).filter((id) => id !== proposal.replaces_id).map(resolve),
          ...mechanic === "defence.sea-dragon-cloak" ? [mechanic] : []
        ]
      });
      if (message) issues.push({
        code: "equipment_combination_forbidden",
        subject_ids: [context.profile.band_id, context.profile.profile_id, proposal.id],
        message
      });
    }
    if (slots && proposal.kind === "add" && proposal.slot !== "main") {
      const main = slots.main_weapon_id ?? "";
      const mainEntry = selectionFactsOf(context, main);
      const occupiesBothHands = main !== "" && handsOf(context, mainEntry, main) === 2;
      const off = slots.off_hand_id ?? "";
      if (occupiesBothHands && !ignoresHandRestrictions(context) && proposal.slot === "off") {
        issues.push({
          code: "equipment_slot_occupied",
          subject_ids: [context.profile.band_id, context.profile.profile_id, main, proposal.id],
          message: `The main weapon ${main} occupies both hands of ${context.profile.band_id}/${context.profile.profile_id}.`
        });
      }
      if (proposal.slot === "off" && off !== "" && off !== proposal.id && !ignoresHandRestrictions(context)) {
        issues.push({
          code: "equipment_slot_occupied",
          subject_ids: [context.profile.band_id, context.profile.profile_id, off, proposal.id],
          message: `The off hand of ${context.profile.band_id}/${context.profile.profile_id} already holds ${off}.`
        });
      }
    }
    if (slots && (proposal.kind === "replace" || proposal.slot === "main")) {
      const other = slots.off_hand_id ?? "";
      if (other !== "" && other !== proposal.id && !ignoresHandRestrictions(context)) {
        const mechanic2 = itemFactsFor(context, proposal.id, proposal.item)?.mechanic_id ?? proposal.id;
        const otherMechanic = itemFactsFor(context, other)?.mechanic_id ?? other;
        const combination = loadoutRestriction({
          build: { ...buildFactsOf(context, mechanic2), off_hand_id: otherMechanic },
          main_weapon: { main_hand: true, hands: handsOf(context, entry, proposal.id), paired: Boolean(entry?.paired) },
          off_weapon: { off_hand: true },
          contracts: [],
          selected_mechanics: [],
          stage: "hands"
        });
        if (combination) issues.push({
          code: "equipment_combination_forbidden",
          subject_ids: [context.profile.band_id, context.profile.profile_id, proposal.id, other],
          message: combination
        });
      }
    }
    if (slots && (proposal.kind === "add" || proposal.kind === "replace")) {
      if (proposal.slot === "main" || proposal.slot === "off" || proposal.slot === "extra") {
        const key = proposal.slot === "main" ? "main_weapon_id" : proposal.slot === "off" ? "off_hand_id" : "extra_hand_id";
        issues.push(...activeWeaponIssues({ ...context, slots: { ...slots, [key]: proposal.id } }));
      }
      const result = activeLoadout(context).filter((id) => id !== (proposal.replaces_id ?? "")).concat(proposal.id);
      const known = result.filter((id) => id !== "" && (itemFactsFor(context, id, id === proposal.id ? proposal.item : void 0) !== null || selectionFactsOf(context, id) !== null));
      for (const setIssue of equipmentSetIssues({
        profile: context.profile,
        limits: context.limits ?? null,
        items: known.map((item_id) => ({ item_id, item: itemFactsFor(context, item_id) }))
      })) issues.push(setIssue);
    }
    return issues;
  }
  function buildFactsOf(context, mainWeaponId) {
    const slots = context.slots ?? {};
    return {
      mounted: context.operation?.mounted ?? false,
      band_id: context.profile.band_id,
      profile_id: context.profile.profile_id,
      main_weapon_id: mainWeaponId ?? slots.main_weapon_id ?? "weapon.fist",
      armour_id: slots.armour_id ?? "armour.no-armour",
      off_hand_id: slots.off_hand_id ?? null,
      extra_hand_id: slots.extra_hand_id ?? null,
      main_material_id: slots.material_id ?? "material.normal",
      off_material_id: "material.normal",
      main_poison_id: slots.main_poison_id ?? null,
      off_poison_id: slots.off_poison_id ?? null,
      defence_ids: slots.defence_ids ?? [],
      skill_ids: Object.keys(context.skills),
      preparation_ids: [],
      special_rule_ids: [],
      variant_ids: []
    };
  }
  function skillProposalIssues(context, proposal) {
    const entry = selectionFactsOf(context, proposal.id);
    const skill = skillFactsFor(context, proposal.id, proposal.skill);
    const category = skill?.category ?? entry?.category ?? proposal.category ?? "";
    const strict = context.operation?.manual_skill_change === true || context.operation?.advance === true;
    const issues = [];
    const facts = skill ?? { id: proposal.id, category, kind: entry?.kind ?? "skill" };
    const issue = skillIssue(context.profile, facts, strict);
    if (issue) issues.push(issue);
    const banned = context.operation?.banned_skill_categories ?? [];
    const alreadyRefused = issues.some((entry2) => entry2.code === "skill_not_permitted");
    if (banned.includes(category) && !alreadyRefused) issues.push({
      code: "skill_not_permitted",
      subject_ids: [context.profile.band_id, context.profile.profile_id, proposal.id],
      message: `"${proposal.id}" (${category}) is forbidden for ${context.profile.band_id}/${context.profile.profile_id} by an implemented rule.`
    });
    return issues;
  }
  function selectionIssues(context, proposal) {
    if (proposal.kind === "remove") return [];
    const entry = selectionFactsOf(context, proposal.id);
    const isSkill = proposal.selection === "skill" || proposal.selection === void 0 && (entry?.skill !== void 0 || context.skills[proposal.id] !== void 0);
    return isSkill ? skillProposalIssues(context, proposal) : equipmentProposalIssues(context, proposal);
  }
  function selectionDecisions(context, proposals) {
    return proposals.map((proposal) => {
      const issues = selectionIssues(context, proposal);
      return {
        proposal,
        allowed: issues.every((issue) => issueIsInformational(issue.code)),
        issues: issues.filter((issue) => !issueIsInformational(issue.code)),
        reports: issues.filter((issue) => issueIsInformational(issue.code))
      };
    });
  }
  function validateConstruction(context, options = {}) {
    const issues = [...activeWeaponIssues(context)];
    const declared = [
      ...(context.selections ?? []).filter((entry) => entry.kind !== "skill" && !entry.skill).map((entry) => entry.id),
      ...activeLoadout(context)
    ];
    const possession = context.possession ?? [];
    const ids = Array.from(/* @__PURE__ */ new Set([...declared, ...possession]));
    for (const id of ids) {
      const item = itemFactsFor(context, id);
      const issue = equipmentIssue({
        profile: context.profile,
        item_id: id,
        item,
        band_forbids: context.band_forbids ?? [],
        active_lists: context.active_lists ?? [],
        gated_lists: context.gated_lists ?? []
      });
      if (issue) issues.push(issue);
    }
    for (const id of Object.keys(context.skills)) {
      const skill = context.skills[id];
      if (!skill) continue;
      const strict = context.operation?.manual_skill_change === true || context.operation?.advance === true;
      const issue = skillIssue(context.profile, skill, strict);
      if (issue) issues.push(issue);
    }
    const occurrences = (ids2) => {
      const counts = /* @__PURE__ */ new Map();
      for (const id of ids2) counts.set(id, (counts.get(id) ?? 0) + 1);
      return counts;
    };
    const declaredCounts = occurrences(declared);
    const ownedCounts = occurrences(possession);
    const setIds = [];
    for (const id of /* @__PURE__ */ new Set([...declaredCounts.keys(), ...ownedCounts.keys()])) {
      const copies = Math.max(declaredCounts.get(id) ?? 0, ownedCounts.get(id) ?? 0);
      for (let index = 0; index < copies; index += 1) setIds.push(id);
    }
    const setItems = setIds.map((item_id) => ({ item_id, item: itemFactsFor(context, item_id) }));
    for (const issue of equipmentSetIssues({ profile: context.profile, limits: context.limits ?? null, items: setItems })) {
      if (options.draft && issue.code === "equipment_required_missing") continue;
      issues.push(issue);
    }
    return issues;
  }
  function profileBindings(pack, profile) {
    return applicableRules(pack, profile).flatMap((rule) => rule.bindings ?? []);
  }
  function selectedRuleBindings(pack, rule_ids, catalogue) {
    const byId = /* @__PURE__ */ new Map();
    for (const rule of pack.special_rules) byId.set(rule.id, rule);
    for (const candidate of Object.values(catalogue?.packages ?? {})) {
      for (const rule of candidate.special_rules) if (!byId.has(rule.id)) byId.set(rule.id, rule);
    }
    for (const rule of Object.values(catalogue?.free_rules ?? {})) if (!byId.has(rule.id)) byId.set(rule.id, rule);
    return rule_ids.flatMap((id) => byId.get(id)?.bindings ?? []);
  }
  function profileFactsProjection(args) {
    const { pack, profile } = args;
    const bandId = args.band_id ?? pack.band.id;
    const forbids = [];
    const skillLists = [];
    const promotionSkills = [];
    let activeWeaponLimit;
    const activeWeaponForbids = [];
    const activeWeaponPermits = [];
    const requiredEquipment = [];
    const poisonApplication = [];
    const missileWeaponLimit = [];
    for (const rule of applicableRules(pack, profile)) for (const binding of rule.bindings ?? []) {
      if (binding.id === "compiler.promoted-hero-skill-access" && rule.runtime?.implemented === "YES") {
        for (const category of strings(binding.parameters?.["allowed_skill_lists"])) {
          if (!promotionSkills.includes(category)) promotionSkills.push(category);
        }
      }
      if (binding.id === "profile.active-weapon-restrictions") {
        const forbidden = strings(binding.parameters?.["forbids"]);
        if (forbidden.length) activeWeaponForbids.push({ rule_id: rule.id, forbids: forbidden });
        const permits = strings(binding.parameters?.["allowed_kinds"]);
        if (permits.length) activeWeaponPermits.push({ rule_id: rule.id, permits });
      }
      if (binding.id === "profile.equipment-restrictions") {
        const maximum = binding.parameters?.["max_active_one_handed_weapons"];
        if (maximum !== void 0) {
          if (typeof maximum !== "number" || !Number.isInteger(maximum) || maximum < 0) throw new Error("invalid active one-handed weapon limit");
          if (!activeWeaponLimit || maximum < activeWeaponLimit.maximum) activeWeaponLimit = { rule_id: rule.id, maximum };
        }
        for (const token of strings(binding.parameters?.["forbids"])) {
          const trimmed = token.trim();
          if (trimmed && !trimmed.startsWith("[") && !forbids.includes(trimmed)) forbids.push(trimmed);
        }
        const kinds = strings(binding.parameters?.["required_kinds"]);
        if (kinds.length) requiredEquipment.push({
          rule_id: rule.id,
          kinds,
          excludes: strings(binding.parameters?.["required_excludes"])
        });
        const governedPoisons = strings(binding.parameters?.["poisons"]);
        if (governedPoisons.length) poisonApplication.push({
          rule_id: rule.id,
          poisons: governedPoisons,
          weapon_kinds: strings(binding.parameters?.["weapon_kinds"])
        });
        const missileMaximum = binding.parameters?.["max_missile_weapons"];
        if (rule.runtime?.grant !== "band" && missileMaximum !== void 0) {
          if (typeof missileMaximum !== "number" || !Number.isInteger(missileMaximum) || missileMaximum < 0)
            throw new Error("invalid missile weapon limit");
          missileWeaponLimit.push({
            rule_id: rule.id,
            maximum: missileMaximum,
            exempt_item_ids: strings(binding.parameters?.["exempt_item_ids"])
          });
        }
      }
      if (binding.id === "profile.skill-access") {
        const category = strings(binding.parameters?.["category"])[0] ?? "";
        const skills = strings(binding.parameters?.["skills"]);
        if (category) skillLists.push({ rule_id: rule.id, category, skills });
      }
    }
    const access = args.catalogue ? Array.from(/* @__PURE__ */ new Set([...profileEquipmentItems(pack, profile), ...profileEquipment(pack, profile, args.catalogue)])).sort().map((item_id) => ({ item_id })) : null;
    const declaredSkills = Array.from(/* @__PURE__ */ new Set([...profile.skill_access ?? [], ...skillLists.map((list) => list.category)]));
    return {
      band_id: bandId,
      profile_id: profile.id,
      fixed_equipment: profile.fixed_equipment ?? [],
      equipment_access: access,
      equipment_forbids: forbids,
      // The promotion grant enters `skill_access` only for the configured Hero:
      // a canonical Henchman row carries it in `promotion_skill_access` alone, so
      // no early projection can hand the tables to an unpromoted fighter.
      skill_access: profile.type === "hero" ? Array.from(/* @__PURE__ */ new Set([...declaredSkills, ...promotionSkills])) : declaredSkills,
      skill_lists: skillLists,
      ...promotionSkills.length ? { promotion_skill_access: promotionSkills } : {},
      ...activeWeaponLimit ? { active_weapon_limit: activeWeaponLimit } : {},
      ...activeWeaponForbids.length ? { active_weapon_forbids: activeWeaponForbids } : {},
      ...activeWeaponPermits.length ? { active_weapon_permits: activeWeaponPermits } : {},
      ...requiredEquipment.length ? { required_equipment: requiredEquipment } : {},
      ...poisonApplication.length ? { poison_application: poisonApplication } : {},
      ...missileWeaponLimit.length ? { missile_weapon_limit: missileWeaponLimit } : {}
    };
  }
  function bandEquipmentLimits(pack) {
    const limits = {};
    for (const rule of pack.special_rules) {
      if (rule.runtime?.grant !== "band" || rule.applies_to?.band !== true) continue;
      for (const binding of rule.bindings ?? []) {
        if (binding.id !== "profile.equipment-restrictions") continue;
        const parameters = binding.parameters ?? {};
        const max = parameters["max_missile_weapons"];
        const required = parameters["required_tag"];
        const exempt = strings(parameters["exempt_profile_ids"]);
        const itemId = strings(parameters["max_item_id"])[0] ?? "";
        const maxCopies = parameters["max_item_copies"];
        const copies = itemId !== "" && typeof maxCopies === "number";
        if (typeof max !== "number" && typeof required !== "string" && !exempt.length && !copies) continue;
        limits.rule_id ??= rule.id;
        if (typeof max === "number") limits.max_missile_weapons = max;
        if (typeof required === "string") limits.required_tag = required;
        if (exempt.length) limits.exempt_profile_ids = exempt;
        if (copies) {
          const exemptMaximum = parameters["exempt_max_item_copies"];
          limits.item_copy_limit = {
            item_id: itemId,
            maximum: maxCopies,
            exempt_profile_ids: exempt,
            ...typeof exemptMaximum === "number" ? { exempt_maximum: exemptMaximum } : {}
          };
        }
      }
    }
    return Object.keys(limits).length ? limits : null;
  }
  function bandEquipmentForbids(pack) {
    const result = [];
    for (const rule of pack.special_rules) {
      if (rule.runtime?.grant !== "band" || rule.applies_to?.band !== true) continue;
      for (const binding of rule.bindings ?? []) {
        if (binding.id !== "profile.equipment-restrictions") continue;
        for (const token of strings(binding.parameters?.["forbids"])) {
          const trimmed = token.trim();
          if (trimmed && !trimmed.startsWith("[") && !result.includes(trimmed)) result.push(trimmed);
        }
      }
    }
    return result;
  }
  function profileSkillLists(pack, profile) {
    const lists = [];
    for (const rule of applicableRules(pack, profile)) for (const binding of rule.bindings ?? []) {
      if (binding.id !== "profile.skill-access") continue;
      const category = strings(binding.parameters?.["category"])[0] ?? "";
      if (category) lists.push({ rule_id: rule.id, category, skills: strings(binding.parameters?.["skills"]) });
    }
    return lists;
  }
  function specialRuleRestriction(args) {
    const { build: b, profile: p, rule } = args;
    const unavailable = `special rule is not available to ${b.band_id}/${b.profile_id}: ${rule.id}`;
    if (!args.stage || args.stage === "recipients") {
      if (p && !recipientTypeMatches(rule, p)) return unavailable;
      if (p && rule.eligibility?.length && !rule.eligibility.includes(p.id)) return unavailable;
      if (p && rule.applies_to?.profile_ids?.length && !rule.applies_to.profile_ids.includes(p.id)) return unavailable;
      if (rule.id.startsWith("band--blessings-of-nurgle-") && b.profile_id !== "tainted-ones") return unavailable;
      if (rule.id.startsWith("band--virtue-of-") && !args.native_virtue && !b.special_rule_ids.includes("band--renowned-virtue")) return "a foreign Bretonnian Virtue requires Renowned Virtue";
    }
    if ((!args.stage || args.stage === "prerequisites") && rule.id === "band--clan-pestilens-special-skills-ignore-pain" && ![...b.skill_ids, ...args.starting_skills].includes("skill.resilient")) return "Ignore Pain requires Resilient";
    if ((!args.stage || args.stage === "prerequisites") && rule.id === "strigoi-vampire--curse-of-the-revenant" && !b.special_rule_ids.includes("strigoi-vampire--great-thirster")) return "Curse of the Revenant requires Great Thirster";
    if ((!args.stage || args.stage === "prerequisites") && (rule.id === "bullied-goblin--frustratingly-tiny" && b.special_rule_ids.includes("bigsnotz--big-bully") || rule.id === "bigsnotz--big-bully" && b.special_rule_ids.includes("bullied-goblin--frustratingly-tiny"))) return "Frustratingly Tiny cannot be combined with Big Bully";
    if ((!args.stage || args.stage === "prerequisites") && b.band_id === "marauders-of-chaos" && rule.id.startsWith("band--mark-of-") && b.special_rule_ids.filter((id) => id.startsWith("band--mark-of-")).length > 1) return "a Marauder leader may have only one Mark of Chaos";
    const warbandSkill = rule.kind === "warband_skill" || rule.bindings?.some((binding) => binding.id.startsWith("skill."));
    if ((!args.stage || args.stage === "access") && p && warbandSkill && rule.applies_to?.band === true && !rule.eligibility?.length && !(p.skill_access ?? []).includes("special")) return unavailable;
    return null;
  }
  function skullBustaRestriction(b) {
    if ([b.off_hand_id, b.extra_hand_id].includes("weapon.skull-busta")) return "Skull Busta must be the main weapon";
    if (b.main_weapon_id !== "weapon.skull-busta") return null;
    if (b.mounted) return "Skull Busta may not be used while mounted";
    if ([b.off_hand_id, b.extra_hand_id].some((id) => id && !["defence.shield", "defence.kite-shield"].includes(id))) return "Skull Busta may only be combined with shields";
    return null;
  }
  function hellbladeRestriction(b) {
    if (b.main_weapon_id === "weapon.hellblade" && b.main_material_id !== "material.normal" || b.off_hand_id === "weapon.hellblade" && b.off_material_id !== "material.normal") {
      return "Hellblade cannot be made of mortal special metals";
    }
    return null;
  }
  function loadoutRestriction(args) {
    const { build: b, main_weapon: main, off_weapon: off, contracts, selected_mechanics: mechanics } = args;
    if (args.stage === "skills") return skillLoadoutRestriction(b, contracts, mechanics);
    if (mechanics.includes("mechanic.foul-odour") && (b.open_flame === true || [b.main_weapon_id, b.off_hand_id, b.extra_hand_id].includes("weapon.brazier-iron"))) return "Foul Odour forbids carrying open flames";
    if (mechanics.some((id) => ["mechanic.ethereal-hit-save", "mechanic.ghost-pirate-ethereal"].includes(id)) && b.skill_ids.some((id) => ["skill.step-aside", "skill.dodge"].includes(id))) return "Ethereal cannot be combined with Dodge or Step Aside";
    const hellblade = hellbladeRestriction(b);
    if (hellblade) return hellblade;
    const skullBusta = skullBustaRestriction(b);
    if (skullBusta) return skullBusta;
    if (!main["main_hand"]) return "illegal main-hand selection";
    if (b.special_rule_ids.includes("strigoi-vampire--curse-of-the-revenant") && !b.special_rule_ids.includes("strigoi-vampire--great-thirster")) return "Curse of the Revenant requires Great Thirster";
    if (b.special_rule_ids.includes("band--clan-pestilens-special-skills-contagious") && !b.special_rule_ids.includes("band--clan-pestilens-special-skills-rotten-body")) return "Contagious requires Rotten Body";
    if (b.special_rule_ids.includes("band--renowned-virtue") && b.special_rule_ids.filter((id) => id.startsWith("band--virtue-of-")).length !== 1) return "Renowned Virtue requires exactly one Bretonnian Virtue";
    if (b.off_hand_id) {
      if (b.off_hand_id.startsWith("weapon.") && !off?.["off_hand"]) return "illegal off-hand selection";
      if ((main["hands"] === 2 || main["paired"]) && !contracts.some((id) => ["compiler.ignore-difficult-to-use-restrictions", "compiler.master-of-arms"].includes(id))) return "main weapon occupies both hands";
      const restricted = {
        "weapon.morning-star": [],
        "weapon.natural-attacks": [],
        "weapon.fist": [],
        "weapon.spear": ["defence.shield", "defence.buckler"],
        "weapon.broadsword": ["defence.shield", "defence.kite-shield"],
        "weapon.squig-prodder": ["defence.shield", "weapon.spiked-gauntlet"],
        "weapon.boar-spear": ["defence.shield", "defence.buckler"]
      };
      if (restricted[b.main_weapon_id] && !restricted[b.main_weapon_id].includes(b.off_hand_id)) return `${b.main_weapon_id} cannot be combined with ${b.off_hand_id}`;
      if (["armour.toughened-leathers", "armour.ninja-robes"].includes(b.armour_id) && ["defence.shield", "defence.kite-shield"].includes(b.off_hand_id)) return "toughened leathers cannot be combined with a shield";
      if (["armour.wizard-s-robe", "armour.eshin-assassin-robes"].includes(b.armour_id) && ["defence.shield", "defence.buckler", "defence.kite-shield"].includes(b.off_hand_id)) return `${b.armour_id} cannot be combined with other armour except a helmet`;
    }
    return args.stage === "hands" ? null : skillLoadoutRestriction(b, contracts, mechanics);
  }
  function skillLoadoutRestriction(b, contracts, mechanics) {
    if (contracts.includes("compiler.berserker-incompatible-with-ferocious-charge") && mechanics.includes("skill.ferocious-charge")) return "Berserker may not be combined with Ferocious Charge";
    if (contracts.includes("compiler.censer-bearer-loadout")) {
      if (!mechanics.includes("mechanic.black-hunger")) return "Censer Bearer requires Black Hunger";
      if (b.main_weapon_id !== "weapon.censer" || b.off_hand_id) return "Censer Bearer may use only a Censer in close combat";
    }
    return null;
  }
  function cloakArmourRestriction(b) {
    return b.defence_ids.includes("defence.sea-dragon-cloak") && b.armour_id !== "armour.no-armour" ? "Sea Dragon cloak occupies the armour choice and cannot be combined with another suit" : null;
  }
  function additionalEquipmentRestriction(b) {
    if (b.special_rule_ids.includes("band--shield-bash") && !["defence.shield", "defence.kite-shield"].includes(b.off_hand_id ?? "")) return "Shield Bash requires a shield or kite shield";
    if (b.extra_hand_id) {
      if (!b.special_rule_ids.some((id) => ["band--mutations-extra-arm", "band--skaven-special-skills-tail-fighting"].includes(id))) return "an extra hand requires Extra Arm or Tail Fighting";
      if (b.extra_hand_id === "defence.kite-shield") return "the extra hand may not carry a kite shield";
      if (!b.extra_hand_id.startsWith("weapon.") && !["defence.shield", "defence.buckler"].includes(b.extra_hand_id)) return "the extra hand must hold a one-handed weapon, shield, or buckler";
    }
    return cloakArmourRestriction(b);
  }
  function catalogueEquipment(pack, profile, catalogue) {
    let actual = profile;
    if (pack.band.id === "khemri-lahmian-brotherhood" && !profile.equipment_lists?.length) {
      actual = { ...profile, equipment_lists: [`foreign-${profile.id === "beloved" ? "beloved" : "undead"}-equipment-list`] };
    }
    const result = new Set(profileEquipment(pack, actual, catalogue));
    if (pack.band.id === "lustria-pirates") for (const list of catalogue.foreign_packages["mercenaries"]?.equipment_lists ?? []) {
      for (const item of list.items ?? []) if (catalogue.mappings[item.item_id]) result.add(catalogue.mappings[item.item_id]);
    }
    return Array.from(result).sort();
  }
  function selectedRuleCandidates(context) {
    const { build: b, package: pack, catalogue: c, contracts } = context;
    const rules = b.band_id ? Object.fromEntries(pack.special_rules.map((rule) => [rule.id, rule])) : { ...c.free_rules };
    if (contracts.includes("compiler.slayer-skill-options")) for (const rule of c.packages["chaos-streets-dwarf-treasure-hunters"]?.special_rules ?? []) {
      if (rule.kind === "warband_skill" && rule.runtime?.implemented === "YES" && !rules[rule.id]) rules[rule.id] = { ...rule, eligibility: [], applies_to: {} };
    }
    if (b.special_rule_ids.includes("band--renowned-virtue")) for (const rule of c.foreign_packages["bretonnian-knights"]?.special_rules ?? []) {
      if (rule.id.startsWith("band--virtue-of-") && !rules[rule.id]) rules[rule.id] = { ...rule, eligibility: [] };
    }
    const count = b.special_rule_ids.filter((id) => id.startsWith("band--mutations-")).length;
    const grants = { "beastmen-raiders": "band--beastmen-special-skills-mutant", "marauders-of-chaos": "band--marauder-special-skills-mutant" };
    const grant = grants[b.band_id ?? ""];
    if (count && grant) {
      if (b.special_rule_ids.filter((id) => id === grant).length < count) return { rules, message: `each purchased mutation requires ${grant}` };
      for (const candidate of Object.values(c.packages)) for (const rule of candidate.special_rules) {
        if (rule.id.startsWith("band--mutations-") && !rules[rule.id]) rules[rule.id] = { ...rule, eligibility: [] };
      }
    }
    return { rules, message: null };
  }
  function bannedSkillCategories(pack, profile) {
    const banned = {};
    for (const rule of applicableRules(pack, profile)) if (rule.runtime?.implemented === "YES") {
      for (const binding of rule.bindings ?? []) if (binding.id === "compiler.forbid-skill-categories") {
        for (const category of strings(binding.parameters?.["categories"])) banned[category] ??= rule.id;
      }
    }
    return banned;
  }
  function catalogueSkillChoices(context) {
    const rules = applicableRules(context.package, context.profile);
    const bindings = rules.flatMap((rule) => rule.bindings ?? []);
    const compilerBindings = rules.filter((rule) => rule.runtime?.implemented === "YES").flatMap((rule) => rule.bindings ?? []).filter((binding) => binding.id.startsWith("compiler."));
    const access = buildAccess({
      ...context,
      profile_bindings: bindings.filter((binding) => binding.id.startsWith("profile.")),
      compiler_bindings: compilerBindings,
      contracts: compilerBindings.map((binding) => binding.id)
    });
    const profile = {
      band_id: context.package.band.id,
      profile_id: context.profile.id,
      fixed_equipment: [],
      equipment_access: null,
      equipment_forbids: [],
      skill_access: access.skills,
      skill_lists: profileSkillLists(context.package, context.profile)
    };
    const banned = bannedSkillCategories(context.package, context.profile);
    return Object.fromEntries(Object.values(context.catalogue.skills).map((skill) => [
      skill.id,
      skillIssue(profile, skill, true) === null && !(skill.category in banned)
    ]));
  }
  function warriorEquipmentRestriction(args) {
    const { warrior, item_id: itemId, item_name: name, category, profile, amount, weapon_hands: hands, stage } = args;
    const weaponId = (row) => stage ? row.base_item_id || row.item_id : row.base_item_id ?? row.item_id;
    if (stage !== "loadout") {
      const identity = [warrior.profile_name, warrior.profile_id, ...warrior.skills, ...warrior.special_rules ?? []].join(" ").replace(/[-_]/g, " ").toLowerCase();
      if (stage !== "profile" && ["armour", "shield-or-defence"].includes(category) && profile && strings(profile["equipment_forbids"]).includes("armour")) return "This warrior cannot wear armour, shields or bucklers.";
      const access = Array.isArray(profile?.["equipment_access"]) ? profile["equipment_access"] : [];
      const training = stage === "profile" ? (warrior.skill_ids ?? []).includes(category === "ranged-weapon" ? "skill.weapons-expert" : "skill.weapons-training") : /weapons? (training|expert)/.test(warrior.skills.join(" ").toLowerCase());
      if (["close-combat-weapon", "ranged-weapon"].includes(category) && warrior.profile_id && !warrior.profile_id.startsWith("hireling.") && (stage === "profile" ? profile !== null : access.length > 0) && !access.some((row) => row.item_id === itemId) && !training) return "This weapon is outside the warrior's equipment access.";
      if (itemId === "barbed_whip" && warrior.kind !== "hero") return "Barbed Whip may only be assigned to a Marauders of Chaos Hero.";
      if (itemId === "great_axe" && !(warrior.kind === "hero" && identity.includes("chosen of chaos"))) return "Great Axe requires a Marauders Hero with the Chosen of Chaos skill.";
      if (itemId === "reptile_venom" && !(warrior.kind === "henchman" && identity.includes("skink"))) return "Reptile Venom may only be assigned to Skink Henchmen.";
      if (["familiar", "arcane_familiar"].includes(itemId) && !identity.includes("spellcaster")) return "A Familiar may only be assigned to a spellcaster.";
      if (itemId === "book_of_the_dead" && !/(vampire|necromancer)/.test(identity)) return "The Book of the Dead may only be assigned to Vampires or Necromancers.";
      if (itemId === "nightmare" && !/(vampire|necromancer|grave guard)/.test(identity)) return "A Nightmare may only be assigned to Vampires, Necromancers or Grave Guards.";
      if (itemId === "temple_dog" && !/(dragon monk|sister|priest)/.test(identity)) return "A Temple Dog may only be assigned to Dragon Monks, Sisters of Sigmar or Priests.";
      if (["barding", "bretonnian_barding"].includes(itemId) && !warrior.equipment.some((row) => /(warhorse|horse)/i.test(`${row.name} ${row.item_id} ${stage === "profile" ? row.base_item_id ?? "" : ""}`))) return "Barding requires this warrior to have a Warhorse.";
      if (["dark_elf_blade_weapon_upgrade", "poisoned_weapon"].includes(itemId) && !warrior.equipment.some((row) => stage === "profile" ? hands[weaponId(row)] != null : hands[weaponId(row)] !== null)) return stage === "profile" ? `${name} requires an equipped weapon to upgrade.` : "This upgrade requires an equipped weapon.";
      if (itemId === "sword_heroes_only" && warrior.kind !== "hero") return "This Sword variant may only be assigned to Heroes.";
      const restricted = {
        beastlash: ["beastmaster"],
        broadsword: ["chapel guard knight"],
        serpent_staff: ["liche priest"],
        shortsword: ["chapel guard knight"],
        nehekharan_javelin: ["tomb lord"],
        swivel_gun: ["gunner"],
        kite_shield: ["chapel guard knight"],
        asp_arrows: ["tomb lord"],
        conch_shell_horn: ["piranha warrior"],
        elven_runestones: ["weaver"],
        parrot: ["captain", "mate"]
      };
      if (restricted[itemId] && !restricted[itemId].some((term) => identity.includes(term))) return (stage === "profile" ? args.profile_restriction_note : "") || `${name} cannot be assigned to this warrior.`;
      if (stage === "profile") return null;
    }
    const carried = warrior.equipment.filter((row) => row.acquisition !== (stage === "loadout" ? "starting_grant" : "fixed")), models = warrior.quantity ?? 1;
    const limit = warrior.equipment_limits?.["maximum_one_handed_weapons"];
    if (hands[itemId] === 1 && limit !== void 0) {
      const carriedHands = carried.filter((row) => hands[weaponId(row)] === 1).reduce((sum, row) => sum + row.quantity, 0);
      if (carriedHands + amount > limit * models) return `Injury limits this warrior to ${limit} one-handed weapon(s) per model.`;
    }
    if (!["close-combat-weapon", "ranged-weapon"].includes(category) && (stage === "loadout" ? warrior.equipment : carried).filter((row) => row.item_id === itemId).reduce((sum, row) => sum + row.quantity, 0) + amount > models) return `${name} is already carried; a warrior carries one of these.`;
    return null;
  }

  // packages/typescript/domain/eligibility/bridge.ts
  var catalogues = /* @__PURE__ */ new Map();
  function installCatalogue(key, catalogue) {
    catalogues.set(key, catalogue);
    return true;
  }
  function profileFacts(pack, profile, bandId, catalogue) {
    return profileFactsProjection({
      pack,
      profile,
      ...bandId ? { band_id: bandId } : {},
      ...catalogue ? { catalogue } : {}
    });
  }
  function bandFacts(pack) {
    return {
      equipment_forbids: bandEquipmentForbids(pack),
      equipment_limits: bandEquipmentLimits(pack)
    };
  }
  function profileSkillLists2(pack, profile) {
    return profileSkillLists(pack, profile);
  }
  function profileBindings2(pack, profile) {
    return profileBindings(pack, profile);
  }
  function selectedRuleBindings2(pack, ruleIds, catalogue) {
    return selectedRuleBindings(pack, ruleIds, catalogue);
  }
  function desktopCall(operation, key, input) {
    const catalogue = catalogues.get(key);
    if (!catalogue) throw new Error(`eligibility catalogue is not installed: ${key}`);
    const profile = input.profile.type ? configuredProfile(input.profile, input.build.variant_ids) : input.profile;
    const context = { ...input, profile, catalogue };
    input = { ...input, profile };
    if (operation === "hirelingKit") return resolveHirelingKit(input.profile.hireling_equipment ?? {}, input.build, catalogue, input.package.special_rules);
    if (operation === "equipment") return profileEquipment(input.package, input.profile, catalogue);
    if (operation === "specialRules") return specialRuleOptions(input.package, input.profile, catalogue);
    if (operation === "configuredRules") return selectableRuleOptions(input.package, input.profile);
    if (operation === "catalogueEquipment") return catalogueEquipment(input.package, input.profile, catalogue);
    if (operation === "selectedRules") return selectedRuleCandidates(context);
    if (operation === "ruleBindings") return selectedRuleBindings(
      input.package,
      input.build.special_rule_ids ?? [],
      catalogue
    );
    if (operation === "skillChoices") return catalogueSkillChoices(context);
    if (operation === "profileFacts") return profileFacts(input.package, input.profile, input.build.band_id ?? void 0, catalogue);
    if (operation === "bandFacts") return bandFacts(input.package);
    if (operation === "profileSkillLists") return profileSkillLists2(input.package, input.profile);
    if (operation === "profileBindings") return profileBindings2(input.package, input.profile);
    if (operation === "selectedRuleBindings") return selectedRuleBindings2(
      input.package,
      input.build.special_rule_ids ?? [],
      catalogue
    );
    return buildRestriction(context, operation);
  }
  function constructionCall(operation, key, input, proposals = [], options = {}) {
    const catalogue = catalogues.get(key);
    if (!catalogue) throw new Error(`eligibility catalogue is not installed: ${key}`);
    const context = { ...input, items: { ...catalogueItemFacts(catalogue), ...input.items } };
    if (operation === "selectionDecisions") return selectionDecisions(context, proposals);
    if (operation === "validateConstruction") return validateConstruction(context, options);
    throw new Error(`unknown construction operation: ${operation}`);
  }
  return __toCommonJS(bridge_exports);
})();
