schema_version: 2
band_id: dwarf-rangers
profiles:
- id: runesmith
  name: Runesmith
  type: hero
  cost: 85
  experience: 20
  characteristics:
    M: 3
    WS: 5
    BS: 4
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 10
  equipment_lists:
  - dwarf-warrior-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - shooting
  - academic
  - strength
  - special
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 1 Runesmith
    url: https://mordheimer.net/docs/warbands/grade-1b-warbands/dwarf-rangers
  source_path:
  - heroes
  - 1 Runesmith
  name_i18n:
    en: Runesmith
    es: null
  rule_ids:
  - runesmith--leader
  - runesmith--inscribe-runes
  combat_traits: {}
- id: apprentice-runesmith
  name: Apprentice Runesmith
  type: hero
  cost: 40
  experience: 0
  characteristics:
    M: 3
    WS: 3
    BS: 2
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 8
  equipment_lists:
  - dwarf-warrior-equipment-list
  fixed_equipment: []
  equipment_restrictions:
  - May select weapons from the Dwarf Warrior Equipment List, but the profile entry does not allow armour.
  skill_access:
  - combat
  - academic
  - strength
  - special
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0 – 1 Apprentice Runesmith
    url: https://mordheimer.net/docs/warbands/grade-1b-warbands/dwarf-rangers
  source_path:
  - heroes
  - 0 – 1 Apprentice Runesmith
  name_i18n:
    en: Apprentice Runesmith
    es: null
  rule_ids:
  - apprentice-runesmith--extra-set-of-hands
  combat_traits: {}
- id: dwarf-troll-slayers
  name: Dwarf Troll Slayers
  type: hero
  cost: 50
  experience: 8
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - dwarf-warrior-equipment-list
  fixed_equipment: []
  equipment_restrictions:
  - May select weapons from the Dwarf Warrior Equipment List.
  - May never carry or use missile weapons or any form of armour.
  skill_access:
  - combat
  - strength
  - special
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0 – 2 Dwarf Troll Slayers
    url: https://mordheimer.net/docs/warbands/grade-1b-warbands/dwarf-rangers
  source_path:
  - heroes
  - 0 – 2 Dwarf Troll Slayers
  name_i18n:
    en: Dwarf Troll Slayers
    es: null
  rule_ids:
  - dwarf-troll-slayers--deathwish
  combat_traits: {}
- id: dwarf-longbeards
  name: Dwarf Longbeards
  type: henchman
  cost: 50
  experience: 0
  characteristics:
    M: 3
    WS: 5
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 3
    A: 1
    Ld: 9
  equipment_lists:
  - dwarf-warrior-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0 – 5 Dwarf Longbeards
    url: https://mordheimer.net/docs/warbands/grade-1b-warbands/dwarf-rangers
  source_path:
  - henchmen
  - 0 – 5 Dwarf Longbeards
  name_i18n:
    en: Dwarf Longbeards
    es: null
  rule_ids:
  - dwarf-longbeards--stubborn
  combat_traits: {}
- id: dwarf-clansmen
  name: Dwarf Clansmen
  type: henchman
  cost: 40
  experience: 0
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - dwarf-warrior-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: mordheimer.net
    printed_page: 0
    section: Dwarf Clansmen
    url: https://mordheimer.net/docs/warbands/grade-1b-warbands/dwarf-rangers
  source_path:
  - henchmen
  - Dwarf Clansmen
  name_i18n:
    en: Dwarf Clansmen
    es: null
  rule_ids: []
  combat_traits: {}
- id: dwarf-crossbowmen
  name: Dwarf Crossbowmen
  type: henchman
  cost: 40
  experience: 0
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - crossbowmen-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0 – 5 Dwarf Crossbowmen
    url: https://mordheimer.net/docs/warbands/grade-1b-warbands/dwarf-rangers
  source_path:
  - henchmen
  - 0 – 5 Dwarf Crossbowmen
  name_i18n:
    en: Dwarf Crossbowmen
    es: null
  rule_ids: []
  combat_traits: {}
- id: beardlings
  name: Beardlings
  type: henchman
  cost: 25
  experience: 0
  characteristics:
    M: 3
    WS: 3
    BS: 2
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 8
  equipment_lists:
  - dwarf-warrior-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: mordheimer.net
    printed_page: 0
    section: Beardlings
    url: https://mordheimer.net/docs/warbands/grade-1b-warbands/dwarf-rangers
  source_path:
  - henchmen
  - Beardlings
  name_i18n:
    en: Beardlings
    es: null
  rule_ids: []
  combat_traits: {}
