schema_version: 2
band_id: sons-of-hashut
profiles:
- id: apprentice-sorcerer
  name: Apprentice Sorcerer
  type: hero
  cost: 85
  experience: 20
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 3
    A: 1
    Ld: 9
  equipment_lists:
  - chaos-dwarf-equipment-list
  fixed_equipment: []
  equipment_restrictions:
  - May select weapons and armour from the Chaos Dwarf Equipment List, but may not cast spells while wearing
    armour.
  skill_access:
  - combat
  - academic
  - special
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 1 Apprentice Sorcerer
    url: https://mordheimer.net/docs/warbands/grade-1c-warbands/sons-of-hashut
  source_path:
  - Heroes
  - 1 Apprentice Sorcerer
  name_i18n:
    en: Apprentice Sorcerer
    es: Hechicero aprendiz
  rule_ids:
  - apprentice-sorcerer--leader
  - apprentice-sorcerer--rituals-of-chaos
  combat_traits: {}
- id: bull-centaur
  name: Bull Centaur
  type: hero
  cost: 75
  experience: 12
  characteristics:
    M: 7
    WS: 4
    BS: 3
    S: 4
    T: 4
    W: 1
    I: 3
    A: 2
    Ld: 9
  equipment_lists:
  - chaos-dwarf-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - strength
  - special
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0 – 1 Bull Centaur
    url: https://mordheimer.net/docs/warbands/grade-1c-warbands/sons-of-hashut
  source_path:
  - Heroes
  - 0 – 1 Bull Centaur
  name_i18n:
    en: Bull Centaur
    es: Centauro toro
  rule_ids:
  - bull-centaur--large-target
  combat_traits: {}
- id: chaos-dwarf-champions
  name: Chaos Dwarf Champions
  type: hero
  cost: 50
  experience: 8
  characteristics:
    M: 3
    WS: 5
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - chaos-dwarf-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - shooting
  - strength
  - special
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0 – 2 Chaos Dwarf Champions
    url: https://mordheimer.net/docs/warbands/grade-1c-warbands/sons-of-hashut
  source_path:
  - Heroes
  - 0 – 2 Chaos Dwarf Champions
  name_i18n:
    en: Chaos Dwarf Champions
    es: Campeones Enanos del Caos
  rule_ids: []
  combat_traits: {}
- id: chaos-dwarf-warriors
  name: Chaos Dwarf Warriors
  type: henchman
  cost: 40
  experience: 0
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - chaos-dwarf-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0 – 6 Chaos Dwarf Warriors
    url: https://mordheimer.net/docs/warbands/grade-1c-warbands/sons-of-hashut
  source_path:
  - Henchmen
  - 0 – 6 Chaos Dwarf Warriors
  name_i18n:
    en: Chaos Dwarf Warriors
    es: Guerreros Enanos del Caos
  rule_ids: []
  combat_traits: {}
- id: blunderbuss-chaos-dwarfs
  name: Blunderbuss Chaos Dwarfs
  type: henchman
  cost: 40
  experience: 0
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - blunderbusser-equipment-list
  fixed_equipment: []
  equipment_restrictions:
  - Starting equipment for a Blunderbuss Chaos Dwarf must include a Chaos Dwarf Blunderbuss from the Blunderbusser
    Equipment List.
  skill_access: []
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 0 – 3 Blunderbuss Chaos Dwarfs
    url: https://mordheimer.net/docs/warbands/grade-1c-warbands/sons-of-hashut
  source_path:
  - Henchmen
  - 0 – 3 Blunderbuss Chaos Dwarfs
  name_i18n:
    en: Blunderbuss Chaos Dwarfs
    es: Enanos del Caos con trompos
  rule_ids: []
  combat_traits: {}
- id: hobgoblins
  name: Hobgoblins
  type: henchman
  cost: 15
  experience: 0
  characteristics:
    M: 4
    WS: 2
    BS: 3
    S: 3
    T: 3
    W: 1
    I: 3
    A: 1
    Ld: 6
  equipment_lists:
  - hobgoblin-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: mordheimer.net
    printed_page: 0
    section: 4+ Hobgoblins
    url: https://mordheimer.net/docs/warbands/grade-1c-warbands/sons-of-hashut
  source_path:
  - Henchmen
  - 4+ Hobgoblins
  name_i18n:
    en: Hobgoblins
    es: Hobgoblins
  rule_ids:
  - hobgoblins--skinny
  - hobgoblins--nobody-cares-about-them
  combat_traits: {}
