import type { CampaignDocument, KnowledgeReader, OpenPayload } from "../../../../domain/campaign/index";
import { withCampaign } from "../../../../domain/campaign/kernel/document";
import { applyInjuryOutcome } from "./injuries-workflow";

type CatalogueReader=KnowledgeReader&{list?(kind:string):readonly Readonly<Record<string,unknown>>[]};type Result={ok:true;document:CampaignDocument}|{ok:false;message:string};
function range(value:string,roll:number){const [low,high]=value.split("-").map(Number);return roll>=low&&roll<=(Number.isFinite(high)?high:low);}
function effects(row:Readonly<Record<string,unknown>>):OpenPayload[]{return Array.isArray(row["effects"])?row["effects"].map((value)=>{const effect=value as Record<string,unknown>;if(effect["type"]==="warrior.miss_games"&&typeof effect["games"]==="object")return{kind:"miss_games",value:Number((effect["games"] as Record<string,unknown>)["value"]??1)};if(effect["type"]==="warrior.characteristic_modifier")return{kind:"stat_modifier",stat:({movement:"M",weapon_skill:"WS",ballistic_skill:"BS",strength:"S",toughness:"T",wounds:"W",initiative:"I",attacks:"A",leadership:"Ld"} as Record<string,string>)[String(effect["characteristic"])]??String(effect["characteristic"]),value:Number(effect["modifier"])};if(effect["type"]==="warrior.add_condition")return{kind:"add_condition",condition_id:String(effect["condition_id"])};return{...effect,kind:String(effect["type"]??"uninterpreted")};}):[];}
export function injuryFollowUpDice(reader:KnowledgeReader,follow:OpenPayload):readonly [number,number]|null{const injury=(reader as CatalogueReader).list?.("injury")?.find((row)=>row["id"]===follow["result_id"]),resolution=injury?.["resolution"] as OpenPayload|undefined,dice=resolution?.["dice"] as OpenPayload|undefined;if(!resolution||!dice)return null;const count=Number(dice["count"]??1),sides=Number(dice["sides"]??6);return Number.isInteger(count)&&Number.isInteger(sides)&&count>0&&sides>1?[count,sides]:null;}
export function resolveInjuryTableFollowUp(document:CampaignDocument,reader:KnowledgeReader,input:{follow_up_id:string;roll:number}):Result{const post=document.campaign.post_battles.find((row)=>!row.complete),follow=post?.pending_follow_ups?.find((row)=>row["id"]===input.follow_up_id&&(row["type"]==="injury_roll"||row["type"]==="injury_followup")),warrior=document.campaign.warriors.find((row)=>row.id===follow?.["warrior_id"]);if(!post||!follow||!warrior)return{ok:false,message:"Unknown injury follow-up."};const dice=injuryFollowUpDice(reader,follow);if(!dice)return{ok:false,message:"This injury follow-up has no supported KB table."};const roll=Math.trunc(input.roll),[count,sides]=dice;if(!Number.isInteger(roll)||roll<count||roll>count*sides||(count===2&&sides===6&&(!range("11-66",roll)||roll%10===0||roll%10>6)))return{ok:false,message:"Use a valid result for this injury table."};const rows=(reader as CatalogueReader).list?.("injury")??[],source=rows.find((row)=>row["id"]===follow["result_id"]),resolution=source?.["resolution"] as OpenPayload|undefined;let outcome:Readonly<Record<string,unknown>>|undefined;if(resolution?.["type"]==="roll_table")outcome=((resolution["branches"]??[]) as readonly Readonly<Record<string,unknown>>[]).find((row)=>range(String((row["when"] as OpenPayload|undefined)?.["min"]??0)+"-"+String((row["when"] as OpenPayload|undefined)?.["max"]??(row["when"] as OpenPayload|undefined)?.["min"]??0),roll));else if(resolution?.["type"]==="repeat_table"){const excluded=new Set((resolution["reroll_ids"]??[]) as readonly string[]);outcome=rows.find((row)=>row["applies_to"]===(follow["table"]??warrior.kind)&&range(String(row["roll"]??""),roll)&&!excluded.has(String(row["id"])));}if(!outcome)return{ok:false,message:"That roll requires another reroll."};const applied=applyInjuryOutcome(document,{warrior_id:warrior.id,result_id:String(outcome["id"]??"injury-followup"),result:String(outcome["result"]??"Resolved injury"),effects:effects(outcome)});if(!applied.ok)return{ok:false,message:applied.message};const changed=applied.document.campaign.post_battles.find((row)=>row.battle_number===post.battle_number)!;return{ok:true,document:withCampaign(applied.document,{...applied.document.campaign,post_battles:applied.document.campaign.post_battles.map((row)=>row===changed?{...changed,pending_follow_ups:(changed.pending_follow_ups??[]).filter((item)=>item["id"]!==follow["id"]),event_log:[...(changed.event_log??[]),{step:0,type:"injury_followup",warrior_id:warrior.id,description:`${warrior.name}: ${String(outcome["result"]??"injury resolved")}`}]}:row)})};}
