import type { CampaignDocument, OpenPayload } from "../../../../domain/campaign/index";
import { currentState, withCampaign } from "../../../../domain/campaign/kernel/document";

type Result={ok:true;document:CampaignDocument}|{ok:false;message:string};
function follow(document:CampaignDocument,id:string,type:string){const post=document.campaign.post_battles.find((row)=>!row.complete),row=post?.pending_follow_ups?.find((item)=>item["id"]===id&&item["type"]===type),warrior=document.campaign.warriors.find((item)=>item.id===row?.["warrior_id"]);return{post,row,warrior};}
function close(document:CampaignDocument,post:NonNullable<ReturnType<typeof follow>["post"]>,row:OpenPayload,description:string,warriors=document.campaign.warriors,extra:Partial<CampaignDocument["campaign"]>={},removedWarriorId?:string){const changed={...post,pending_follow_ups:(post.pending_follow_ups??[]).filter((item)=>item!==row&&(!removedWarriorId||item["warrior_id"]!==removedWarriorId)),pending_advances:removedWarriorId?(post.pending_advances??[]).filter((item)=>item["warrior_id"]!==removedWarriorId||item["committed"]):post.pending_advances,equipment_obligations:removedWarriorId?(post.equipment_obligations??[]).filter((item)=>item["warrior_id"]!==removedWarriorId):post.equipment_obligations,searches:removedWarriorId?Object.fromEntries(Object.entries(post.searches??{}).filter(([id])=>id!==removedWarriorId)):post.searches,event_log:[...(post.event_log??[]),{step:0,type:"injury_decision",description}]};return withCampaign(document,{...document.campaign,...extra,warriors,post_battles:document.campaign.post_battles.map((item)=>item===post?changed:item)});}
function discardCarried(document:CampaignDocument,warrior:CampaignDocument["campaign"]["warriors"][number]) { const lost=new Map<string,number>(); for(const item of warrior.equipment)if(item.transferable!==false)lost.set(item.item_id,(lost.get(item.item_id)??0)+item.quantity); return document.campaign.inventory.map((item)=>{const quantity=lost.get(item.id)??0;return quantity?{...item,owned:Math.max(0,item.owned-quantity),equipped:Math.max(0,item.equipped-quantity),stash:Math.max(0,item.stash-quantity)}:item;}).filter((item)=>item.owned>0); }

export function resolveEyeInjury(document:CampaignDocument,input:{follow_up_id:string;eye:string}):Result {const {post,row,warrior}=follow(document,input.follow_up_id,"eye_injury");if(!post||!row||!warrior)return{ok:false,message:"Unknown eye-injury follow-up."};const eye=input.eye.toLowerCase(),eyes=warrior.lost_eyes??[];if(!["left","right"].includes(eye)||eyes.includes(eye))return{ok:false,message:"Choose the warrior's remaining eye."};const updated={...warrior,lost_eyes:[...eyes,eye]};const retire=updated.lost_eyes.length>=2;return{ok:true,document:close(document,post,row,retire?`${warrior.name} lost the remaining eye and retires.`:`${warrior.name} lost the ${eye} eye.`,retire?document.campaign.warriors.filter((item)=>item.id!==warrior.id):document.campaign.warriors.map((item)=>item.id===warrior.id?updated:item),retire?{inventory:discardCarried(document,warrior)}:{},retire?warrior.id:undefined)};}
export function resolveHatred(document:CampaignDocument,input:{follow_up_id:string;target:string}):Result {const {post,row,warrior}=follow(document,input.follow_up_id,"relationship"),target=input.target.trim();if(!post||!row||!warrior)return{ok:false,message:"Unknown Bitter Enmity follow-up."};if(!target)return{ok:false,message:"Enter the warrior, warband, or warband type hated."};const changed={...warrior,hatreds:[...new Set([...(warrior.hatreds??[]),target])]};return{ok:true,document:close(document,post,row,`${warrior.name} permanently hates ${target}.`,document.campaign.warriors.map((item)=>item.id===warrior.id?changed:item))};}
export function resolvePrisoner(document:CampaignDocument,input:{follow_up_id:string;resolution:string;ransom?:number;disposition?:string}):Result {const {post,row,warrior}=follow(document,input.follow_up_id,"prisoner");if(!post||!row||!warrior)return{ok:false,message:"Unknown captured-warrior follow-up."};const resolution=input.resolution,ransom=Math.max(0,Math.trunc(input.ransom??0));if(resolution==="ransom"){const gold=(currentState(document)?.gold??0)+(post.gold_delta??0);if(ransom>gold)return{ok:false,message:`The warband cannot pay a ransom of ${ransom} gc.`};const changed={...post,gold_delta:(post.gold_delta??0)-ransom,pending_follow_ups:(post.pending_follow_ups??[]).filter((item)=>item!==row),event_log:[...(post.event_log??[]),{step:0,type:"captured",description:`${warrior.name} was ransomed for ${ransom} gc.`}]};return{ok:true,document:withCampaign(document,{...document.campaign,post_battles:document.campaign.post_battles.map((item)=>item===post?changed:item)})};}if(resolution==="exchange")return{ok:true,document:close(document,post,row,`${warrior.name} was exchanged or released and returns with all equipment.`)};if(resolution!=="lost")return{ok:false,message:"Choose ransom, exchange, or permanent loss."};const disposition=input.disposition??"other";if(!["enslaved","executed","zombie","sacrificed","other"].includes(disposition))return{ok:false,message:"Choose what happened to the captured warrior."};const labels:Record<string,string>={enslaved:"sold into slavery",executed:"executed",zombie:"raised as a Zombie",sacrificed:"sacrificed",other:"otherwise permanently lost"};return{ok:true,document:close(document,post,row,`${warrior.name} was ${labels[disposition]}.`,document.campaign.warriors.filter((item)=>item.id!==warrior.id),{inventory:discardCarried(document,warrior)},warrior.id)};}
