import type { CampaignDocument, KnowledgeReader, OpenPayload } from "../../../../domain/campaign/index";
import { withCampaign } from "../../../../domain/campaign/kernel/document";
import { applyInjuryOutcome, type InjuryEffect } from "./injuries-workflow";

type Result={ok:true;document:CampaignDocument}|{ok:false;message:string};
type CatalogueReader=KnowledgeReader&{list?(kind:string):readonly Readonly<Record<string,unknown>>[]};
function effects(row:Readonly<Record<string,unknown>>):InjuryEffect[]{return Array.isArray(row["effects"])?row["effects"].map((value)=>{const effect=value as OpenPayload;if(effect["type"]==="warrior.miss_games"&&typeof effect["games"]==="object")return{kind:"miss_games",value:Number((effect["games"] as OpenPayload)["value"]??1)};if(effect["type"]==="warrior.characteristic_modifier")return{kind:"stat_modifier",stat:({movement:"M",weapon_skill:"WS",ballistic_skill:"BS",strength:"S",toughness:"T",wounds:"W",initiative:"I",attacks:"A",leadership:"Ld"} as Record<string,string>)[String(effect["characteristic"])]??String(effect["characteristic"]),value:Number(effect["modifier"])};if(effect["type"]==="warrior.add_condition")return{kind:"add_condition",condition_id:String(effect["condition_id"])};return{kind:"follow_up",type:String(effect["type"]??"uninterpreted"),payload:effect};}):[];}
function close(document:CampaignDocument,follow:OpenPayload,description:string,warriors=document.campaign.warriors,gold=0):CampaignDocument{const post=document.campaign.post_battles.find((item)=>!item.complete)!;const changed={...post,gold_delta:(post.gold_delta??0)+gold,pending_follow_ups:(post.pending_follow_ups??[]).filter((item)=>item!==follow),event_log:[...(post.event_log??[]),{step:0,type:"sold_to_pits",warrior_id:follow["warrior_id"],description}]};return withCampaign(document,{...document.campaign,warriors,post_battles:document.campaign.post_battles.map((item)=>item===post?changed:item)});}

/** Desktop `resolve_sold_to_pits`: win grants 50gc/2XP; loss applies a D66 injury then loses carried weapons and armour. */
export function resolveSoldToPits(document:CampaignDocument,reader:KnowledgeReader,input:{follow_up_id:string;won:boolean;injury_roll?:number}):Result {const post=document.campaign.post_battles.find((item)=>!item.complete),follow=post?.pending_follow_ups?.find((item)=>item["id"]===input.follow_up_id&&item["type"]==="encounter"&&item["encounter_id"]==="campaign.encounter.sold-to-the-pits"),warrior=document.campaign.warriors.find((item)=>item.id===follow?.["warrior_id"]);if(!post||!follow||!warrior)return{ok:false,message:"Unknown Sold to the Pits encounter."};if(input.won){const warriors=document.campaign.warriors.map((item)=>item.id===warrior.id?{...item,experience:item.experience+2}:item);return{ok:true,document:close(document,follow,`${warrior.name} wins in the pits: +50 gc and +2 Experience.`,warriors,50)};}const roll=Math.trunc(input.injury_roll??0),tens=Math.trunc(roll/10),ones=roll%10;if(tens<1||tens>6||ones<1||ones>6)return{ok:false,message:"A valid D66 result is required after losing in the pits."};let staged=document;if(roll<=35){const injury=(reader as CatalogueReader).list?.("injury")?.find((item)=>item["applies_to"]==="hero"&&(() => {const [low,high]=String(item["roll"]??"").split("-").map(Number);return roll>=low&&roll<=((Number.isFinite(high)?high:low));})());if(!injury)return{ok:false,message:"The serious-injury table has no result for this roll."};const applied=applyInjuryOutcome(document,{warrior_id:warrior.id,result_id:String(injury["id"]),result:String(injury["result"]),effects:effects(injury)});if(!applied.ok)return{ok:false,message:applied.message};staged=applied.document;}const current=staged.campaign.warriors.find((item)=>item.id===warrior.id);if(!current)return{ok:true,document:close(staged,follow,`${warrior.name} loses in the pits (${roll}) and leaves the warband.`)};const inventoryById=new Map(staged.campaign.inventory.map((item)=>[item.id,item]));const lost=current.equipment.filter((item)=>{const category=inventoryById.get(item.item_id)?.category.toLowerCase()??"";return /weapon|armour|armor/.test(category);});const lostIds=new Map<string,number>();for(const item of lost)if(item.transferable!==false)lostIds.set(item.item_id,(lostIds.get(item.item_id)??0)+item.quantity);const updatedWarrior={...current,equipment:current.equipment.filter((item)=>!lost.includes(item))};const inventory=staged.campaign.inventory.map((item)=>{const quantity=lostIds.get(item.id)??0;return quantity?{...item,owned:Math.max(0,item.owned-quantity),equipped:Math.max(0,item.equipped-quantity),stash:Math.max(0,item.stash-quantity)}:item;}).filter((item)=>item.owned>0);const after={...staged,campaign:{...staged.campaign,inventory,warriors:staged.campaign.warriors.map((item)=>item.id===current.id?updatedWarrior:item)}};return{ok:true,document:close(after,follow,`${warrior.name} loses in the pits (${roll}); lost equipment: ${lost.map((item)=>item.name).join(", ")||"none"}.`)};}
