import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";

/** Existing henchman groups may recruit one veteran at a time. */
export function GroupRecruitmentPanel({document,locale="en"}:{readonly document:CampaignDocument;readonly locale?:"es"|"en"}) {
  const app=useCampaignApp(); const post=document.campaign.post_battles.find((row)=>!row.complete); if(!post)return null;
  const ready=Boolean((post.step_state?.["veterans"] as Record<string,unknown>|undefined)?.["resolved"]);
  const groups=document.campaign.warriors.filter((row)=>row.kind==="henchman"); const individual=document.campaign.warriors.filter((row)=>row.kind!=="henchman");
  const t=locale==="es"?{title:"07 · Reclutamiento",wait:"Resuelve primero los veteranos disponibles.",empty:"No hay grupos de secuaces que ampliar.",pool:"PX de veterano disponibles",add:"Reclutar un miembro",xp:"PX",cost:"Coste base",dismissOne:"Retirar un miembro",dismiss:"Licenciar",individual:"Guerreros individuales",group:"Grupo",action:"Acción"}:{title:"07 · Recruitment",wait:"Resolve available veterans first.",empty:"No henchman groups can be expanded.",pool:"Veteran XP available",add:"Recruit one member",xp:"XP",cost:"Base cost",dismissOne:"Dismiss one member",dismiss:"Dismiss",individual:"Individual warriors",group:"Group",action:"Action"};
  return <section aria-label={locale === "es" ? "Reclutamiento de grupos" : "Group recruitment"}><h3>{t.title}</h3>{!ready?<p role="status">{t.wait}</p>:<><p>{t.pool}: {post.veteran_pool??0}</p>{groups.length===0?<p>{t.empty}</p>:<table><thead><tr><th>{t.group}</th><th>{t.xp}</th><th>{t.cost}</th><th>{t.action}</th></tr></thead><tbody>{groups.map((group)=><tr key={group.id}><td>{group.name} · {group.quantity??1}</td><td>{group.experience}</td><td>{group.cost} gc</td><td><button onClick={()=>void app.runAction("recruitGroupMember",{warrior_id:group.id})}>{t.add}</button>{(group.quantity??1)>1&&<button onClick={()=>void app.runAction("dismissRecruit",{warrior_id:group.id,one_member:true})}>{t.dismissOne}</button>}<button onClick={()=>void app.runAction("dismissRecruit",{warrior_id:group.id})}>{t.dismiss}</button></td></tr>)}</tbody></table>}{individual.length>0&&<><h4>{t.individual}</h4><ul>{individual.map((warrior)=><li key={warrior.id}>{warrior.name} <button onClick={()=>void app.runAction("dismissRecruit",{warrior_id:warrior.id})}>{t.dismiss}</button></li>)}</ul></>}</>}</section>;
}
