import type { CampaignDocument } from "../campaign/types";
import { resourceAmount } from "../campaign/displayText";
import { useCampaignApp } from "../campaign/useCampaignApp";

/** Unified management for every warrior already in the warband. */
export function GroupRecruitmentPanel({document,locale="en"}:{readonly document:CampaignDocument;readonly locale?:"es"|"en"}) {
  const app=useCampaignApp(); const post=document.campaign.post_battles.find((row)=>!row.complete); if(!post)return null;
  const ready=Boolean((post.step_state?.["veterans"] as Record<string,unknown>|undefined)?.["resolved"]);
  const isLeader=(warrior:CampaignDocument["campaign"]["warriors"][number])=>warrior.kind==="hero"&&warrior.skills.some((rule)=>(/(^|--|\.)leader$/i).test(String(rule)));
  const warriors=[...document.campaign.warriors].sort((a,b)=>Number(isLeader(b))-Number(isLeader(a))||a.name.localeCompare(b.name,locale));
  const upkeep=new Map((post.pending_follow_ups??[]).filter((row)=>row["type"]==="hireling_upkeep").map((row)=>[String(row["warrior_id"]),row]));
  const t=locale==="es"?{title:"07 · Reclutamiento",wait:"Resuelve primero los veteranos disponibles.",empty:"La banda no tiene miembros.",pool:"PX de veterano disponibles",member:"Miembro",type:"Tipo",quantity:"Cantidad",xp:"PX",cost:"Coste / mantenimiento",action:"Acción",group:"Grupo de secuaces",hero:"Héroe",hireling:"Espada de alquiler",add:"Reclutar un miembro",dismissOne:"Retirar un miembro",dismiss:"Licenciar",pay:"Pagar",leave:"Dejar marchar"}:{title:"07 · Recruitment",wait:"Resolve available veterans first.",empty:"The warband has no members.",pool:"Veteran XP available",member:"Member",type:"Type",quantity:"Quantity",xp:"XP",cost:"Cost / upkeep",action:"Action",group:"Henchman group",hero:"Hero",hireling:"Hired Sword",add:"Recruit one member",dismissOne:"Dismiss one member",dismiss:"Dismiss",pay:"Pay",leave:"Let leave"};
  const costs=(row:Record<string,unknown>)=>(Array.isArray(row["costs"])?row["costs"]:[]).filter(Array.isArray).map((cost)=>resourceAmount(cost[0],cost[1],locale)).join(" + ");
  return <section aria-label={locale === "es" ? "Personal de la banda" : "Warband members"}><h3>{t.title}</h3>{!ready?<p role="status">{t.wait}</p>:<><p>{t.pool}: {post.veteran_pool??0}</p>{warriors.length===0?<p>{t.empty}</p>:<table className="mobile-cards"><caption>{locale==="es"?"Personal de la banda":"Warband members"}</caption><thead><tr><th>{t.member}</th><th>{t.type}</th><th>{t.quantity}</th><th>{t.xp}</th><th>{t.cost}</th><th>{t.action}</th></tr></thead><tbody>{warriors.map((warrior)=>{const pending=upkeep.get(warrior.id);return <tr key={warrior.id}><td data-label={t.member}>{warrior.name}</td><td data-label={t.type}>{warrior.kind==="henchman"?t.group:warrior.kind==="hireling"?t.hireling:t.hero}</td><td data-label={t.quantity}>{warrior.quantity??1}</td><td data-label={t.xp}>{warrior.experience}</td><td data-label={t.cost}>{pending?costs(pending):warrior.kind==="henchman"?`${warrior.cost} gc`:"—"}</td><td data-label={t.action}>{warrior.kind==="henchman"&&<button onClick={()=>void app.runAction("recruitGroupMember",{warrior_id:warrior.id})}>{t.add}</button>}{warrior.kind==="hireling"&&pending?<><button className="primary" onClick={()=>void app.runAction("resolveHirelingUpkeep",{follow_up_id:pending["id"],pay:true})}>{t.pay}</button><button onClick={()=>void app.runAction("resolveHirelingUpkeep",{follow_up_id:pending["id"],pay:false})}>{t.leave}</button></>:<>{warrior.kind==="henchman"&&(warrior.quantity??1)>1&&<button onClick={()=>void app.runAction("dismissRecruit",{warrior_id:warrior.id,one_member:true})}>{t.dismissOne}</button>}<button onClick={()=>void app.runAction("dismissRecruit",{warrior_id:warrior.id})}>{t.dismiss}</button></>}</td></tr>;})}</tbody></table>}</>}</section>;
}
