import { warriorPersonalName, textJoin, textNumber, textSymbol } from "../campaign/presentation-values";
import { presentationOutput } from "../campaign/presentation-output";
import { translate } from "../campaign/i18n-core";
import { useLocale } from "../campaign/i18n-context";
import type { CampaignDocument } from "../campaign/types";
import { resourceAmount } from "../campaign/displayText";
import { useCampaignApp } from "../campaign/useCampaignApp";

/** Unified management for every warrior already in the warband. */
export function GroupRecruitmentPanel({document,locale: requestedLocale}:{readonly document:CampaignDocument;readonly locale?:"es"|"en"}) {
  const locale = useLocale(requestedLocale);
  const app=useCampaignApp(); const post=document.campaign.post_battles.find((row)=>!row.complete); if(!post)return null;
  const ready=Boolean((post.step_state?.["veterans"] as Record<string,unknown>|undefined)?.["resolved"]);
  const isLeader=(warrior:CampaignDocument["campaign"]["warriors"][number])=>warrior.kind==="hero"&&warrior.skills.some((rule)=>(/(^|--|\.)leader$/i).test(String(rule)));
  const warriors=[...document.campaign.warriors].sort((a,b)=>Number(isLeader(b))-Number(isLeader(a))||a.name.localeCompare(b.name,locale));
  const upkeep=new Map((post.pending_follow_ups??[]).filter((row)=>row["type"]==="hireling_upkeep").map((row)=>[String(row["warrior_id"]),row]));
  const t=({ title: translate({ key: "ui.605988653c2c" }, locale), wait: translate({ key: "ui.7b1092ca7178" }, locale), empty: translate({ key: "ui.618a731477d0" }, locale), pool: translate({ key: "ui.83c2cd1e23cf" }, locale), member: translate({ key: "ui.92a1381c2819" }, locale), type: translate({ key: "ui.94f1d228df1f" }, locale), quantity: translate({ key: "ui.8f2846965a7a" }, locale), xp: translate({ key: "ui.fb309c6e7256" }, locale), cost: translate({ key: "ui.04cfd1450459" }, locale), action: translate({ key: "ui.b9a0db2ec300" }, locale), group: translate({ key: "ui.ab7904956cd6" }, locale), hero: translate({ key: "ui.34dc1a21c0f8" }, locale), hireling: translate({ key: "ui.960b575d21e7" }, locale), add: translate({ key: "ui.50fa5dbf4f66" }, locale), dismissOne: translate({ key: "ui.0a81642728f7" }, locale), dismiss: translate({ key: "ui.78090120c578" }, locale), pay: translate({ key: "ui.8826dd3f8e40" }, locale), leave: translate({ key: "ui.9d4da9224528" }, locale) });
  const costs=(row:Record<string,unknown>)=>textJoin((Array.isArray(row["costs"])?row["costs"]:[]).filter(Array.isArray).map((cost)=>resourceAmount(cost[0],cost[1],locale)), " + ");
  return <section aria-label={presentationOutput(translate({ key: "ui.059d0c76ac53" }, locale))}><h3>{presentationOutput(t.title)}</h3>{!ready?<p role="status">{presentationOutput(t.wait)}</p>:<><p>{presentationOutput(t.pool)} {presentationOutput(textSymbol(":"))} {presentationOutput(textNumber(post.veteran_pool??0, locale))}</p>{warriors.length===0?<p>{presentationOutput(t.empty)}</p>:<table className="mobile-cards"><caption>{presentationOutput(translate({ key: "ui.059d0c76ac53" }, locale))}</caption><thead><tr><th>{presentationOutput(t.member)}</th><th>{presentationOutput(t.type)}</th><th>{presentationOutput(t.quantity)}</th><th>{presentationOutput(t.xp)}</th><th>{presentationOutput(t.cost)}</th><th>{presentationOutput(t.action)}</th></tr></thead><tbody>{warriors.map((warrior)=>{const pending=upkeep.get(warrior.id);return <tr key={warrior.id}><td data-label={presentationOutput(t.member)}>{presentationOutput(warriorPersonalName(warrior, locale))}</td><td data-label={presentationOutput(t.type)}>{presentationOutput(warrior.kind==="henchman"?t.group:warrior.kind==="hireling"?t.hireling:t.hero)}</td><td data-label={presentationOutput(t.quantity)}>{presentationOutput(textNumber(warrior.quantity??1, locale))}</td><td data-label={presentationOutput(t.xp)}>{presentationOutput(textNumber(warrior.experience, locale))}</td><td data-label={presentationOutput(t.cost)}>{presentationOutput(pending?costs(pending):warrior.kind==="henchman"?textJoin([textNumber(warrior.cost, locale), translate({ key: "unit.gold" }, locale)]):textSymbol("—"))}</td><td data-label={presentationOutput(t.action)}>{warrior.kind==="henchman"&&<button onClick={()=>void app.runAction("recruitGroupMember",{warrior_id:warrior.id})}>{presentationOutput(t.add)}</button>}{warrior.kind==="hireling"&&pending?<><button className="primary" onClick={()=>void app.runAction("resolveHirelingUpkeep",{follow_up_id:pending["id"],pay:true})}>{presentationOutput(t.pay)}</button><button onClick={()=>void app.runAction("resolveHirelingUpkeep",{follow_up_id:pending["id"],pay:false})}>{presentationOutput(t.leave)}</button></>:<>{warrior.kind==="henchman"&&(warrior.quantity??1)>1&&<button onClick={()=>void app.runAction("dismissRecruit",{warrior_id:warrior.id,one_member:true})}>{presentationOutput(t.dismissOne)}</button>}<button onClick={()=>void app.runAction("dismissRecruit",{warrior_id:warrior.id})}>{presentationOutput(t.dismiss)}</button></>}</td></tr>;})}</tbody></table>}</>}</section>;
}
