import { useState } from "react";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";
import { NumberStepper } from "../common/NumberStepper";

export function RecruitProfilePanel({document,knowledge,locale="en"}:{readonly document:CampaignDocument;readonly knowledge:ArtefactKnowledgeReader;readonly locale?:"es"|"en"}) {
  const app=useCampaignApp(); const post=document.campaign.post_battles.find((row)=>!row.complete); const band=knowledge.queryKnowledge({id:{kind:"band_id",value:document.campaign.identity.band_id}}); const members=band.ok&&Array.isArray((band.record.data["roster"] as Record<string,unknown>|undefined)?.["members"])?(band.record.data["roster"] as Record<string,unknown>)["members"] as Record<string,unknown>[]:[]; const [profileId,setProfileId]=useState(""); const [quantity,setQuantity]=useState(1); const [name,setName]=useState(""); if(!post)return null;
  const offers=members.flatMap((member)=>{const id=String(member["profile_id"]??"");const profile=knowledge.queryKnowledge({id:{kind:"profile_id",value:id}});return profile.ok?[{id,name:profile.record.names[locale]??profile.record.names.en??id,kind:profile.record.data["type"],cost:Number(profile.record.data["cost"]??0)}]:[];}).sort((a,b)=>a.name.localeCompare(b.name,locale)); const selected=offers.find((offer)=>offer.id===profileId);
  const t=locale==="es"?{title:"Nuevos Reclutas",profile:"Perfil",name:"Nombre",quantity:"Cantidad",hire:"Reclutar",none:"No hay reclutas disponibles.",group:"Grupo"}:{title:"New Recruits",profile:"Profile",name:"Name",quantity:"Quantity",hire:"Recruit",none:"No recruits available.",group:"Group"};
  return <section aria-label={t.title}><h3>{t.title}</h3>{offers.length===0?<p>{t.none}</p>:<><label>{t.profile}<select value={profileId} onChange={(event)=>{setProfileId(event.target.value);setName("");}}><option value="">{locale==="es"?"Selecciona un perfil…":"Select a profile…"}</option>{offers.map((offer)=><option key={offer.id} value={offer.id}>{offer.name} · {offer.cost} gc</option>)}</select></label><label>{t.name}<input value={name} placeholder={selected?.kind==="hero"?selected?.name:`${selected?.name??""} ${t.group}`} onChange={(event)=>setName(event.target.value)}/></label>{selected&&selected.kind!=="hero"&&<div className="warrior-control-row"><span>{t.quantity}</span><NumberStepper label={t.quantity} value={quantity} min={1} onChange={setQuantity}/></div>}<button className="primary" disabled={!selected} data-disabled-reason={!selected ? (locale==="es"?"Selecciona un perfil de guerrero.":"Select a warrior profile.") : undefined} onClick={()=>selected&&void app.runAction("recruitBandProfile",{profile_id:selected.id,quantity:selected.kind==="hero"?1:quantity,name:name.trim()||undefined,locale})}>{t.hire}</button></>}</section>;
}
