import { textJoin, textNumber, textSymbol } from "../campaign/presentation-values";
import { presentationOutput } from "../campaign/presentation-output";
import { translate } from "../campaign/i18n-core";
import { useLocale } from "../campaign/i18n-context";
import { useState } from "react";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";
import { knowledgeName } from "../campaign/displayText";
import { NumberStepper } from "../common/NumberStepper";

export function RecruitProfilePanel({document,knowledge,locale: requestedLocale}:{readonly document:CampaignDocument;readonly knowledge:ArtefactKnowledgeReader;readonly locale?:"es"|"en"}) {
  const locale = useLocale(requestedLocale);
  const app=useCampaignApp(); const post=document.campaign.post_battles.find((row)=>!row.complete); const band=knowledge.queryKnowledge({id:{kind:"band_id",value:document.campaign.identity.band_id}}); const members=band.ok&&Array.isArray((band.record.data["roster"] as Record<string,unknown>|undefined)?.["members"])?(band.record.data["roster"] as Record<string,unknown>)["members"] as Record<string,unknown>[]:[]; const [profileId,setProfileId]=useState(""); const [quantity,setQuantity]=useState(1); const [name,setName]=useState(""); if(!post)return null;
  const offers=members.flatMap((member)=>{const id=String(member["profile_id"]??"");const profile=knowledge.queryKnowledge({id:{kind:"profile_id",value:id}});return profile.ok?[{id,name:knowledgeName(knowledge,"profile",id,locale),kind:profile.record.data["type"],cost:Number(profile.record.data["cost"]??0)}]:[];}).sort((a,b)=>a.name.localeCompare(b.name,locale)); const selected=offers.find((offer)=>offer.id===profileId);
  const t=({ title: translate({ key: "ui.ad6615d7b621" }, locale), profile: translate({ key: "ui.c0f38b97c8b9" }, locale), name: translate({ key: "ui.9b9a13d3e4d1" }, locale), quantity: translate({ key: "ui.8f2846965a7a" }, locale), hire: translate({ key: "ui.d6cf6004f926" }, locale), none: translate({ key: "ui.af20c50e64e8" }, locale), group: translate({ key: "ui.4984638918b7" }, locale) });
  return <section aria-label={presentationOutput(t.title)}><h3>{presentationOutput(t.title)}</h3>{offers.length===0?<p>{presentationOutput(t.none)}</p>:<><label>{presentationOutput(t.profile)}<select value={profileId} onChange={(event)=>{setProfileId(event.target.value);setName("");}}><option value="">{presentationOutput(translate({ key: "ui.9e5a2ffd017e" }, locale))}</option>{offers.map((offer)=><option key={offer.id} value={offer.id}>{presentationOutput(textJoin([offer.name, textJoin([textNumber(offer.cost, locale), translate({ key: "unit.gold" }, locale)])], " · "))}</option>)}</select></label><label>{presentationOutput(t.name)}<input value={name} placeholder={presentationOutput(selected?.kind==="hero" ? selected.name : textJoin([selected?.name ?? textSymbol(""), t.group]))} onChange={(event)=>setName(event.target.value)}/></label>{selected&&selected.kind!=="hero"&&<div className="warrior-control-row"><span>{presentationOutput(t.quantity)}</span><NumberStepper locale={locale} label={translate({ key: "number.quantity" }, locale)} value={quantity} min={1} onChange={setQuantity}/></div>}<button className="primary" disabled={!selected} data-disabled-reason={(!selected ? (translate({ key: "disabled.a5b46d0dc0" }, locale)) : undefined) === undefined ? undefined : presentationOutput((!selected ? (translate({ key: "disabled.a5b46d0dc0" }, locale)) : undefined)!)} onClick={()=>selected&&void app.runAction("recruitBandProfile",{profile_id:selected.id,quantity:selected.kind==="hero"?1:quantity,name:name.trim()||undefined,locale})}>{presentationOutput(t.hire)}</button></>}</section>;
}
