import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import "@testing-library/jest-dom/vitest";
import { describe, expect, it } from "vitest";

import { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import { createService } from "@src/features/campaign/default-deps";
import { knowledgeName, variantName } from "@src/features/campaign/displayText";
import { presentationOutput } from "@src/features/campaign/presentation-output";
import { CampaignAppProvider, localizeErrorMessage, useCampaignApp } from "@src/features/campaign/useCampaignApp";
import type { CampaignDocument } from "@src/features/campaign/types";
import { DraftWorkspace } from "@src/features/draft/DraftWorkspace";

import { freshArtefactPath, freshArtefactRaw } from "../../support/fresh-campaign-artefact";

const ES_VARIANT = "Ostermark";
const ES_PROFILE = "Campeones";

/**
 * T09 publishes a mandatory choice over a band: the roster marks the slot it
 * gates with `maximum: 0` and every published option declares the slots it
 * opens. This fixture mutates the produced artefact in place — the same rows
 * the presentation index resolves — so the interface is exercised against the
 * real reader, not a hand-written stub.
 *
 * It reads the **freshly generated** artefact, the same basis the campaign
 * obligations suite uses: the versioned `outputs/web-public/knowledge` file is
 * pre-T09 and is regenerated by T12.
 */
function knowledge() {
  const raw = freshArtefactRaw();
  const band = (raw["bands"] as { id: string; roster: { requires_variant_selection?: boolean; members: { profile_id: string; maximum: number | null }[] }; variants: { id: string; roster_members?: unknown }[] }[]).find((row) => row.id === "mercenaries")!;
  band.roster.requires_variant_selection = true;
  band.roster.members = band.roster.members.map((member: { profile_id: string; maximum: number | null }) =>
    member.profile_id === "champions" ? { ...member, maximum: 0 } : member);
  const marienburg = band.variants.find((option: { id: string }) => option.id === "marienburg")!;
  marienburg.roster_members = [{ profile_id: "champions", minimum: 0, maximum: 2 }];
  return ArtefactKnowledgeReader.from(raw);
}

/** The real product route: the browser service creates the draft and holds it. */
async function session(reader: ArtefactKnowledgeReader, variantId?: string) {
  const service = createService(reader);
  const created = await service.createCampaign({ band_id: "mercenaries", campaign_name: "Variant campaign", warband_name: "Mercenarios", ...(variantId ? { variant: variantId } : {}) });
  if (!created.ok) throw new Error(created.message);
  return { service, document: created.document as CampaignDocument };
}

/**
 * A campaign file written before T09: it carries no variant, so the interface
 * has to ask for the mandatory choice the domain now requires instead of
 * fabricating one. Round-trips through the v5 export/import route.
 */
async function legacySession(reader: ArtefactKnowledgeReader) {
  const source = createService(reader);
  const created = await source.createCampaign({ band_id: "mercenaries", campaign_name: "Variant campaign", warband_name: "Mercenarios", variant: "marienburg" });
  if (!created.ok) throw new Error(created.message);
  const exported = await source.prepareExport();
  if (!exported.ok || !exported.payload) throw new Error("export should succeed");
  const legacy = JSON.parse(exported.payload.text);
  legacy.campaign.identity.mercenary_variant = null;
  const service = createService(reader);
  const imported = await service.importCampaign({ text: JSON.stringify(legacy) });
  if (!imported.ok) throw new Error(imported.message);
  return { service, document: imported.document as CampaignDocument };
}

function renderDraft(service: { current: unknown }, document: CampaignDocument, reader: ArtefactKnowledgeReader, locale: "es" | "en") {
  return render(
    <CampaignAppProvider
      service={service as never}
      locale={locale}
      profileName={(id) => knowledgeName(reader, "profile", id, locale, undefined, document.campaign.identity.band_id)}
      bandName={(id) => knowledgeName(reader, "band", id, locale)}
      variantName={(band, variant) => variantName(reader, band, variant, locale)}
    >
      <DraftWorkspace document={document} knowledge={reader} locale={locale} />
    </CampaignAppProvider>,
  );
}

async function openRosterDialog(locale: "es" | "en") {
  const user = userEvent.setup();
  await user.click(screen.getByRole("button", { name: locale === "es" ? /AÑADIR HÉROE/ : /ADD HERO/ }));
  return screen.getByRole("dialog", { name: locale === "es" ? "Añadir guerreros" : "Add warriors" });
}

describe.skipIf(freshArtefactPath() === null)("warband variant construction", () => {
  it("keeps a variant-gated slot unavailable until the mandatory choice is made", async () => {
    const reader = knowledge();
    const { service, document } = await legacySession(reader);
    renderDraft(service, document, reader, "es");
    const dialog = await openRosterDialog("es");
    const gated = within(dialog).getByRole("radio", { name: new RegExp(ES_PROFILE) });
    expect(gated).toBeDisabled();
    expect(gated.closest("label")).toHaveTextContent("Elige la variante de banda antes de añadir miembros que dependen de ella.");
    // The free slots of the same dialog stay usable.
    expect(within(dialog).getByRole("radio", { name: /Mercenario/ })).toBeEnabled();
  });

  it("presents the bound the selected option publishes and the option that forbids the slot", async () => {
    const reader = knowledge();
    const openedSession = await session(reader, "marienburg");
    const opened = renderDraft(openedSession.service, openedSession.document, reader, "es");
    const openedDialog = await openRosterDialog("es");
    const available = within(openedDialog).getByRole("radio", { name: new RegExp(ES_PROFILE) });
    expect(available).toBeEnabled();
    expect(available.closest("label")).toHaveTextContent("2");
    opened.unmount();

    const closedSession = await session(reader, "ostermark");
    renderDraft(closedSession.service, closedSession.document, reader, "es");
    const dialog = await openRosterDialog("es");
    const forbidden = within(dialog).getByRole("radio", { name: new RegExp(ES_PROFILE) });
    expect(forbidden).toBeDisabled();
    expect(forbidden.closest("label")).toHaveTextContent(`No disponible con la variante ${ES_VARIANT}`);
    // Neither the option id nor the profile id is used as visible text.
    expect(forbidden.closest("label")).not.toHaveTextContent("ostermark");
    expect(forbidden.closest("label")).not.toHaveTextContent("champions");
  });

  it("covers both locales for the gated slot", async () => {
    const reader = knowledge();
    const { service, document } = await session(reader, "ostermark");
    renderDraft(service, document, reader, "en");
    const dialog = await openRosterDialog("en");
    const forbidden = within(dialog).getByRole("radio", { name: /Champions/ });
    expect(forbidden).toBeDisabled();
    expect(forbidden.closest("label")).toHaveTextContent(`Not available with variant ${ES_VARIANT}`);
  });

  it("phrases every variant verdict the domain returns without printing an id", () => {
    const reader = knowledge();
    const profileName = (id: string, locale: "es" | "en" = "es") => knowledgeName(reader, "profile", id, locale, undefined, "mercenaries");
    const names = { bandId: "mercenaries", variantName: (band: string, variant: string) => variantName(reader, band, variant, "es") };

    expect(localizeErrorMessage("Choose a valid warband variant.", "es")).toBe("Elige una variante de banda antes de continuar.");
    expect(localizeErrorMessage("Choose a valid warband variant.", "en")).toBe("Choose a warband variant before continuing.");
    expect(localizeErrorMessage("The warband variant is locked after selection.", "es")).toBe("La variante de banda queda fijada en cuanto se elige.");
    expect(localizeErrorMessage("Unknown warband variant for mercenaries: bogus.", "es")).toBe("Esa variante no pertenece a esta banda. Elige una de las opciones publicadas.");
    expect(localizeErrorMessage('"ostermark" is not a published warband variant of "mercenaries".', "en")).toBe("That variant does not belong to this warband. Choose one of the published options.");
    expect(localizeErrorMessage('"mercenaries" requires choosing a warband variant, but the knowledge base publishes no variant options for it.', "es"))
      .toBe("La banda exige una variante, pero la base de conocimiento todavía no publica sus opciones. No es una elección tuya pendiente: es un dato que falta.");

    const forbidden = localizeErrorMessage('"champions" is not available under the selected warband variant "ostermark" of "mercenaries".', "es", profileName, names);
    expect(forbidden).toBe(`${ES_PROFILE} no está disponible con la variante ${ES_VARIANT}.`);
    expect(forbidden).not.toContain("champions");
    expect(forbidden).not.toContain("ostermark");

    const animal = localizeErrorMessage('"mercenaries" may not field animals: "champions" is an animal profile.', "en", (id) => profileName(id, "en"), names);
    expect(animal).toBe("This warband may not field animals: Champions is an animal profile.");
  });

  it("surfaces the domain rejection through the rendered route with resolved names", async () => {
    const user = userEvent.setup();
    const reader = knowledge();
    const created = await session(reader, "ostermark");
    const message = '"champions" is not available under the selected warband variant "ostermark" of "mercenaries".';
    const service = { current: () => created.document, isDirty: () => false, subscribe: () => () => {}, run: async () => ({ ok: false, reason: "rejected", message }) } as never;
    function Probe() {
      const app = useCampaignApp();
      return <><button onClick={() => void app.runAction("composeDraft", {})}>compose</button>{app.error && <output role="alert">{presentationOutput(app.error)}</output>}</>;
    }
    render(
      <CampaignAppProvider service={service} locale="es" profileName={(id) => knowledgeName(reader, "profile", id, "es", undefined, "mercenaries")} bandName={(id) => knowledgeName(reader, "band", id, "es")} variantName={(band, variant) => variantName(reader, band, variant, "es")}>
        <Probe />
      </CampaignAppProvider>,
    );
    await user.click(screen.getByRole("button", { name: "compose" }));
    const alert = await screen.findByRole("alert");
    expect(alert).toHaveTextContent(`${ES_PROFILE} no está disponible con la variante ${ES_VARIANT}.`);
    expect(alert).not.toHaveTextContent("champions");
    expect(alert).not.toHaveTextContent("ostermark");
  });
});
