import { localizedLabel } from "../campaign/presentation-enums";
import { textJoin, textNumber, textSymbol, warriorPersonalName } from "../campaign/presentation-values";
import { presentationOutput } from "../campaign/presentation-output";
import { translate } from "../campaign/i18n-core";
import { useLocale } from "../campaign/i18n-context";
import { useEffect, useMemo, useState } from "react";

import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import { DiceResolver } from "../dice/DiceResolver";
import { NumberStepper } from "../common/NumberStepper";
import { useCampaignApp } from "../campaign/useCampaignApp";
import type { CampaignDocument, IdString } from "../campaign/types";
import { calculatedAwards, scenarioAwards, scenarioExplorationRewards, scenarioLootRewards, scenarioResourceRewards, type ScenarioLootReward } from "@app/campaign/features/battle/scenario-awards";
import { underdogBonusForRatingDifference } from "@app/campaign/features/advances/experience-workflow";

export interface BattlePanelProps {
  document: CampaignDocument;
  knowledge?: ArtefactKnowledgeReader;
  locale?: "es" | "en";
  onDocument?: (document: CampaignDocument) => void;
}

function LootReward({ reward, locale, resolved, onResolved }: { reward: ScenarioLootReward; locale:"es"|"en"; resolved?:Record<string,unknown>; onResolved:(value:Record<string,unknown>)=>void }) {
  const savedRoll=(key:string)=>Array.isArray(resolved?.[key])?(resolved?.[key] as unknown[]).map(Number).filter(Number.isFinite):[];
  const [available,setAvailable]=useState(resolved ? Number(resolved["quantity"]??0)>0 : !reward.availability); const [done,setDone]=useState(Boolean(resolved)); const [awardedQuantity,setAwardedQuantity]=useState(Number(resolved?.["quantity"]??0)); const [availabilityRoll,setAvailabilityRoll]=useState(()=>savedRoll("availability_roll")); const [quantityRoll,setQuantityRoll]=useState(()=>savedRoll("quantity_roll")); const dice=(row:Record<string,unknown>|undefined)=>row?.["dice"] as Record<string,unknown>|undefined;
  const availability=dice(reward.availability); const quantity=reward.quantity_dice;
  const t=({ roll: translate({ key: "ui.9a5040b02281" }, locale), awarded: translate({ key: "ui.6c43251920c1" }, locale), available: translate({ key: "ui.9f9dfc216f33" }, locale), missing: translate({ key: "ui.b003f36a76a9" }, locale) });
  const rollText=(values:number[])=>textJoin(values.map((value)=>textNumber(value,locale)),", ");
  const resolve=(values:number[])=>{setAvailabilityRoll(values);const raw=values.reduce((sum,value)=>sum+value,0), total=raw*Number(availability?.["multiplier"]??1)+Number(availability?.["modifier"]??0), target=Number(reward.availability?.["target"]??0), when=reward.when, pass=(target?total>=target:true)&&(!when||(total>=Number(when["min"]??0)&&total<=Number(when["max"]??total)));setAvailable(pass);if(!pass){onResolved({id:reward.id,kind:reward.kind,quantity:0,availability_roll:values,label:reward.label});setDone(true);}};
  const grant=(values?:number[])=>{if(values)setQuantityRoll(values);const quantityValue=values?(values.reduce((sum,value)=>sum+value,0)*Number(quantity?.["multiplier"]??1)+Number(quantity?.["modifier"]??0)):1;setAwardedQuantity(Math.max(0,quantityValue));onResolved({id:reward.id,kind:reward.kind,quantity:Math.max(0,quantityValue),...(availabilityRoll.length?{availability_roll:availabilityRoll}:{}),...(values?{quantity_roll:values}:{}),...(reward.item_id?{item_id:reward.item_id}:{}),...(reward.resource?{resource:reward.resource}:{}),...(reward.special_id?{special_id:reward.special_id}:{}),label:reward.label,rule:reward.rule});setDone(true);};
  if(done)return <p>{presentationOutput(textJoin([reward.label,...(availabilityRoll.length>0?[textJoin([textJoin([t.roll,textSymbol(":")],""),rollText(availabilityRoll)])]:[]),...(quantityRoll.length>0?[textJoin([textJoin([t.roll,textSymbol(":")],""),rollText(quantityRoll)])]:[]),available?textJoin([textJoin([t.awarded,textSymbol(":")],""),textNumber(awardedQuantity,locale)]):t.missing]," · "))}</p>;
  if(availability&&!available)return <DiceResolver locale={locale} count={Number(availability["count"]??1)} sides={Number(availability["sides"]??6)} label={reward.label} onResolve={resolve}/>;
  return <>{availabilityRoll.length>0&&<p>{presentationOutput(textJoin([t.roll,textSymbol(":"),rollText(availabilityRoll),t.available]," "))}</p>}{quantity?<DiceResolver locale={locale} count={Number(quantity["count"]??1)} sides={Number(quantity["sides"]??6)} label={reward.label} onResolve={grant}/>:<button type="button" onClick={()=>grant()}>{presentationOutput(reward.label)}</button>}</>;
}

function objectiveCandidates(row: { label: string }, available: CampaignDocument["campaign"]["warriors"]) {
  return /\b(hero|héroe)s?\b/i.test(row.label) && !/\b(henchman|secuaz)(?:es)?\b/i.test(row.label)
    ? available.filter((warrior) => warrior.kind === "hero")
    : available;
}

export function BattlePanel({ document, knowledge, locale: requestedLocale }: BattlePanelProps) {
  const locale = useLocale(requestedLocale);
  const app = useCampaignApp();
  const saveBattleDraft = app.runAction;
  const draft=document.view.pending_battle_draft ?? {};
  const scenarios = useMemo(() => [...(knowledge?.list("scenario") ?? [])].sort((a, b) => (knowledge?.recordText(a, "name", locale) ?? translate({ key: "knowledge.unavailable" }, locale)).localeCompare((knowledge?.recordText(b, "name", locale) ?? translate({ key: "knowledge.unavailable" }, locale)), locale)), [knowledge, locale]);
  const [scenario, setScenario] = useState(String(draft["scenario"] ?? "")); const [opponent, setOpponent] = useState(String(draft["opponent"] ?? "")); const [opponentRating, setOpponentRating] = useState(String(draft["opponent_rating"] ?? ""));
  const [awardAmounts, setAwardAmounts] = useState<Record<string, number>>((draft["award_amounts"] as Record<string,number>|undefined) ?? {});
  const [result, setResult] = useState<"win" | "loss" | "draw">((draft["result"] as "win" | "loss" | "draw" | undefined) ?? "win");
  const [gold, setGold] = useState(String(draft["gold"] ?? "0")); const [wyrdstone, setWyrdstone] = useState(String(draft["wyrdstone"] ?? "0"));
  const [xp, setXp] = useState(String(draft["xp"] ?? "0")); const [notes, setNotes] = useState(String(draft["notes"] ?? "")); const [outOfAction, setOutOfAction] = useState<IdString[]>((draft["out_of_action_ids"] as IdString[] | undefined) ?? []); const [enemyOoa, setEnemyOoa] = useState<Record<string, number>>((draft["enemy_ooa"] as Record<string,number> | undefined) ?? {}); const [objectives, setObjectives] = useState<Record<string, Record<string, number>>>((draft["objectives"] as Record<string,Record<string,number>> | undefined) ?? {}); const [rewardQuantities, setRewardQuantities] = useState<Record<string, number>>((draft["reward_quantities"] as Record<string,number> | undefined) ?? {}); const [loot, setLoot] = useState<Record<string,Record<string,unknown>>>((draft["loot"] as Record<string,Record<string,unknown>> | undefined) ?? {}); const [extraItem, setExtraItem] = useState(String(draft["extra_item"] ?? "")); const [extraQuantity, setExtraQuantity] = useState(String(draft["extra_quantity"] ?? "1")); const [xpUnlocked, setXpUnlocked] = useState(Boolean(draft["xp_unlocked"])); const [xpOverride, setXpOverride] = useState<Record<string, number>>((draft["xp_override"] as Record<string,number> | undefined) ?? {}); const [busy, setBusy] = useState(false); const [submitError, setSubmitError] = useState<"record" | "exception" | null>(null);
  const pending = document.campaign.post_battles.find((post) => !post.complete);
  const t = ({ post: translate({ key: "ui.6d07c6511d84" }, locale), step: translate({ key: "ui.b3b55860db42" }, locale), continue: translate({ key: "ui.4076d9cad312" }, locale), record: translate({ key: "ui.471283dfa89a" }, locale), checks: translate({ key: "ui.830ec9e21a2d" }, locale), checkHint: translate({ key: "ui.f44c5553120a" }, locale), oldWound: translate({ key: "ui.5159ce32cc6b" }, locale), scenario: translate({ key: "ui.201fe029d821" }, locale), opponent: translate({ key: "ui.7bed3e725d95" }, locale), opponentRating: translate({ key: "ui.28b485cbb796" }, locale), result: translate({ key: "ui.0a91171a8d9f" }, locale), victory: translate({ key: "ui.a75c58313e08" }, locale), defeat: translate({ key: "ui.6f9f7ab34080" }, locale), draw: translate({ key: "ui.12620124754a" }, locale), gold: translate({ key: "ui.36e27dbf1f11" }, locale), wyrdstone: translate({ key: "ui.e71905bfd3f8" }, locale), experience: translate({ key: "ui.1cd47aaf2397" }, locale), ooa: translate({ key: "ui.b8977d088658" }, locale), notes: translate({ key: "ui.18b6f71f8d6c" }, locale), casualties: translate({ key: "ui.2c33483f2759" }, locale), submit: translate({ key: "ui.7f0caf303e37" }, locale), awards: translate({ key: "ui.87f917a96463" }, locale), enemy: translate({ key: "ui.3eb076da2af5" }, locale), objectives: translate({ key: "ui.2122bf4c22ad" }, locale), rewards: translate({ key: "ui.bc1578a0df3e" }, locale), extra: translate({ key: "ui.c6e2729931e9" }, locale), item: translate({ key: "ui.cf471eb26f03" }, locale), quantity: translate({ key: "ui.8f2846965a7a" }, locale), edit: translate({ key: "ui.eea7ec61b748" }, locale), lock: translate({ key: "ui.2158e08c298d" }, locale), manual: translate({ key: "ui.d5dfd3804010" }, locale) });
  const resolvedChecks = (document.view.pending_battle_draft?.["battle_start_checks"] ?? {}) as Record<string, { misses_battle?: boolean }>;
  const checks = document.campaign.warriors.filter((warrior) => (warrior.games_to_miss ?? 0) === 0).flatMap((warrior) => (warrior.battle_start_checks ?? []).map((check) => ({ warrior, check, key: `${warrior.id}:${String(check["check_id"] ?? "")}` })));
  const unavailable = new Set(checks.filter(({ key }) => resolvedChecks[key]?.misses_battle).map(({ warrior }) => warrior.id));
  const available = document.campaign.warriors.filter((warrior) => (warrior.games_to_miss ?? 0) === 0 && !unavailable.has(warrior.id));
  const scenarioId = scenario || "unknown"; const awards = scenarioAwards(knowledge, scenarioId, locale); const resourceRewards=scenarioResourceRewards(knowledge, scenarioId, locale); const explorationRewards=scenarioExplorationRewards(knowledge, scenarioId, locale); const lootRewards=scenarioLootRewards(knowledge, scenarioId, locale);
  const effectiveObjectives=Object.fromEntries(Object.entries(objectives).map(([awardId,recipients])=>{const award=awards.find((row)=>row.id===awardId),amount=awardAmounts[awardId];if(!award?.amountDice||amount==null||award.selection==="distributed")return[awardId,recipients];return[awardId,Object.fromEntries(Object.entries(recipients).map(([id,value])=>[id,value>0?amount:0]))];}));
  const calculated = calculatedAwards(awards, available, result, enemyOoa, effectiveObjectives); const xpAwards = xpUnlocked ? Object.fromEntries(available.map((warrior) => [warrior.id, Math.max(0, Math.trunc(xpOverride[warrior.id] ?? calculated[warrior.id] ?? 0))])) : calculated; const ratingBefore=document.campaign.states.find((state)=>state.number===document.campaign.current_state_number)?.rating ?? 0; const underdogBonus=opponentRating.trim()?underdogBonusForRatingDifference(Number(opponentRating)-ratingBefore,knowledge as never):0; const displayedXpAwards=Object.fromEntries(available.map((warrior)=>[warrior.id,(xpAwards[warrior.id]??0)+underdogBonus]));
  const objectiveResults = Object.fromEntries(awards.filter((row) => row.manual).map((row) => { const recipients=effectiveObjectives[row.id] ?? {}; const recipient=Object.keys(recipients).find((id) => (recipients[id] ?? 0) > 0) ?? ""; const amount=awardAmounts[row.id] ?? row.amount; return [row.id, row.selection === "single" ? { recipient, amount: recipient ? amount : 0 } : { recipients, amount }]; }));
  const extraItems=useMemo(()=>[...(knowledge?.list("item")??[])].sort((a,b)=>(knowledge?.recordText(a, "name", locale) ?? translate({ key: "knowledge.unavailable" }, locale)).localeCompare((knowledge?.recordText(b, "name", locale) ?? translate({ key: "knowledge.unavailable" }, locale)),locale)),[knowledge,locale]); const selectedExtra=extraItem;
  useEffect(()=>{void saveBattleDraft("saveBattleDraft",{draft:{scenario,opponent,opponent_rating:opponentRating,result,gold,wyrdstone,xp,notes,out_of_action_ids:outOfAction,enemy_ooa:enemyOoa,objectives,award_amounts:awardAmounts,reward_quantities:rewardQuantities,loot,extra_item:extraItem,extra_quantity:extraQuantity,xp_unlocked:xpUnlocked,xp_override:xpOverride}});},[saveBattleDraft,scenario,opponent,opponentRating,result,gold,wyrdstone,xp,notes,outOfAction,enemyOoa,objectives,awardAmounts,rewardQuantities,loot,extraItem,extraQuantity,xpUnlocked,xpOverride]);
  const record = async () => { setBusy(true); setSubmitError(null); try { const ok=await app.runAction("recordBattle", { scenario: scenarioId, opponent, opponent_rating: opponentRating.trim() ? Number(opponentRating) : null, result, gold_delta: Number(gold) || 0, wyrdstone: Number(wyrdstone) || 0, xp_delta: Number(xp) || 0, xp_awards: xpAwards, scenario_results: { scenario_id: scenarioId, enemy_out_of_action_by_warrior: enemyOoa, objectives: objectiveResults, additional_rewards: [...resourceRewards.flatMap((row) => { const quantity=Math.max(0,Math.trunc(rewardQuantities[row.id]??0)); return quantity?[{kind:"resource",resource:row.resource,quantity}]:[]; }),...explorationRewards.map((row)=>({kind:"exploration",extra_dice:row.extra_dice,reroll_all:row.reroll_all,quantity:1,rule:row.rule})),...Object.values(loot), ...(extraItem&&Number(extraQuantity)>0?[{kind:"item",item_id:extraItem,quantity:Math.max(1,Math.trunc(Number(extraQuantity))),source:"house_rule"}]:[])] }, out_of_action_ids: outOfAction, notes: notes.trim() }); if(!ok)setSubmitError("record"); } catch(error) { console.error(error); setSubmitError("exception"); } finally { setBusy(false); } };
  const casualtiesFor = (id: IdString) => outOfAction.filter((value) => value === id).length;
  const setCasualties = (id: IdString, count: number) => setOutOfAction((current) => [...current.filter((value) => value !== id), ...Array.from({ length: Math.max(0, count) }, () => id)]);
  const blockedReason = busy ? (translate({ key: "ui.4cf7badb878f" }, locale)) : !scenario ? (translate({ key: "ui.eae3868a35a6" }, locale)) : !opponent.trim() ? (translate({ key: "ui.e7b6ca790f0e" }, locale)) : available.length === 0 ? (translate({ key: "ui.62bb2f25f46e" }, locale)) : null;
  if (pending) return <section aria-label={presentationOutput(translate({ key: "ui.8731a48db4a4" }, locale))}><h2>{presentationOutput(textJoin([t.post,textJoin([textSymbol("#"),textNumber(pending.battle_number, locale)],"")]))}</h2><p role="status">{presentationOutput(textJoin([t.step,textJoin([textNumber(pending.active_step + 1, locale),textSymbol("/"),textNumber(8,locale)],""),t.continue]))}</p></section>;
  return <section aria-label={presentationOutput(translate({ key: "ui.8731a48db4a4" }, locale))}><header className="battle-record-heading"><h2>{presentationOutput(t.record)}</h2><button className="primary" disabled={Boolean(blockedReason)} data-disabled-reason={blockedReason ? presentationOutput(blockedReason) : undefined} form="record-battle-form" type="submit">{presentationOutput(t.submit)}</button></header>{(app.error || submitError) && <output role="alert">{presentationOutput(app.error ?? translate({key:submitError==="record"?"ui.3c4b05a4b32b":"ui.a8d1287e0979"},locale))}</output>}{checks.length > 0 && <fieldset><legend>{presentationOutput(t.checks)}</legend><p>{presentationOutput(t.checkHint)}</p>{checks.map(({ warrior, check, key }) => { const dice=(check["dice"] ?? {}) as Record<string, unknown>; const count=Number(dice["count"] ?? 1); const sides=Number(dice["sides"] ?? 6); return resolvedChecks[key] ? <p key={key}>{presentationOutput(textJoin([warriorPersonalName(warrior,locale),t.oldWound,textSymbol(":")]," · "))} {presentationOutput(resolvedChecks[key].misses_battle ? t.ooa : translate({key:"battle.check-passed"},locale))}</p> : <DiceResolver locale={locale} key={key} count={count} sides={sides} label={textJoin([warriorPersonalName(warrior, locale), t.oldWound], " · ")} onResolve={(values) => void app.runAction("resolveBattleStartCheck", { warrior_id: warrior.id, check_id: String(check["check_id"] ?? ""), roll: values.reduce((sum, value) => sum + value, 0) })}/>; })}</fieldset>}<form id="record-battle-form" onSubmit={(event) => { event.preventDefault(); void record(); }}>
    <label>{presentationOutput(t.scenario)}<select required value={scenario} onChange={(event) => {setScenario(event.target.value);setEnemyOoa({});setObjectives({});setAwardAmounts({});setRewardQuantities({});setLoot({});}}><option value="" disabled>{presentationOutput(translate({ key: "ui.db3dd5208501" }, locale))}</option>{scenarios.map((row) => <option value={String(row.id)} key={String(row.id)}>{presentationOutput((knowledge?.recordText(row, "name", locale) ?? translate({ key: "knowledge.unavailable" }, locale)))}</option>)}</select></label>
    <label>{presentationOutput(t.opponent)}<input required value={opponent} onChange={(event) => setOpponent(event.target.value)} /></label>
    <label>{presentationOutput(t.opponentRating)}<input type="number" min="0" value={opponentRating} onChange={(event) => setOpponentRating(event.target.value)} /></label>
    <label>{presentationOutput(t.result)}<select value={result} onChange={(event) => setResult(event.target.value as typeof result)}><option value="win">{presentationOutput(t.victory)}</option><option value="loss">{presentationOutput(t.defeat)}</option><option value="draw">{presentationOutput(t.draw)}</option></select></label>
    {awards.some((row) => row.trigger === "enemy_put_out_of_action") && <fieldset><legend>{presentationOutput(t.enemy)}</legend><div className="enemy-ooa-controls">{available.filter((warrior) => warrior.kind === "hero").map((warrior) => <div className="warrior-control-row" key={warrior.id}><span>{presentationOutput(warriorPersonalName(warrior,locale))}</span><NumberStepper locale={locale} label={textJoin([translate({ key: "number.enemy" }, locale), warriorPersonalName(warrior, locale)])} value={enemyOoa[warrior.id] ?? 0} onChange={(value)=>setEnemyOoa((current)=>({...current,[warrior.id]:value}))}/></div>)}</div></fieldset>}
    {awards.filter((row) => row.manual).length > 0 && <fieldset><legend>{presentationOutput(t.objectives)}</legend>{awards.filter((row) => row.manual).map((row) => <div className="scenario-objective" key={row.id}><strong>{presentationOutput(row.label)}</strong>{row.amountDice && <DiceResolver locale={locale} count={row.amountDice[0]} sides={row.amountDice[1]} label={row.label} onResolve={(dice)=>setAwardAmounts((current)=>({...current,[row.id]:dice.reduce((sum,value)=>sum+value,0)}))}/>}<div className="scenario-objective-recipients">{objectiveCandidates(row, available).map((warrior) => row.selection === "single" ? <label key={warrior.id}><input type="checkbox" checked={(objectives[row.id]?.[warrior.id] ?? 0) > 0} onChange={(event) => setObjectives((current) => ({ ...current, [row.id]: event.target.checked ? { [warrior.id]: awardAmounts[row.id] ?? row.amount } : {} }))} />{presentationOutput(warriorPersonalName(warrior,locale))}</label> : row.selection === "multiple" ? <label key={warrior.id}><input type="checkbox" checked={(objectives[row.id]?.[warrior.id] ?? 0) > 0} onChange={(event) => setObjectives((current) => ({ ...current, [row.id]: { ...(current[row.id] ?? {}), [warrior.id]: event.target.checked ? awardAmounts[row.id] ?? row.amount : 0 } }))} />{presentationOutput(warriorPersonalName(warrior,locale))}</label> : <div className="warrior-control-row" key={warrior.id}><span>{presentationOutput(warriorPersonalName(warrior,locale))}</span><NumberStepper locale={locale} label={textJoin([translate({ key: "number.manual" }, locale), warriorPersonalName(warrior, locale)])} value={objectives[row.id]?.[warrior.id] ?? 0} onChange={(value) => setObjectives((current) => ({ ...current, [row.id]: { ...(current[row.id] ?? {}), [warrior.id]: value } }))}/></div>)}</div></div>)}</fieldset>}
    {resourceRewards.length > 0 && <fieldset><legend>{presentationOutput(t.rewards)}</legend>{resourceRewards.map((row) => <div className="warrior-control-row" key={row.id}><span>{presentationOutput(translate({key:"battle.resource-obtained",args:{resource:localizedLabel(row.resource,locale)}},locale))}</span><NumberStepper locale={locale} label={localizedLabel(row.resource, locale)} value={rewardQuantities[row.id] ?? 0} onChange={(value) => setRewardQuantities((current) => ({ ...current, [row.id]: value }))}/></div>)}</fieldset>}
    {lootRewards.length > 0 && <fieldset><legend>{presentationOutput(t.rewards)}</legend>{lootRewards.map((reward)=><LootReward key={`${scenarioId}:${reward.id}`} reward={reward} locale={locale} resolved={loot[reward.id]} onResolved={(value)=>setLoot((current)=>({...current,[reward.id]:value}))}/>)}</fieldset>}
    <fieldset><legend>{presentationOutput(t.ooa)}</legend>{available.map((warrior) => warrior.kind === "henchman" && (warrior.quantity ?? 1) > 1 ? <div className="warrior-control-row" key={warrior.id}><span>{presentationOutput(textJoin([warriorPersonalName(warrior,locale),t.casualties]," · "))}</span><NumberStepper locale={locale} label={textJoin([translate({ key: "number.casualties" }, locale), warriorPersonalName(warrior, locale)])} value={casualtiesFor(warrior.id)} min={0} max={warrior.quantity ?? 1} onChange={(value) => setCasualties(warrior.id, value)} /></div> : <label key={warrior.id}><input type="checkbox" checked={outOfAction.includes(warrior.id)} onChange={(event) => setCasualties(warrior.id, event.target.checked ? 1 : 0)} />{presentationOutput(warriorPersonalName(warrior,locale))}</label>)}</fieldset>
    <label>{presentationOutput(t.notes)}<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>
    <fieldset><legend>{presentationOutput(t.extra)}</legend><div className="warrior-control-row"><span>{presentationOutput(t.gold)}</span><NumberStepper locale={locale} label={translate({ key: "number.gold" }, locale)} value={Math.max(0, Number(gold) || 0)} onChange={(value) => setGold(String(value))}/></div><div className="warrior-control-row"><span>{presentationOutput(t.wyrdstone)}</span><NumberStepper locale={locale} label={translate({ key: "number.wyrdstone" }, locale)} value={Math.max(0, Number(wyrdstone) || 0)} onChange={(value) => setWyrdstone(String(value))}/></div><div className="warrior-control-row"><span>{presentationOutput(t.experience)}</span><NumberStepper locale={locale} label={translate({ key: "number.experience" }, locale)} value={Math.max(0, Number(xp) || 0)} onChange={(value) => setXp(String(value))}/></div>{extraItems.length > 0 && <><label>{presentationOutput(t.item)}<select value={selectedExtra} onChange={(event) => setExtraItem(event.target.value)}><option value="">{presentationOutput(translate({ key: "ui.0ce8e4ce27f3" }, locale))}</option>{extraItems.map((item) => <option key={String(item.item_id)} value={String(item.item_id)}>{presentationOutput((knowledge?.recordText(item, "name", locale) ?? translate({ key: "knowledge.unavailable" }, locale)))}</option>)}</select></label><div className="warrior-control-row"><span>{presentationOutput(t.quantity)}</span><NumberStepper locale={locale} label={translate({ key: "number.quantity" }, locale)} value={Math.max(0, Number(extraQuantity) || 0)} onChange={(value) => setExtraQuantity(String(value))}/></div></>}</fieldset>
    <fieldset><legend>{presentationOutput(t.awards)}</legend>{underdogBonus>0&&<p>{presentationOutput(textJoin([translate({ key: "ui.79c2d1f3a039" }, locale),textSymbol(":"),textSymbol("+"),textNumber(underdogBonus,locale),translate({ key: "unit.experience" }, locale)]))}</p>}<button type="button" onClick={() => setXpUnlocked((current) => !current)}>{presentationOutput(xpUnlocked ? t.lock : t.edit)}</button>{available.map((warrior) => <div className="warrior-control-row" key={warrior.id}><span>{presentationOutput(warriorPersonalName(warrior,locale))}</span>{xpUnlocked ? <NumberStepper locale={locale} label={textJoin([translate({ key: "number.experience" }, locale), warriorPersonalName(warrior, locale)])} value={displayedXpAwards[warrior.id] ?? 0} min={underdogBonus} onChange={(value) => setXpOverride((current) => ({ ...current, [warrior.id]: Math.max(0,value-underdogBonus) }))} /> : <output>{presentationOutput(textNumber(displayedXpAwards[warrior.id] ?? 0, locale))}</output>}</div>)}</fieldset>
    {blockedReason && !busy && <p role="status">{presentationOutput(blockedReason)}</p>}
  </form></section>;
}
