import { useEffect, useMemo, useState } from "react";

import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import { resolveName } from "@adapters/knowledge-reader/index";
import { DiceResolver } from "../dice/DiceResolver";
import { useCampaignApp } from "../campaign/useCampaignApp";
import type { CampaignDocument, IdString } from "../campaign/types";
import { readableValue } from "../campaign/displayText";
import { calculatedAwards, scenarioAwards, scenarioExplorationRewards, scenarioLootRewards, scenarioResourceRewards, type ScenarioLootReward } from "@app/campaign/features/battle/scenario-awards";

export interface BattlePanelProps {
  document: CampaignDocument;
  knowledge?: ArtefactKnowledgeReader;
  locale?: "es" | "en";
  onDocument?: (document: CampaignDocument) => void;
}

function LootReward({ reward, locale, resolved, onResolved }: { reward: ScenarioLootReward; locale:"es"|"en"; resolved?:Record<string,unknown>; onResolved:(value:Record<string,unknown>)=>void }) {
  const [available,setAvailable]=useState(resolved ? Number(resolved["quantity"]??0)>0 : !reward.availability); const [done,setDone]=useState(Boolean(resolved)); const dice=(row:Record<string,unknown>|undefined)=>row?.["dice"] as Record<string,unknown>|undefined;
  const availability=dice(reward.availability); const quantity=reward.quantity_dice;
  const resolve=(values:number[])=>{const raw=values.reduce((sum,value)=>sum+value,0), total=raw*Number(availability?.["multiplier"]??1)+Number(availability?.["modifier"]??0), target=Number(reward.availability?.["target"]??0), when=reward.when, pass=(target?total>=target:true)&&(!when||(total>=Number(when["min"]??0)&&total<=Number(when["max"]??total)));setAvailable(pass);if(!pass){onResolved({id:reward.id,kind:reward.kind,quantity:0,label:reward.label});setDone(true);}};
  const grant=(values?:number[])=>{const quantityValue=values?(values.reduce((sum,value)=>sum+value,0)*Number(quantity?.["multiplier"]??1)+Number(quantity?.["modifier"]??0)):1;onResolved({id:reward.id,kind:reward.kind,quantity:Math.max(0,quantityValue),...(reward.item_id?{item_id:reward.item_id}:{}),...(reward.resource?{resource:reward.resource}:{}),...(reward.special_id?{special_id:reward.special_id}:{}),label:reward.label,rule:reward.rule});setDone(true);};
  if(done)return <p>{reward.label} · {available?"✓":"—"}</p>;
  if(availability&&!available)return <DiceResolver locale={locale} count={Number(availability["count"]??1)} sides={Number(availability["sides"]??6)} label={reward.label} onResolve={resolve}/>;
  return quantity?<DiceResolver locale={locale} count={Number(quantity["count"]??1)} sides={Number(quantity["sides"]??6)} label={reward.label} onResolve={grant}/>:<button type="button" onClick={()=>grant()}>{reward.label}</button>;
}

export function BattlePanel({ document, knowledge, locale = "en" }: BattlePanelProps) {
  const app = useCampaignApp();
  const draft=document.view.pending_battle_draft ?? {};
  const scenarios = useMemo(() => [...(knowledge?.list("scenario") ?? [])].sort((a, b) => resolveName(a, locale).localeCompare(resolveName(b, locale), locale)), [knowledge, locale]);
  const [scenario, setScenario] = useState(String(draft["scenario"] ?? "")); const [opponent, setOpponent] = useState(String(draft["opponent"] ?? "")); const [opponentRating, setOpponentRating] = useState(String(draft["opponent_rating"] ?? ""));
  const [awardAmounts, setAwardAmounts] = useState<Record<string, number>>((draft["award_amounts"] as Record<string,number>|undefined) ?? {});
  const [result, setResult] = useState<"win" | "loss" | "draw">((draft["result"] as "win" | "loss" | "draw" | undefined) ?? "win");
  const [gold, setGold] = useState(String(draft["gold"] ?? "0")); const [wyrdstone, setWyrdstone] = useState(String(draft["wyrdstone"] ?? "0"));
  const [xp, setXp] = useState(String(draft["xp"] ?? "0")); const [notes, setNotes] = useState(String(draft["notes"] ?? "")); const [outOfAction, setOutOfAction] = useState<IdString[]>((draft["out_of_action_ids"] as IdString[] | undefined) ?? []); const [enemyOoa, setEnemyOoa] = useState<Record<string, number>>((draft["enemy_ooa"] as Record<string,number> | undefined) ?? {}); const [objectives, setObjectives] = useState<Record<string, Record<string, number>>>((draft["objectives"] as Record<string,Record<string,number>> | undefined) ?? {}); const [rewardQuantities, setRewardQuantities] = useState<Record<string, number>>((draft["reward_quantities"] as Record<string,number> | undefined) ?? {}); const [loot, setLoot] = useState<Record<string,Record<string,unknown>>>((draft["loot"] as Record<string,Record<string,unknown>> | undefined) ?? {}); const [extraItem, setExtraItem] = useState(String(draft["extra_item"] ?? "")); const [extraQuantity, setExtraQuantity] = useState(String(draft["extra_quantity"] ?? "1")); const [xpUnlocked, setXpUnlocked] = useState(Boolean(draft["xp_unlocked"])); const [xpOverride, setXpOverride] = useState<Record<string, number>>((draft["xp_override"] as Record<string,number> | undefined) ?? {}); const [busy, setBusy] = useState(false); const [submitError, setSubmitError] = useState("");
  const pending = document.campaign.post_battles.find((post) => !post.complete);
  const t = locale === "es" ? { post:"Post-batalla",step:"Paso",continue:"Continúa con las acciones guiadas que aparecen debajo.",record:"Registrar batalla",checks:"Comprobaciones prebatalla",checkHint:"Resuelve heridas persistentes antes de registrar batalla.",oldWound:"Herida de batalla antigua",scenario:"Escenario",opponent:"Oponente",opponentRating:"Valoración rival",result:"Resultado",victory:"Victoria",defeat:"Derrota",draw:"Empate",gold:"Oro",wyrdstone:"Piedra bruja",experience:"Experiencia",ooa:"Fuera de combate",notes:"Notas",casualties:"Bajas",submit:"Registrar batalla",awards:"Experiencia por guerrero",enemy:"Enemigos fuera de combate",objectives:"Objetivos del escenario",rewards:"Recompensas de escenario",extra:"Recompensas adicionales",item:"Objeto",quantity:"Cantidad",edit:"Editar EXP",lock:"Bloquear EXP",manual:"Recompensa manual" } : { post:"Post-battle",step:"Step",continue:"Continue with the guided actions shown below.",record:"Record a battle",checks:"Pre-battle checks",checkHint:"Resolve lasting injuries before recording battle.",oldWound:"Old Battle Wound",scenario:"Scenario",opponent:"Opponent",opponentRating:"Opponent rating",result:"Result",victory:"Victory",defeat:"Defeat",draw:"Draw",gold:"Gold",wyrdstone:"Wyrdstone",experience:"Experience",ooa:"Out of action",notes:"Notes",casualties:"Casualties",submit:"Record battle",awards:"Experience by warrior",enemy:"Enemies put out of action",objectives:"Scenario objectives",rewards:"Scenario rewards",extra:"Additional rewards",item:"Item",quantity:"Quantity",edit:"Edit XP",lock:"Lock XP",manual:"Manual reward" };
  const resolvedChecks = (document.view.pending_battle_draft?.["battle_start_checks"] ?? {}) as Record<string, { misses_battle?: boolean }>;
  const checks = document.campaign.warriors.filter((warrior) => (warrior.games_to_miss ?? 0) === 0).flatMap((warrior) => (warrior.battle_start_checks ?? []).map((check) => ({ warrior, check, key: `${warrior.id}:${String(check["check_id"] ?? "")}` })));
  const unavailable = new Set(checks.filter(({ key }) => resolvedChecks[key]?.misses_battle).map(({ warrior }) => warrior.id));
  const available = document.campaign.warriors.filter((warrior) => (warrior.games_to_miss ?? 0) === 0 && !unavailable.has(warrior.id));
  const scenarioId = scenario || "unknown"; const awards = scenarioAwards(knowledge, scenarioId, locale); const resourceRewards=scenarioResourceRewards(knowledge, scenarioId); const explorationRewards=scenarioExplorationRewards(knowledge,scenarioId); const lootRewards=scenarioLootRewards(knowledge, scenarioId);
  const effectiveObjectives=Object.fromEntries(Object.entries(objectives).map(([awardId,recipients])=>{const award=awards.find((row)=>row.id===awardId),amount=awardAmounts[awardId];if(!award?.amountDice||amount==null||award.selection==="distributed")return[awardId,recipients];return[awardId,Object.fromEntries(Object.entries(recipients).map(([id,value])=>[id,value>0?amount:0]))];}));
  const calculated = calculatedAwards(awards, available, result, enemyOoa, effectiveObjectives); const xpAwards = xpUnlocked ? Object.fromEntries(available.map((warrior) => [warrior.id, Math.max(0, Math.trunc(xpOverride[warrior.id] ?? calculated[warrior.id] ?? 0))])) : calculated;
  const objectiveResults = Object.fromEntries(awards.filter((row) => row.manual).map((row) => { const recipients=effectiveObjectives[row.id] ?? {}; const recipient=Object.keys(recipients).find((id) => (recipients[id] ?? 0) > 0) ?? ""; const amount=awardAmounts[row.id] ?? row.amount; return [row.id, row.selection === "single" ? { recipient, amount: recipient ? amount : 0 } : { recipients, amount }]; }));
  const extraItems=useMemo(()=>[...(knowledge?.list("item")??[])].sort((a,b)=>resolveName(a,locale).localeCompare(resolveName(b,locale),locale)),[knowledge,locale]); const selectedExtra=extraItem;
  useEffect(()=>{void app.runAction("saveBattleDraft",{draft:{scenario,opponent,opponent_rating:opponentRating,result,gold,wyrdstone,xp,notes,out_of_action_ids:outOfAction,enemy_ooa:enemyOoa,objectives,award_amounts:awardAmounts,reward_quantities:rewardQuantities,loot,extra_item:extraItem,extra_quantity:extraQuantity,xp_unlocked:xpUnlocked,xp_override:xpOverride}});},[app,scenario,opponent,opponentRating,result,gold,wyrdstone,xp,notes,outOfAction,enemyOoa,objectives,awardAmounts,rewardQuantities,loot,extraItem,extraQuantity,xpUnlocked,xpOverride]);
  const record = async () => { setBusy(true); setSubmitError(""); try { const ok=await app.runAction("recordBattle", { scenario: scenarioId, opponent, opponent_rating: opponentRating.trim() ? Number(opponentRating) : null, result, gold_delta: Number(gold) || 0, wyrdstone: Number(wyrdstone) || 0, xp_delta: Number(xp) || 0, xp_awards: xpAwards, scenario_results: { scenario_id: scenarioId, enemy_out_of_action_by_warrior: enemyOoa, objectives: objectiveResults, additional_rewards: [...resourceRewards.flatMap((row) => { const quantity=Math.max(0,Math.trunc(rewardQuantities[row.id]??0)); return quantity?[{kind:"resource",resource:row.resource,quantity}]:[]; }),...explorationRewards.map((row)=>({kind:"exploration",extra_dice:row.extra_dice,reroll_all:row.reroll_all,quantity:1,rule:row.rule})),...Object.values(loot), ...(extraItem&&Number(extraQuantity)>0?[{kind:"item",item_id:extraItem,quantity:Math.max(1,Math.trunc(Number(extraQuantity))),source:"house_rule"}]:[])] }, out_of_action_ids: outOfAction, notes: notes.trim() }); if(!ok)setSubmitError(locale==="es"?"No se pudo registrar la batalla. Revisa el error indicado arriba.":"The battle could not be recorded. Check the error shown above."); } catch(error) { setSubmitError(error instanceof Error?error.message:(locale==="es"?"No se pudo registrar la batalla.":"The battle could not be recorded.")); } finally { setBusy(false); } };
  const casualtiesFor = (id: IdString) => outOfAction.filter((value) => value === id).length;
  const setCasualties = (id: IdString, count: number) => setOutOfAction((current) => [...current.filter((value) => value !== id), ...Array.from({ length: Math.max(0, count) }, () => id)]);
  const blockedReason = busy ? (locale === "es" ? "Se está registrando la batalla." : "The battle is being recorded.") : !scenario ? (locale === "es" ? "Selecciona un escenario." : "Select a scenario.") : !opponent.trim() ? (locale === "es" ? "Introduce el nombre de la banda oponente." : "Enter the opposing warband name.") : available.length === 0 ? (locale === "es" ? "No hay guerreros disponibles para participar en la batalla." : "No warriors are available for the battle.") : "";
  if (pending) return <section aria-label={locale === "es" ? "Batalla" : "Battle"}><h2>{t.post} #{pending.battle_number}</h2><p role="status">{t.step} {pending.active_step + 1}/8. {t.continue}</p></section>;
  return <section aria-label={locale === "es" ? "Batalla" : "Battle"}><h2>{t.record}</h2>{(app.error || submitError) && <output role="alert">{app.error || submitError}</output>}{checks.length > 0 && <fieldset><legend>{t.checks}</legend><p>{t.checkHint}</p>{checks.map(({ warrior, check, key }) => { const dice=(check["dice"] ?? {}) as Record<string, unknown>; const count=Number(dice["count"] ?? 1); const sides=Number(dice["sides"] ?? 6); return resolvedChecks[key] ? <p key={key}>{warrior.name} · {t.oldWound}: {resolvedChecks[key].misses_battle ? t.ooa : "OK"}</p> : <DiceResolver locale={locale} key={key} count={count} sides={sides} label={`${warrior.name} · ${t.oldWound}`} onResolve={(values) => void app.runAction("resolveBattleStartCheck", { warrior_id: warrior.id, check_id: String(check["check_id"] ?? ""), roll: values.reduce((sum, value) => sum + value, 0) })}/>; })}</fieldset>}<form onSubmit={(event) => { event.preventDefault(); void record(); }}>
    <label>{t.scenario}<select required value={scenario} onChange={(event) => {setScenario(event.target.value);setEnemyOoa({});setObjectives({});setAwardAmounts({});setRewardQuantities({});setLoot({});}}><option value="" disabled>{locale === "es" ? "Selecciona un escenario…" : "Select a scenario…"}</option>{scenarios.map((row) => <option value={String(row.id)} key={String(row.id)}>{resolveName(row, locale)}</option>)}</select></label>
    <label>{t.opponent}<input required value={opponent} onChange={(event) => setOpponent(event.target.value)} /></label>
    <label>{t.opponentRating}<input type="number" min="0" value={opponentRating} onChange={(event) => setOpponentRating(event.target.value)} /></label>
    <label>{t.result}<select value={result} onChange={(event) => setResult(event.target.value as typeof result)}><option value="win">{t.victory}</option><option value="loss">{t.defeat}</option><option value="draw">{t.draw}</option></select></label>
    {awards.some((row) => row.trigger === "enemy_put_out_of_action") && <fieldset><legend>{t.enemy}</legend>{available.filter((warrior) => warrior.kind === "hero").map((warrior) => <label key={warrior.id}>{warrior.name}<input type="number" min="0" value={enemyOoa[warrior.id] ?? 0} onChange={(event) => setEnemyOoa((current) => ({ ...current, [warrior.id]: Math.max(0, Math.trunc(event.target.valueAsNumber || 0)) }))} /></label>)}</fieldset>}
    {awards.filter((row) => row.manual).length > 0 && <fieldset><legend>{t.objectives}</legend>{awards.filter((row) => row.manual).map((row) => <div key={row.id}><strong>{row.label}</strong>{row.amountDice && <DiceResolver locale={locale} count={row.amountDice[0]} sides={row.amountDice[1]} label={row.label} onResolve={(dice)=>setAwardAmounts((current)=>({...current,[row.id]:dice.reduce((sum,value)=>sum+value,0)}))}/>} {row.selection === "single" ? <label>{t.manual}<select value={Object.keys(objectives[row.id] ?? {}).find((id) => (objectives[row.id]?.[id] ?? 0) > 0) ?? ""} onChange={(event) => setObjectives((current) => ({ ...current, [row.id]: event.target.value ? { [event.target.value]: awardAmounts[row.id] ?? row.amount } : {} }))}><option value="">{locale === "es" ? "Selecciona un guerrero…" : "Select a warrior…"}</option>{[...available].sort((a,b)=>a.name.localeCompare(b.name,locale)).map((warrior) => <option key={warrior.id} value={warrior.id}>{warrior.name}</option>)}</select></label> : available.map((warrior) => row.selection === "multiple" ? <label key={warrior.id}><input type="checkbox" checked={(objectives[row.id]?.[warrior.id] ?? 0) > 0} onChange={(event) => setObjectives((current) => ({ ...current, [row.id]: { ...(current[row.id] ?? {}), [warrior.id]: event.target.checked ? awardAmounts[row.id] ?? row.amount : 0 } }))} />{warrior.name}</label> : <label key={warrior.id}>{warrior.name}<input aria-label={`${t.manual} ${warrior.name}`} type="number" min="0" value={objectives[row.id]?.[warrior.id] ?? 0} onChange={(event) => setObjectives((current) => ({ ...current, [row.id]: { ...(current[row.id] ?? {}), [warrior.id]: Math.max(0, Math.trunc(event.target.valueAsNumber || 0)) } }))} /></label>)}</div>)}</fieldset>}
    {resourceRewards.length > 0 && <fieldset><legend>{t.rewards}</legend>{resourceRewards.map((row) => <label key={row.id}>{locale === "es" ? `${readableValue(row.resource, locale)} obtenidos según el escenario` : row.rule}<input type="number" min="0" value={rewardQuantities[row.id] ?? 0} onChange={(event) => setRewardQuantities((current) => ({ ...current, [row.id]: Math.max(0, Math.trunc(event.target.valueAsNumber || 0)) }))} /></label>)}</fieldset>}
    {lootRewards.length > 0 && <fieldset><legend>{t.rewards}</legend>{lootRewards.map((reward)=><LootReward key={`${scenarioId}:${reward.id}`} reward={reward} locale={locale} resolved={loot[reward.id]} onResolved={(value)=>setLoot((current)=>({...current,[reward.id]:value}))}/>)}</fieldset>}
    <fieldset><legend>{t.awards}</legend><button type="button" onClick={() => setXpUnlocked((current) => !current)}>{xpUnlocked ? t.lock : t.edit}</button>{available.map((warrior) => <label key={warrior.id}>{warrior.name}{xpUnlocked ? <input type="number" min="0" value={xpOverride[warrior.id] ?? calculated[warrior.id] ?? 0} onChange={(event) => setXpOverride((current) => ({ ...current, [warrior.id]: Math.max(0, Math.trunc(event.target.valueAsNumber || 0)) }))} /> : <output>{calculated[warrior.id] ?? 0}</output>}</label>)}</fieldset>
    <fieldset><legend>{t.ooa}</legend>{available.map((warrior) => warrior.kind === "henchman" && (warrior.quantity ?? 1) > 1 ? <label key={warrior.id}>{warrior.name} · {t.casualties}<input aria-label={`${t.casualties} ${warrior.name}`} type="number" min="0" max={warrior.quantity ?? 1} value={casualtiesFor(warrior.id)} onChange={(event) => setCasualties(warrior.id, Math.min(warrior.quantity ?? 1, Math.max(0, Math.trunc(event.target.valueAsNumber || 0))))} /></label> : <label key={warrior.id}><input type="checkbox" checked={outOfAction.includes(warrior.id)} onChange={(event) => setCasualties(warrior.id, event.target.checked ? 1 : 0)} />{warrior.name}</label>)}</fieldset>
    <label>{t.notes}<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>
    <fieldset><legend>{t.extra}</legend><label>{t.gold}<input type="number" min="0" value={gold} onChange={(event) => setGold(event.target.value)} /></label><label>{t.wyrdstone}<input type="number" min="0" value={wyrdstone} onChange={(event) => setWyrdstone(event.target.value)} /></label><label>{t.experience}<input type="number" min="0" value={xp} onChange={(event) => setXp(event.target.value)} /></label>{extraItems.length > 0 && <><label>{t.item}<select value={selectedExtra} onChange={(event) => setExtraItem(event.target.value)}><option value="">{locale === "es" ? "Selecciona un objeto…" : "Select an item…"}</option>{extraItems.map((item) => <option key={String(item.item_id)} value={String(item.item_id)}>{resolveName(item, locale)}</option>)}</select></label><label>{t.quantity}<input type="number" min="0" value={extraQuantity} onChange={(event) => setExtraQuantity(event.target.value)} /></label></>}</fieldset>
    <button className="primary" disabled={Boolean(blockedReason)} data-disabled-reason={blockedReason || undefined} type="submit">{t.submit}</button>{blockedReason && !busy && <p role="status">{blockedReason}</p>}
  </form></section>;
}
