schema_version: 2
sources:
- id: mordheimer.net
  name: mordheimer.net
- id: chaos-in-the-streets
  name: Chaos in the Streets
- id: khemri
  name: Khemri (Mordheimer.net)
- id: lustria
  name: Lustria (Mordheimer.net)
- id: trollheim
  name: Trollheim (Mordheimer.net)
- id: user-ruling
  name: User Ruling
- id: mordheim-rulebook
  name: Mordheim Rulebook
- id: sylvania-supplement
  name: Sylvania Supplement (Mordheimer.net)
- id: mordheim-index-catalog
  name: Mordheim Index Catalog (Mordheimer.net)
- id: mordheim-facebook-group
  name: Mordheim Facebook Group
- id: broheim.net
  name: broheim.net
- id: liber-malefic
  name: Liber Malefic (Miracle Workers, Werekin)
