schema_version: 2
band_id: dwarf-guildsmen-kaz
profiles:
- id: master-craftsman
  name: Master Craftsman
  type: hero
  cost: 85
  experience: 20
  characteristics:
    M: 3
    WS: 5
    BS: 4
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - thunderer-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - shooting
  - academic
  - strength
  - special
  source:
    manual: broheim.net
    printed_page: 26
    section: 1 Dwarf Master Craftsman
    url: https://broheim.net/downloads/campaigns/karakazgal/Karak Azgal.pdf
  source_path:
  - heroes
  - 1 Dwarf Master Craftsman
  name_i18n:
    es: Maestro Artesano
  rule_ids:
  - master-craftsman--leader
  combat_traits: {}
- id: expert-craftsmen
  name: Expert Craftsmen
  type: hero
  cost: 50
  experience: 10
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - thunderer-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - shooting
  - special
  source:
    manual: broheim.net
    printed_page: 27
    section: 0-2 Dwarf Expert Craftsman
    url: https://broheim.net/downloads/campaigns/karakazgal/Karak Azgal.pdf
  source_path:
  - heroes
  - 0-2 Dwarf Expert Craftsman
  name_i18n:
    es: Artesanos Expertos
  rule_ids: []
  combat_traits: {}
- id: apprentices
  name: Apprentices
  type: hero
  cost: 35
  experience: 0
  characteristics:
    M: 3
    WS: 3
    BS: 2
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 8
  equipment_lists:
  - thunderer-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access:
  - combat
  - shooting
  - special
  source:
    manual: broheim.net
    printed_page: 27
    section: 0-2 Dwarf Apprentice
    url: https://broheim.net/downloads/campaigns/karakazgal/Karak Azgal.pdf
  source_path:
  - heroes
  - 0-2 Dwarf Apprentice
  name_i18n:
    es: Aprendices
  rule_ids: []
  combat_traits: {}
- id: artisans
  name: Artisans
  type: henchman
  cost: 40
  experience: 0
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - dwarf-warrior-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: broheim.net
    printed_page: 27
    section: Dwarf Artisans
    url: https://broheim.net/downloads/campaigns/karakazgal/Karak Azgal.pdf
  source_path:
  - henchmen
  - Dwarf Artisans
  name_i18n:
    es: Artesanos
  rule_ids: []
  combat_traits: {}
- id: labourers
  name: Labourers
  type: henchman
  cost: 25
  experience: 0
  characteristics:
    M: 3
    WS: 3
    BS: 2
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 8
  equipment_lists:
  - dwarf-warrior-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: broheim.net
    printed_page: 28
    section: Dwarf Labourers
    url: https://broheim.net/downloads/campaigns/karakazgal/Karak Azgal.pdf
  source_path:
  - henchmen
  - Dwarf Labourers
  name_i18n:
    es: Peones
  rule_ids: []
  combat_traits: {}
- id: dwarf-thunderers
  name: Dwarf Thunderers
  type: henchman
  cost: 40
  experience: 0
  characteristics:
    M: 3
    WS: 4
    BS: 3
    S: 3
    T: 4
    W: 1
    I: 2
    A: 1
    Ld: 9
  equipment_lists:
  - thunderer-equipment-list
  fixed_equipment: []
  equipment_restrictions: []
  skill_access: []
  source:
    manual: broheim.net
    printed_page: 28
    section: 0-5 Dwarf Thunderers
    url: https://broheim.net/downloads/campaigns/karakazgal/Karak Azgal.pdf
  source_path:
  - henchmen
  - 0-5 Dwarf Thunderers
  name_i18n:
    es: Tronadores Enanos
  rule_ids: []
  combat_traits: {}
