import { useState } from "react";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";

export function ManualCorrectionsPanel({knowledge,locale="en"}:{readonly document:CampaignDocument;readonly knowledge:ArtefactKnowledgeReader;readonly locale?:"es"|"en"}) {
  const app=useCampaignApp();const [resource,setResource]=useState(""),[delta,setDelta]=useState(0),[item,setItem]=useState(""),[quantity,setQuantity]=useState(1),[reason,setReason]=useState(""),[itemSearch,setItemSearch]=useState("");const itemName=(row:Record<string,unknown>)=>{const names=row.names as Record<string,unknown>|undefined;return String(names?.[locale]??names?.["en"]??row.item_id);};const items=knowledge.list("item"), filteredItems=items.filter((row)=>itemName(row).toLocaleLowerCase().includes(itemSearch.toLocaleLowerCase())).sort((a,b)=>itemName(a).localeCompare(itemName(b),locale)), selected=items.find((row)=>String(row.item_id)===item);const t=locale==="es"?{title:"Correcciones manuales",resource:"Recurso",delta:"Ajuste",item:"Objeto",quantity:"Cantidad",reason:"Motivo",search:"Buscar objeto",apply:"Aplicar recurso",add:"Añadir a reserva",selectResource:"Selecciona un recurso…",selectItem:"Selecciona un objeto…"}:{title:"Manual corrections",resource:"Resource",delta:"Adjustment",item:"Item",quantity:"Quantity",reason:"Reason",search:"Search item",apply:"Apply resource",add:"Add to stash",selectResource:"Select a resource…",selectItem:"Select an item…"};
  const resources=[["campaign_points",locale==="es"?"Puntos de campaña":"Campaign points"],["gold_crowns",locale==="es"?"Coronas de oro":"Gold crowns"],["wyrdstone_fragments",locale==="es"?"Fragmentos de piedra bruja":"Wyrdstone fragments"],["treasures",locale==="es"?"Tesoros":"Treasures"]].sort((a,b)=>a[1].localeCompare(b[1],locale));
  return <section aria-label={t.title}><h3>{t.title}</h3><label>{t.resource}<select value={resource} onChange={(event)=>setResource(event.target.value)}><option value="">{t.selectResource}</option>{resources.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>{t.delta}<input type="number" value={Number.isNaN(delta)?"":delta} onChange={(event)=>{const raw=event.target.valueAsNumber;setDelta(Number.isFinite(raw)&&Number.isInteger(raw)?raw:NaN);}}/></label><label>{t.reason}<input value={reason} onChange={(event)=>setReason(event.target.value)}/></label><button disabled={!resource||!reason.trim()||!delta} onClick={()=>void app.runAction("correctResource",{resource,delta,reason})}>{t.apply}</button><label>{t.search}<input value={itemSearch} onChange={(event)=>setItemSearch(event.target.value)} placeholder={locale==="es"?"Escribe para filtrar…":"Type to filter…"}/></label><label>{t.item}<select value={item} onChange={(event)=>setItem(event.target.value)}><option value="">{t.selectItem}</option>{filteredItems.map((row)=><option key={String(row.item_id)} value={String(row.item_id)}>{itemName(row)}</option>)}</select></label><label>{t.quantity}<input type="number" min="1" value={quantity} onChange={(event)=>setQuantity(Math.max(1,Math.trunc(event.target.valueAsNumber||1)))}/></label><button disabled={!reason.trim()||!selected} onClick={()=>selected&&void app.runAction("addManualStashItem",{item_id:selected.item_id,quantity,reason})}>{t.add}</button></section>;
}
