import { presentationOutput } from "../campaign/presentation-output";
import { translate } from "../campaign/i18n-core";
import { useLocale } from "../campaign/i18n-context";
import { useState } from "react";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";
import { knowledgeName } from "../campaign/displayText";
import { NumberStepper } from "../common/NumberStepper";

export function ManualCorrectionsPanel({knowledge,locale: requestedLocale}:{readonly document:CampaignDocument;readonly knowledge:ArtefactKnowledgeReader;readonly locale?:"es"|"en"}) {
  const locale = useLocale(requestedLocale);
  const app=useCampaignApp();const [resource,setResource]=useState(""),[delta,setDelta]=useState(0),[item,setItem]=useState(""),[quantity,setQuantity]=useState(1),[reason,setReason]=useState(""),[itemSearch,setItemSearch]=useState("");const itemName=(row:Record<string,unknown>)=>knowledgeName(knowledge,"item",row.item_id,locale);const items=knowledge.list("item"), filteredItems=items.filter((row)=>itemName(row).toLocaleLowerCase().includes(itemSearch.toLocaleLowerCase())).sort((a,b)=>itemName(a).localeCompare(itemName(b),locale)), selected=items.find((row)=>String(row.item_id)===item);const t=({ title: translate({ key: "ui.cf7b0254c9cf" }, locale), resource: translate({ key: "ui.8c9e951462e5" }, locale), delta: translate({ key: "ui.8a40e38c32a8" }, locale), item: translate({ key: "ui.cf471eb26f03" }, locale), quantity: translate({ key: "ui.8f2846965a7a" }, locale), reason: translate({ key: "ui.eb4f4db9befd" }, locale), search: translate({ key: "ui.105b3478b0cb" }, locale), apply: translate({ key: "ui.2d2a3da52117" }, locale), add: translate({ key: "ui.f0612465e77c" }, locale), selectResource: translate({ key: "ui.9ed6eeec7896" }, locale), selectItem: translate({ key: "ui.0ce8e4ce27f3" }, locale) });
  const resources: [string, ReturnType<typeof translate>][] = [["campaign_points",translate({ key: "ui.c329e59bd68a" }, locale)],["gold_crowns",translate({ key: "ui.ccc350b8a962" }, locale)],["wyrdstone_fragments",translate({ key: "ui.4bd30edf1030" }, locale)],["treasures",translate({ key: "ui.70ef4295b531" }, locale)]] ; resources.sort((a,b)=>a[1].localeCompare(b[1],locale));
  const resourceReason=!resource?(translate({ key: "ui.0dcf674379de" }, locale)):!delta?(translate({ key: "ui.ce064bad1bf9" }, locale)):!reason.trim()?(translate({ key: "ui.e5f5931dbb46" }, locale)):undefined;
  const itemReason=!selected?(translate({ key: "ui.f5d2dce53fec" }, locale)):!reason.trim()?(translate({ key: "ui.e5f5931dbb46" }, locale)):undefined;
  return <section aria-label={presentationOutput(t.title)}><h3>{presentationOutput(t.title)}</h3><label>{presentationOutput(t.resource)}<select value={resource} onChange={(event)=>setResource(event.target.value)}><option value="">{presentationOutput(t.selectResource)}</option>{resources.map(([value,label])=><option key={value} value={value}>{presentationOutput(label)}</option>)}</select></label><div className="warrior-control-row"><span>{presentationOutput(t.delta)}</span><NumberStepper locale={locale} label={translate({ key: "number.delta" }, locale)} value={Number.isFinite(delta)?delta:0} min={-Infinity} max={Infinity} onChange={setDelta}/></div><label>{presentationOutput(t.reason)}<input value={reason} onChange={(event)=>setReason(event.target.value)}/></label><button disabled={Boolean(resourceReason)} data-disabled-reason={(resourceReason) === undefined ? undefined : presentationOutput((resourceReason)!)} onClick={()=>void app.runAction("correctResource",{resource,delta,reason})}>{presentationOutput(t.apply)}</button><label>{presentationOutput(t.search)}<input value={itemSearch} onChange={(event)=>setItemSearch(event.target.value)} placeholder={presentationOutput(translate({ key: "ui.c510b1ecd70b" }, locale))}/></label><label>{presentationOutput(t.item)}<select value={item} onChange={(event)=>setItem(event.target.value)}><option value="">{presentationOutput(t.selectItem)}</option>{filteredItems.map((row)=><option key={String(row.item_id)} value={String(row.item_id)}>{presentationOutput(itemName(row))}</option>)}</select></label><div className="warrior-control-row"><span>{presentationOutput(t.quantity)}</span><NumberStepper locale={locale} label={translate({ key: "number.quantity" }, locale)} value={quantity} min={1} onChange={setQuantity}/></div><button disabled={Boolean(itemReason)} data-disabled-reason={(itemReason) === undefined ? undefined : presentationOutput((itemReason)!)} onClick={()=>selected&&void app.runAction("addManualStashItem",{item_id:selected.item_id,quantity,reason})}>{presentationOutput(t.add)}</button></section>;
}
