import { useState } from "react";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";

export function ManualCorrectionsPanel({document,knowledge,locale="en"}:{readonly document:CampaignDocument;readonly knowledge:ArtefactKnowledgeReader;readonly locale?:"es"|"en"}) {
  const app=useCampaignApp();const [resource,setResource]=useState("gold_crowns"),[delta,setDelta]=useState(0),[item,setItem]=useState(""),[quantity,setQuantity]=useState(1),[reason,setReason]=useState("");const items=knowledge.list("item"), selected=items.find((row)=>String(row.item_id)===item)??items[0];const t=locale==="es"?{title:"Correcciones manuales",resource:"Recurso",delta:"Ajuste",item:"Objeto",quantity:"Cantidad",reason:"Motivo",apply:"Aplicar recurso",add:"Añadir a reserva"}:{title:"Manual corrections",resource:"Resource",delta:"Adjustment",item:"Item",quantity:"Quantity",reason:"Reason",apply:"Apply resource",add:"Add to stash"};
  return <section aria-label="Manual corrections"><h3>{t.title}</h3><label>{t.resource}<select value={resource} onChange={(event)=>setResource(event.target.value)}><option value="gold_crowns">Gold crowns</option><option value="wyrdstone_fragments">Wyrdstone fragments</option><option value="treasures">Treasures</option><option value="campaign_points">Campaign points</option></select></label><label>{t.delta}<input type="number" value={delta} onChange={(event)=>setDelta(Math.trunc(event.target.valueAsNumber||0))}/></label><label>{t.reason}<input value={reason} onChange={(event)=>setReason(event.target.value)}/></label><button disabled={!reason.trim()||!delta} onClick={()=>void app.runAction("correctResource",{resource,delta,reason})}>{t.apply}</button><label>{t.item}<select value={String(selected?.item_id??"")} onChange={(event)=>setItem(event.target.value)}>{items.map((row)=><option key={String(row.item_id)} value={String(row.item_id)}>{String(row.names?.[locale]??row.names?.en??row.item_id)}</option>)}</select></label><label>{t.quantity}<input type="number" min="1" value={quantity} onChange={(event)=>setQuantity(Math.max(1,Math.trunc(event.target.valueAsNumber||1)))}/></label><button disabled={!reason.trim()||!selected} onClick={()=>selected&&void app.runAction("addManualStashItem",{item_id:selected.item_id,quantity,reason})}>{t.add}</button></section>;
}
