import { useMemo, useState } from "react";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import { quoteWyrdstoneSale } from "@app/campaign/features/economy/wyrdstone-sale-workflow";
import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";

export function WyrdstoneSalePanel({document,knowledge,locale="en"}:{readonly document:CampaignDocument;readonly knowledge:ArtefactKnowledgeReader;readonly locale?:"es"|"en"}) {
  const app=useCampaignApp(); const post=document.campaign.post_battles.find((row)=>!row.complete); const [quantity,setQuantity]=useState(0); const quote=useMemo(()=>quoteWyrdstoneSale(document,knowledge,quantity),[document,knowledge,quantity]); if(!post)return null;
  const t=locale==="es"?{title:"Vender piedra bruja",resolved:"Venta resuelta",sold:"fragmentos vendidos",gained:"Oro ganado",first:"Completa exploración y su resultado especial antes.",available:"Disponible",size:"Tamaño de banda",value:"Valor de venta",shards:"Fragmentos a vender",confirm:"Confirmar venta una vez"}:{title:"Sell wyrdstone",resolved:"Sale resolved",sold:"shard(s) sold",gained:"Gold gained",first:"Complete exploration and its special result first.",available:"Available",size:"Warband size",value:"Sale value",shards:"Shards to sell",confirm:"Confirm sale once"};
  const exploration=Boolean(post.step_state?.["exploration"]); const followup=(post.pending_follow_ups??[]).some((row)=>row["type"]==="exploration_followup");
  return <section aria-label={t.title}><h3>04 · {t.title}</h3>{post.sale_resolved?<p role="status">{t.resolved}: {post.wyrdstone_sold??0} {t.sold}. {t.gained}: {quoteWyrdstoneSale(document,knowledge,post.wyrdstone_sold??0).profit} gc.</p>:!exploration||followup?<p role="status">{t.first}</p>:<><dl className="campaign-metrics"><div><dt>{t.available}</dt><dd>{quote.available}</dd></div><div><dt>{t.size}</dt><dd>{quote.warband_size}</dd></div><div><dt>{t.value}</dt><dd>{quote.profit} gc</dd></div></dl><label>{t.shards}<input type="number" min={0} max={quote.available} step={1} value={quantity} onChange={(event)=>setQuantity(Math.max(0,Math.trunc(event.target.valueAsNumber||0)))}/></label><button className="primary" disabled={quantity>quote.available} data-disabled-reason={quantity>quote.available ? (locale==="es"?"No tienes suficiente Piedra bruja.":"You do not have enough Wyrdstone.") : undefined} onClick={()=>void app.runAction("sellWyrdstone",{quantity})}>{t.confirm}</button></>}</section>;
}
