import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import type { OpenPayload } from "@domain/campaign/index";
import { DiceResolver } from "../dice/DiceResolver";
import { useCampaignApp } from "../campaign/useCampaignApp";
import type { CampaignDocument } from "../campaign/types";
import { promotionHeroTables, wizardLore } from "@app/campaign/features/advances/advance-resolution-workflow";
import { knowledgeName, localizedLabel } from "../campaign/displayText";
import { useMemo, useState } from "react";

function PromotionOffer({ warriorId, threshold, locale }: { warriorId: string; threshold: number | null; locale:"es"|"en" }) {
  const app=useCampaignApp(); const [name,setName]=useState("");
  return <form className="inline-form" onSubmit={(event)=>{event.preventDefault();void app.runAction("promoteHenchman",{warrior_id:warriorId,threshold,member_name:name.trim()});}}><label>{locale==="es"?"Nombre del nuevo Héroe":"New Hero name"}<input required value={name} onChange={(event)=>setName(event.target.value)}/></label><button className="primary" disabled={!name.trim()} data-disabled-reason={!name.trim() ? (locale==="es"?"Introduce el nombre del nuevo héroe.":"Enter the new Hero name.") : undefined}>{locale==="es"?"Promover miembro":"Promote member"}</button></form>;
}

function PromotionSetup({ document, knowledge, warriorId, locale }: { document: CampaignDocument; knowledge: ArtefactKnowledgeReader; warriorId: string; locale:"es"|"en" }) {
  const app=useCampaignApp(); const [selected,setSelected]=useState<string[]>([]); const tables=promotionHeroTables(document,knowledge);
  return <fieldset><legend>{locale==="es"?"Elige exactamente dos listas de habilidades de Héroe":"Choose exactly two future Hero skill lists"}</legend>{tables.map((table)=><label key={table}><input type="checkbox" checked={selected.includes(table)} disabled={!selected.includes(table)&&selected.length>=2} data-disabled-reason={!selected.includes(table)&&selected.length>=2 ? (locale==="es"?"Ya has seleccionado el máximo de dos listas.":"You have already selected the maximum of two lists.") : undefined} onChange={(event)=>setSelected((current)=>event.target.checked?[...current,table]:current.filter((item)=>item!==table))}/>{localizedLabel(table, locale)}</label>)}<button className="primary" disabled={selected.length!==2} data-disabled-reason={selected.length!==2 ? (locale==="es"?"Selecciona exactamente dos listas de habilidades.":"Select exactly two skill lists.") : undefined} onClick={()=>void app.runAction("setPromotionSkillTables",{warrior_id:warriorId,tables:selected})}>{locale==="es"?"Confirmar listas":"Confirm skill lists"}</button></fieldset>;
}

export function AdvancesPanel({ document, knowledge, locale="en" }: { readonly document: CampaignDocument; readonly knowledge: ArtefactKnowledgeReader; readonly locale?:"es"|"en" }) {
  const app = useCampaignApp();
  const [processing, setProcessing] = useState<string | null>(null);
  const post = document.campaign.post_battles.find((row) => !row.complete);
  const rows = (post?.pending_advances ?? []) as readonly OpenPayload[];
  const t=locale==="es"?{title:"Avances",earned:"Tiradas de avance conseguidas",none:"Ningún guerrero cruzó un umbral de experiencia.",immediate:"avance inmediato",threshold:"umbral de EXP",committed:"Confirmado",pending:"Pendiente",roll:"Tirada de avance · 2D6",subroll:"Subtirada de característica tras",skill:"Elige habilidad",select:"Elige una habilidad permitida…",spell:"Generar hechizo",spellSelect:"Elige hechizo de",known:"ya conocido: dificultad −1",external:"Registrar resolución externa"}:{title:"Advances",earned:"Advance rolls earned this sequence",none:"No warrior crossed an experience threshold.",immediate:"immediate advance",threshold:"XP threshold",committed:"Committed",pending:"Pending",roll:"Advance roll · 2D6",subroll:"Characteristic sub-roll after",skill:"Choose skill",select:"Select a permitted skill…",spell:"Generate spell",spellSelect:"Select a spell from",known:"already known: −1 difficulty",external:"Record external resolution"};
  const skillCatalogue = useMemo(() => knowledge.list("skill").map((skill) => ({ skill, name: knowledgeName(knowledge, "skill", skill["id"], locale, skill["name"]) })).sort((a,b)=>a.name.localeCompare(b.name,locale)), [knowledge, locale]);
  const runAdvance = async (key: string, action: string, input: Record<string, unknown>) => { if (processing) return; setProcessing(key); try { await app.runAction(action, input); } finally { setProcessing(null); } };
  if (rows.length === 0) return <section aria-label={t.title}><h4>{t.earned}</h4><p role="status">{t.none}</p></section>;
  return <section aria-label={t.title} aria-busy={Boolean(processing)}><h4>{t.earned}</h4>{processing && <p className="advance-processing" role="status" aria-live="polite"><span className="operation-spinner" aria-hidden="true" />{locale === "es" ? "Procesando la tirada y actualizando los avances…" : "Processing the roll and updating advances…"}</p>}<table className="mobile-cards advance-results"><caption>{t.earned}</caption><thead><tr><th>{locale==="es"?"Guerrero":"Warrior"}</th><th>{locale==="es"?"Resultado":"Result"}</th><th>{locale==="es"?"Tiradas y decisiones pendientes":"Pending rolls and decisions"}</th></tr></thead><tbody>{rows.map((row, index) => {
    const id = String(row["warrior_id"]); const threshold = row["threshold"] == null ? null : Number(row["threshold"]); const warrior = document.campaign.warriors.find((item) => item.id === id);
    const committed = Boolean(row["committed"]); const total = row["roll_total"] == null ? null : Number(row["roll_total"]); const choices = (row["advance_options"] ?? []) as OpenPayload[];
    const promotionSetup=Boolean(row["promotion_setup_pending"]);
    const needsSubroll = total !== null && !committed && choices.length === 0;
    const skills = skillCatalogue.filter(({ skill }) => !warrior?.skill_access?.length || warrior.skill_access.includes(String(skill["category"] ?? "")));
    const needsSpells = choices.some((choice) => choice["kind"] === "generate_spell"); const loreId = needsSpells && warrior ? wizardLore(knowledge, document, warrior) : null; const lore = loreId ? knowledge.queryKnowledge({ id: { kind: "lore_id", value: loreId } }) : null; const spells = lore?.ok ? (lore.record.data["spells"] ?? []) as readonly Record<string, unknown>[] : [];
    return <tr key={`${id}:${String(threshold)}:${index}`}><td data-label={locale==="es"?"Guerrero":"Warrior"}><strong>{warrior?.name ?? (locale === "es" ? "Guerrero no disponible" : "Warrior unavailable")}</strong><small>{localizedLabel(row["table"] ?? "hero", locale)} · {threshold === null ? t.immediate : `${threshold} ${t.threshold}`}</small></td><td data-label={locale==="es"?"Resultado":"Result"}><strong>{committed ? String(row["applied_label"] ?? t.committed) : total === null ? t.pending : `${locale==="es"?"Tirada":"Roll"}: ${total}`}</strong>{((row["roll_history"] ?? []) as string[]).map((message) => <small key={message}>{message}</small>)}</td><td data-label={locale==="es"?"Tiradas y decisiones pendientes":"Pending rolls and decisions"}>
      {promotionSetup && <PromotionSetup document={document} knowledge={knowledge} warriorId={id} locale={locale}/>}
      {!promotionSetup && !committed && total === null && <DiceResolver disabled={Boolean(processing)} key={`advance:${id}:${String(threshold)}:main`} locale={locale} count={2} sides={6} label={t.roll} onResolve={(dice) => void runAdvance(`roll:${id}:${threshold}`, "resolveAdvanceRoll", { warrior_id: id, threshold, roll_total: dice[0] + dice[1] })} />}
      {needsSubroll && <DiceResolver disabled={Boolean(processing)} key={`advance:${id}:${String(threshold)}:subroll:${total}`} locale={locale} count={1} sides={6} label={`${t.subroll} ${total} · D6`} onResolve={(dice) => void runAdvance(`subroll:${id}:${threshold}`, "resolveAdvanceRoll", { warrior_id: id, threshold, roll_total: total, subroll: dice[0] })} />}
      {!committed && choices.some((choice) => choice["kind"] === "characteristic_increase") && <div className="button-row">{choices.filter((choice) => choice["kind"] === "characteristic_increase").map((choice) => <button disabled={Boolean(processing)} key={String(choice["characteristic"])} onClick={() => void runAdvance(`choice:${id}:${threshold}`, "commitAdvanceChoice", { warrior_id: id, threshold, kind: "characteristic_increase", characteristic: choice["characteristic"] })}>+{String(choice["amount"] ?? 1)} {String(choice["characteristic"])}</button>)}</div>}
      {!committed && choices.some((choice) => choice["kind"] === "choose_skill") && <label>{t.skill}<select disabled={Boolean(processing)} defaultValue="" onChange={(event) => { if (event.target.value) void runAdvance(`skill:${id}:${threshold}`, "commitAdvanceChoice", { warrior_id: id, threshold, kind: "choose_skill", skill_id: event.target.value }); }}><option value="" disabled>{t.select}</option>{skills.map(({ skill, name }) => <option value={String(skill["id"])} key={String(skill["id"])}>{name}</option>)}</select></label>}
      {!committed && choices.some((choice) => choice["kind"] === "promote_henchman") && <PromotionOffer warriorId={id} threshold={threshold} locale={locale}/>}
      {!committed && choices.some((choice) => choice["kind"] === "generate_spell") && <label>{t.spell}<select defaultValue="" onChange={(event) => { const spell=spells.find((item)=>item["id"]===event.target.value); const duplicate=warrior?.skills.includes(String(spell?.["name"]??"")); if(event.target.value) void app.runAction("commitAdvanceChoice", { warrior_id:id,threshold,kind:duplicate?"duplicate_spell":"generate_spell",skill_id:event.target.value }); }}><option value="" disabled>{t.spellSelect} {loreId ? knowledgeName(knowledge, "lore", loreId, locale, localizedLabel(loreId, locale)) : ""}…</option>{[...spells].sort((a,b)=>String(a["name"]??a["id"]).localeCompare(String(b["name"]??b["id"]),locale)).map((spell)=><option value={String(spell["id"])} key={String(spell["id"])}>{knowledgeName(knowledge, "skill", spell["id"], locale, spell["name"])}{warrior?.skills.includes(String(spell["name"]))?` · ${t.known}`:""}</option>)}</select></label>}
      {!committed && choices.some((choice) => choice["kind"] === "external_resolution") && <button disabled={Boolean(processing)} onClick={() => void runAdvance(`external:${id}:${threshold}`, "commitAdvanceChoice", { warrior_id:id, threshold, kind:"external_resolution" })}>{t.external}</button>}
      {committed && <span>{total === null ? t.committed : `${locale==="es"?"Tirada":"Roll"}: ${total}${row["subroll"] == null ? "" : ` · D6: ${row["subroll"]}`}`}</span>}
    </td></tr>;
  })}</tbody></table></section>;
}
