import { presentationOutput } from "../campaign/presentation-output";
import { textJoin, textNumber, textSymbol, textDice, warriorPersonalName } from "../campaign/presentation-values";
import { translate } from "../campaign/i18n-core";
import { useLocale } from "../campaign/i18n-context";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import type { OpenPayload } from "@domain/campaign/index";
import { DiceResolver } from "../dice/DiceResolver";
import { useCampaignApp } from "../campaign/useCampaignApp";
import type { CampaignDocument } from "../campaign/types";
import { promotionHeroTables, wizardLore } from "@app/campaign/features/advances/advance-resolution-workflow";
import { knowledgeName, localizedLabel } from "../campaign/displayText";
import { advanceResultDetails, advanceResultText } from "./advanceResultText";
import { KnowledgeHint } from "../campaign/KnowledgeHint";
import { useMemo, useState } from "react";

function PromotionOffer({ warriorId, threshold, locale }: { warriorId: string; threshold: number | null; locale:"es"|"en" }) {
  const app=useCampaignApp(); const [name,setName]=useState("");
  return <form className="inline-form" onSubmit={(event)=>{event.preventDefault();void app.runAction("promoteHenchman",{warrior_id:warriorId,threshold,member_name:name.trim()});}}><label>{presentationOutput(translate({ key: "ui.a87571d8e50b" }, locale))}<input required value={name} onChange={(event)=>setName(event.target.value)}/></label><button className="primary" disabled={!name.trim()} data-disabled-reason={!name.trim() ? presentationOutput(translate({ key: "disabled.8c97da99fa" }, locale)) : undefined}>{presentationOutput(translate({ key: "ui.d76b22a18b22" }, locale))}</button></form>;
}

function PromotionSetup({ document, knowledge, warriorId, locale }: { document: CampaignDocument; knowledge: ArtefactKnowledgeReader; warriorId: string; locale:"es"|"en" }) {
  const app=useCampaignApp(); const [selected,setSelected]=useState<string[]>([]); const tables=promotionHeroTables(document,knowledge);
  return <fieldset><legend>{presentationOutput(translate({ key: "ui.d524ac64caf5" }, locale))}</legend>{tables.map((table)=><label key={table}><input type="checkbox" checked={selected.includes(table)} disabled={!selected.includes(table)&&selected.length>=2} data-disabled-reason={!selected.includes(table)&&selected.length>=2 ? presentationOutput(translate({ key: "disabled.2c5f879a96" }, locale)) : undefined} onChange={(event)=>setSelected((current)=>event.target.checked?[...current,table]:current.filter((item)=>item!==table))}/>{presentationOutput(localizedLabel(table, locale))}</label>)}<button className="primary" disabled={selected.length!==2} data-disabled-reason={selected.length!==2 ? presentationOutput(translate({ key: "disabled.b4f4928f05" }, locale)) : undefined} onClick={()=>void app.runAction("setPromotionSkillTables",{warrior_id:warriorId,tables:selected})}>{presentationOutput(translate({ key: "ui.7290ecbbca36" }, locale))}</button></fieldset>;
}

export function AdvancesPanel({ document, knowledge, locale: requestedLocale }: { readonly document: CampaignDocument; readonly knowledge: ArtefactKnowledgeReader; readonly locale?:"es"|"en" }) {
  const locale = useLocale(requestedLocale);
  const app = useCampaignApp();
  const [processing, setProcessing] = useState<string | null>(null);
  const post = document.campaign.post_battles.find((row) => !row.complete);
  const rows = (post?.pending_advances ?? []) as readonly OpenPayload[];
  const t=({ title: translate({ key: "ui.01bf66ea165f" }, locale), earned: translate({ key: "ui.f18f7ad3ca04" }, locale), none: translate({ key: "ui.f675964cde10" }, locale), immediate: translate({ key: "ui.2b6d749dd546" }, locale), threshold: translate({ key: "ui.3404f7cdf1b2" }, locale), committed: translate({ key: "ui.bb7710e2d88e" }, locale), pending: translate({ key: "ui.8071fe9b52ff" }, locale), roll: translate({ key: "ui.21514234e5bd" }, locale), subroll: translate({ key: "ui.87a673c9f588" }, locale), skill: translate({ key: "ui.05042f3e88cd" }, locale), select: translate({ key: "ui.0b420490a2f2" }, locale), spell: translate({ key: "ui.f7b291590e00" }, locale), spellSelect: translate({ key: "ui.86fb4cbcc7cd" }, locale), known: translate({ key: "ui.2c75b2d3f397" }, locale), external: translate({ key: "ui.9f3130d3519d" }, locale) });
  const skillCatalogue = useMemo(() => knowledge.list("skill").map((skill) => ({ skill, name: knowledgeName(knowledge, "skill", skill["id"], locale) })).sort((a,b)=>a.name.localeCompare(b.name,locale)), [knowledge, locale]);
  const runAdvance = async (key: string, action: string, input: Record<string, unknown>) => { if (processing) return; setProcessing(key); try { await app.runAction(action, input); } finally { setProcessing(null); } };
  if (rows.length === 0) return <section aria-label={presentationOutput(t.title)}><h4>{presentationOutput(t.earned)}</h4><p role="status">{presentationOutput(t.none)}</p></section>;
  return <section aria-label={presentationOutput(t.title)} aria-busy={Boolean(processing)}><h4>{presentationOutput(t.earned)}</h4>{processing && <p className="advance-processing" role="status" aria-live="polite"><span className="operation-spinner" aria-hidden="true" />{presentationOutput(translate({ key: "ui.b05a48d072f7" }, locale))}</p>}<table className="mobile-cards advance-results"><caption>{presentationOutput(t.earned)}</caption><thead><tr><th>{presentationOutput(translate({ key: "ui.dca4e7aa700c" }, locale))}</th><th>{presentationOutput(translate({ key: "ui.0a91171a8d9f" }, locale))}</th><th>{presentationOutput(translate({ key: "ui.e9906fb3a302" }, locale))}</th></tr></thead><tbody>{rows.map((row, index) => {
    const id = String(row["warrior_id"]); const threshold = row["threshold"] == null ? null : Number(row["threshold"]); const warrior = document.campaign.warriors.find((item) => item.id === id);
    const committed = Boolean(row["committed"]); const total = row["roll_total"] == null ? null : Number(row["roll_total"]); const choices = (row["advance_options"] ?? []) as OpenPayload[];
    const promotionSetup=Boolean(row["promotion_setup_pending"]);
    const needsSubroll = total !== null && !committed && choices.length === 0;
    const skills = skillCatalogue.filter(({ skill }) => !warrior?.skill_access?.length || warrior.skill_access.includes(String(skill["category"] ?? "")));
    const needsSpells = choices.some((choice) => choice["kind"] === "generate_spell"); const loreId = needsSpells && warrior ? wizardLore(knowledge, document, warrior) : null; const lore = loreId ? knowledge.queryKnowledge({ id: { kind: "lore_id", value: loreId } }) : null; const spells = lore?.ok ? (lore.record.data["spells"] ?? []) as readonly Record<string, unknown>[] : [];
    const storedHistory = row["roll_history_events"] ?? row["roll_history"] ?? []; const history = Array.isArray(storedHistory) ? storedHistory : [undefined];
    const result = advanceResultDetails(row["applied_result"] ?? row["applied_label"] ?? t.committed, knowledge, locale);
    return <tr key={`${id}:${String(threshold)}:${index}`}><td data-label={presentationOutput(translate({ key: "ui.dca4e7aa700c" }, locale))}><strong>{presentationOutput(warriorPersonalName(warrior, locale))}</strong><small>{presentationOutput(textJoin([localizedLabel(row["table"] ?? "hero", locale), threshold === null ? t.immediate : textJoin([textNumber(threshold, locale), t.threshold])], " · "))}</small></td><td data-label={presentationOutput(translate({ key: "ui.0a91171a8d9f" }, locale))}><strong>{committed ? result.skillId ? <>{presentationOutput(result.text)} <KnowledgeHint knowledge={knowledge} kind="skill" id={result.skillId} locale={locale} compact /></> : presentationOutput(result.text) : presentationOutput(total === null ? t.pending : textJoin([translate({ key: "ui.9a5040b02281" }, locale), textNumber(total, locale)]))}</strong>{history.map((message, historyIndex) => <small key={historyIndex}>{presentationOutput(advanceResultText(message, knowledge, locale))}</small>)}</td><td data-label={presentationOutput(translate({ key: "ui.e9906fb3a302" }, locale))}>
      {promotionSetup && <PromotionSetup document={document} knowledge={knowledge} warriorId={id} locale={locale}/>}
      {!promotionSetup && !committed && total === null && <DiceResolver disabled={Boolean(processing)} key={`advance:${id}:${String(threshold)}:main`} locale={locale} count={2} sides={6} label={t.roll} onResolve={(dice) => void runAdvance(`roll:${id}:${threshold}`, "resolveAdvanceRoll", { warrior_id: id, threshold, roll_total: dice[0] + dice[1] })} />}
      {needsSubroll && <DiceResolver disabled={Boolean(processing)} key={`advance:${id}:${String(threshold)}:subroll:${total}`} locale={locale} count={1} sides={6} label={textJoin([t.subroll, textNumber(total, locale), textDice(1, 6, locale)])} onResolve={(dice) => void runAdvance(`subroll:${id}:${threshold}`, "resolveAdvanceRoll", { warrior_id: id, threshold, roll_total: total, subroll: dice[0] })} />}
      {!committed && choices.some((choice) => choice["kind"] === "characteristic_increase") && <div className="button-row">{choices.filter((choice) => choice["kind"] === "characteristic_increase").map((choice) => <button disabled={Boolean(processing)} key={String(choice["characteristic"])} onClick={() => void runAdvance(`choice:${id}:${threshold}`, "commitAdvanceChoice", { warrior_id: id, threshold, kind: "characteristic_increase", characteristic: choice["characteristic"] })}>{presentationOutput(textJoin([textJoin([textSymbol("+"), textNumber(choice["amount"] ?? 1, locale)], ""), localizedLabel(choice["characteristic"], locale)]))}</button>)}</div>}
      {!committed && choices.some((choice) => choice["kind"] === "choose_skill") && <label>{presentationOutput(t.skill)}<select disabled={Boolean(processing)} defaultValue="" onChange={(event) => { if (event.target.value) void runAdvance(`skill:${id}:${threshold}`, "commitAdvanceChoice", { warrior_id: id, threshold, kind: "choose_skill", skill_id: event.target.value }); }}><option value="" disabled>{presentationOutput(t.select)}</option>{skills.map(({ skill, name }) => <option value={String(skill["id"])} key={String(skill["id"])}>{presentationOutput(name)}</option>)}</select></label>}
      {!committed && choices.some((choice) => choice["kind"] === "promote_henchman") && <PromotionOffer warriorId={id} threshold={threshold} locale={locale}/>}
      {!committed && choices.some((choice) => choice["kind"] === "generate_spell") && <label>{presentationOutput(t.spell)}<select defaultValue="" onChange={(event) => { const spell=spells.find((item)=>item["id"]===event.target.value); const duplicate=warrior?.skills.includes(String(spell?.["name"]??"")); if(event.target.value) void app.runAction("commitAdvanceChoice", { warrior_id:id,threshold,kind:duplicate?"duplicate_spell":"generate_spell",skill_id:event.target.value }); }}><option value="" disabled>{presentationOutput(textJoin([t.spellSelect, ...(loreId ? [knowledgeName(knowledge, "lore", loreId, locale)] : [])]))}</option>{[...spells].sort((a,b)=>String(a["name"]??a["id"]).localeCompare(String(b["name"]??b["id"]),locale)).map((spell)=><option value={String(spell["id"])} key={String(spell["id"])}>{presentationOutput(knowledgeName(knowledge, "skill", spell["id"], locale))}{presentationOutput(warrior?.skills.includes(String(spell["name"])) ? t.known : textSymbol(""))}</option>)}</select></label>}
      {!committed && choices.some((choice) => choice["kind"] === "external_resolution") && <button disabled={Boolean(processing)} onClick={() => void runAdvance(`external:${id}:${threshold}`, "commitAdvanceChoice", { warrior_id:id, threshold, kind:"external_resolution" })}>{presentationOutput(t.external)}</button>}
      {committed && <span>{presentationOutput(total === null ? t.committed : textJoin([translate({ key: "ui.9a5040b02281" }, locale), textNumber(total, locale), ...(row["subroll"] == null ? [] : [textDice(1, 6, locale), textNumber(row["subroll"], locale)])]))}</span>}
    </td></tr>;
  })}</tbody></table></section>;
}
