import { warriorPersonalName } from "../campaign/presentation-values";
import { presentationOutput } from "../campaign/presentation-output";
import { translate } from "../campaign/i18n-core";
import { useLocale } from "../campaign/i18n-context";
import { useState } from "react";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";
import { knowledgeName } from "../campaign/displayText";

export function ManualSkillPanel({document,knowledge,locale: requestedLocale}:{readonly document:CampaignDocument;readonly knowledge:ArtefactKnowledgeReader;readonly locale?:"es"|"en"}) {
  const locale = useLocale(requestedLocale);
  const app=useCampaignApp(); const [warriorId,setWarriorId]=useState("");const [skillId,setSkillId]=useState("");const [reason,setReason]=useState(""); const warriors=[...document.campaign.warriors].sort((a,b)=>a.name.localeCompare(b.name,locale)); const skillName=(row:Record<string,unknown>)=>knowledgeName(knowledge,"skill",row.id,locale);const skills=[...knowledge.list("skill")].sort((a,b)=>skillName(a).localeCompare(skillName(b),locale)); const warrior=warriors.find((row)=>row.id===warriorId); const skill=skills.find((row)=>String(row.id)===skillId); const t=({ title: translate({ key: "ui.9bcbe91b98e4" }, locale), warrior: translate({ key: "ui.dca4e7aa700c" }, locale), skill: translate({ key: "ui.842e16b36c7d" }, locale), reason: translate({ key: "ui.eb4f4db9befd" }, locale), add: translate({ key: "ui.193fb5a7cea2" }, locale), remove: translate({ key: "ui.1e6fa3c57aa1" }, locale), selectWarrior: translate({ key: "ui.e9ef132ca653" }, locale), selectSkill: translate({ key: "ui.88d46d36996d" }, locale) });
  if(warriors.length===0||skills.length===0)return null; const run=(present:boolean)=>warrior&&skill&&void app.runAction("setManualSkill",{warrior_id:warrior.id,skill_id:String(skill.id),present,reason});
  const blockedReason=!warrior?(translate({ key: "ui.893dd851cac5" }, locale)):!skill?(translate({ key: "ui.55dfb8188281" }, locale)):!reason.trim()?(translate({ key: "ui.e5f5931dbb46" }, locale)):undefined;
  return <section aria-label={presentationOutput(t.title)}><h3>{presentationOutput(t.title)}</h3><label>{presentationOutput(t.warrior)}<select value={warriorId} onChange={(event)=>setWarriorId(event.target.value)}><option value="">{presentationOutput(t.selectWarrior)}</option>{warriors.map((row)=><option key={row.id} value={row.id}>{presentationOutput(warriorPersonalName(row, locale))}</option>)}</select></label><label>{presentationOutput(t.skill)}<select value={skillId} onChange={(event)=>setSkillId(event.target.value)}><option value="">{presentationOutput(t.selectSkill)}</option>{skills.map((row)=><option key={String(row.id)} value={String(row.id)}>{presentationOutput(skillName(row))}</option>)}</select></label><label>{presentationOutput(t.reason)}<input value={reason} onChange={(event)=>setReason(event.target.value)}/></label><button className="primary" disabled={Boolean(blockedReason)} data-disabled-reason={(blockedReason) === undefined ? undefined : presentationOutput((blockedReason)!)} onClick={()=>run(true)}>{presentationOutput(t.add)}</button><button disabled={Boolean(blockedReason)} data-disabled-reason={(blockedReason) === undefined ? undefined : presentationOutput((blockedReason)!)} onClick={()=>run(false)}>{presentationOutput(t.remove)}</button></section>;
}
