import { useState } from "react";
import type { ArtefactKnowledgeReader } from "@adapters/knowledge-reader/index";
import type { CampaignDocument } from "../campaign/types";
import { useCampaignApp } from "../campaign/useCampaignApp";

export function ManualSkillPanel({document,knowledge,locale="en"}:{readonly document:CampaignDocument;readonly knowledge:ArtefactKnowledgeReader;readonly locale?:"es"|"en"}) {
  const app=useCampaignApp(); const [warriorId,setWarriorId]=useState("");const [skillId,setSkillId]=useState("");const [reason,setReason]=useState(""); const warriors=[...document.campaign.warriors].sort((a,b)=>a.name.localeCompare(b.name,locale)); const skillName=(row:Record<string,unknown>)=>{const names=row.names as Record<string,unknown>|undefined;return String(names?.[locale]??names?.["en"]??row.id);};const skills=[...knowledge.list("skill")].sort((a,b)=>skillName(a).localeCompare(skillName(b),locale)); const warrior=warriors.find((row)=>row.id===warriorId); const skill=skills.find((row)=>String(row.id)===skillId); const t=locale==="es"?{title:"Corrección manual de habilidades",warrior:"Guerrero",skill:"Habilidad",reason:"Motivo",add:"Añadir",remove:"Quitar",selectWarrior:"Selecciona un guerrero…",selectSkill:"Selecciona una habilidad…"}:{title:"Manual skill correction",warrior:"Warrior",skill:"Skill",reason:"Reason",add:"Add",remove:"Remove",selectWarrior:"Select a warrior…",selectSkill:"Select a skill…"};
  if(warriors.length===0||skills.length===0)return null; const run=(present:boolean)=>warrior&&skill&&void app.runAction("setManualSkill",{warrior_id:warrior.id,skill_id:String(skill.id),present,reason});
  const blockedReason=!warrior?(locale==="es"?"Selecciona un guerrero.":"Select a warrior."):!skill?(locale==="es"?"Selecciona una habilidad.":"Select a skill."):!reason.trim()?(locale==="es"?"Explica el motivo de la corrección.":"Explain the reason for the correction."):undefined;
  return <section aria-label={t.title}><h3>{t.title}</h3><label>{t.warrior}<select value={warriorId} onChange={(event)=>setWarriorId(event.target.value)}><option value="">{t.selectWarrior}</option>{warriors.map((row)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>{t.skill}<select value={skillId} onChange={(event)=>setSkillId(event.target.value)}><option value="">{t.selectSkill}</option>{skills.map((row)=><option key={String(row.id)} value={String(row.id)}>{skillName(row)}</option>)}</select></label><label>{t.reason}<input value={reason} onChange={(event)=>setReason(event.target.value)}/></label><button className="primary" disabled={Boolean(blockedReason)} data-disabled-reason={blockedReason} onClick={()=>run(true)}>{t.add}</button><button disabled={Boolean(blockedReason)} data-disabled-reason={blockedReason} onClick={()=>run(false)}>{t.remove}</button></section>;
}
